### ISSUE TITLE
Place holder text and screen readers [accessibility]

### ISSUE THREAD

**Issue by BillyTheKidd88** [shentao/vue-multiselect#1000]
### Reproduction Link
https://jsfiddle.net/5aeonxLg/1/

### Steps to reproduce
1) Start a screen reader
2) Remove the default selected value from the vue-multiselect.
3) Focus on the vue-multiselect
4) Press tab to move out of the vue-multiselect

### Expected behaviour
Placeholder text is not read when focus of the vue-multiselect is lost.

### Actual behaviour
Placeholder text is read when focus of the vue-multiselect is lost.

### Other thoughts
So this happens when aria-relevant is set to "additions". Since the placeholder text is a span that is added and removed from the page, it gets read when aria-relevant="additions". I had some thoughts as to how this could be avoided by using v-bind:style instead of v-if inside the span tag for the placeholder text.

**Comment by jag1989** [comment]
@BillyTheKidd88 What was your outcome for this? Having the same issue on a project I'm also working on.

**Comment by BillyTheKidd88** [comment]
I ended up just removing aria-live and aria-relevant from the vue-multiselects. The guy before me added those properties for some reason, but they may have become obsolete after some other changes (see #1007). If you remove those properties from your vue-multiselects does it mess up what the screen reader reads?
