### ISSUE TITLE
How to use v-model as record id but display record description

### ISSUE THREAD

**Issue by paulsimongb** [shentao/vue-multiselect#1003]
This is not a bug report but more a question that I cannot figure out how to do something that should be a very common scenario.

With a conventional HTML select I have a single select, I can have the v-model as the selected record id, and display the code and description columns from the record in the drop down list. By setting the selected record id, I can make the drop down list initialise to show the last value that the user picked (it will show the code and description, not the record id). When the user selects a different item from the drop down list, the v-model linkage automatically updates the selected record id. It does not return the whole record. Further details of how I do this are given below. The standard HTML select is giving me what I want but what it doesn't give users the ability to do a type in search which is what I was hoping to get from this component.

I have got the multiselect component to show the code and description using a custom label. However, I cannot see how you can initialise the list to show anything other than the first item, and how you can make it return the id rather than the record.

Is there a way to do this?

My current approach using HTML Select is as follows - My Vue component retrieves records from SQL with columns
Elem_Id
Elem_Code
Elem_Description

With a conventional select in the Vue template I have

<select class="form-control" :required="true"
          id="UpdateElemLevelParent"
          name="UpdateElemLevelParent"
          v-model="SelectedId"
      >
      <option v-for="Item in Items"
            v-bind:value="Item.Elem_Id"
            :key="Item.Elem_Id"
            > {{Item.Elem_Description}} {{Item.Elem_Code}}
        </option>
      </select> -->

And in data I have:

data()
  {
    return {

      SelectedId: this.$store.getters.GetLastElemSelIdByLevel(this.ParentLevelId) || 
                                                                                   this.CurrParentElemId ,
      Items: [
        {
          Elem_Description: 'Select Elements not populated',
          Elem_Code: 'NoCode' ,
          Elem_Id: -1
        }
      ],

The Vuex store uses Vue-Persist to store an array of the last selected Elem_Id for each Level. So the initialisation of SelectedId will always be the last Elem_Id that the user selected for the Level Id which is passed in to my component as a Prop.

In the created hook I have a method that does a SQL call and populates Items with the details of the Elems for the given Level. Therefore the component will always show a pull down list with the last item that the user selected as the initially selected item.

**Comment by shentao** [comment]
Duplicate.
