### ISSUE TITLE
Setting "overflow-x: auto" on table hides choices & causes weird scrolling

### ISSUE THREAD

**Issue by domplz** [shentao/vue-multiselect#1024]
### Reproduction Link
[JSFiddle](https://jsfiddle.net/c23b8h0v/14/)

### Steps to reproduce
Create a multiselect-component inside a table (td) and set the div containing the table to "overflow-x: auto" (for the table being scrollable, if it has to many columns)

### Expected behaviour
Choices of the select-box popping out of the table-div.

### Actual behaviour
Choices get cut-off causing some weird scroll-behaviour.
![2019-07-15 11_07_53-Vue-multiselect - JSFiddle and 4 more pages - Microsoft Edge](https://user-images.githubusercontent.com/46622427/61205616-d5275f80-a6f0-11e9-989f-706bff2eceb7.jpg)

Tested in Firefox, Chrome & Edge Chromium

**Comment by splatEric** [comment]
did you work out a way around this, I'm suffering from a similar problem?

**Comment by domplz** [comment]
Not really. I've added a min-height to the parent container to keep the options inside of it.

[JSFiddle](https://jsfiddle.net/Ltq04f7b/8/)

Absolutely not a good solution (also not usable for many cases), but the only thing I could do.

As there is zero response from the devs, I might have to use a different library.

**Comment by splatEric** [comment]
I found this discussion, and the latter comments seem to work nicely. Although I can't work out how to support the showing above behaviour. But it'll do ...

https://github.com/shentao/vue-multiselect/issues/618

**Comment by shentao** [comment]
This is related to the fact that the dropdown is rendered just next to the element itself. To fix it, one would have to portal the dropdown contents to some kind of absolutely positioned div outside of the overflow element. However, there is another fix to it if you use position static in between. I remember there was an article on css-tricks on this.
