### ISSUE TITLE
Prevent opening the dropdown when clicking a tag.

### ISSUE THREAD

**Issue by smyth64** [shentao/vue-multiselect#1051]
Hi
When I click a tag I want to have a modal opened instead of seeing the dropdown. I only want to see the dropdown when I click the input field (Or make it completely programmatic).

Is there a workaround to achieve this?

**Comment by shentao** [comment]
I think you would need to use the scoped slot for the tags and then add a `@mousedown.prevent` listener to open the modal. This should prevent the multiselect from opening.
