### ISSUE TITLE
Feature request: Separator

### ISSUE THREAD

**Issue by tim-kilian** [shentao/vue-multiselect#1057]
I need to add a separator to my select box. How do I do it? It could be helpful, to have some support from the library itself.

**Comment by shentao** [comment]
Could you describe it a bit better? You should be able to do quite a lot with the scoped slots that are available.

**Comment by tim-kilian** [comment]
Here is a reference for some separators I have in mind:

![image](https://user-images.githubusercontent.com/5788010/62203765-1a53be80-b38c-11e9-9c90-7f6431078810.png)

**Comment by shentao** [comment]
And how would those fit inside a multiselect? Do you want those separators inside your options list? Take a look at: https://vue-multiselect.js.org/#sub-custom-option-template
As you can see, you can replace how every option looks like with a custom template. Will this be enough?

**Comment by tim-kilian** [comment]
Yes inside my options list. Options groups are pretty much that what I was looking for thanks. But what if I just want a line that separates it. I'll play with it around first and give some feedback afterwards. Thanks for the quick reply.

**Comment by shentao** [comment]
👍
