### ISSUE TITLE
Prevent the deselection

### ISSUE THREAD

**Issue by Zettex** [shentao/vue-multiselect#1060]
It would be great if I could prevent deselect when I click on an already selected option.

New prop
```js
deselectSelectedOption: {
      type: String,
      default: true
 },
```
used in
```js
const isSelected = this.isSelected(option)

if (isSelected && deselectSelectedOption) {
     if (key !== 'Tab') this.removeElement(option)
     return
}
```

**Comment by shentao** [comment]
Sorry but there are no plans to introduce such a change. You can control which options you select or deselect by using the corresponding events instead of relying on v-model or at input event. Please take a look at the docs.

**Comment by komonjlep** [comment]
@shentao  - Could you give some insight on how allowEmpty should work? "Allows to remove all selected values. Otherwise one must be left selected." -- But when I select already selected value it sets v-model to null or undefined... isn't this contradicting the documentation?
