### ISSUE TITLE
How can I select all options?

### ISSUE THREAD

**Issue by CathyZYF** [shentao/vue-multiselect#1061]
I have tried to put all the options into selected array,but it didn't change the view(no tags show in the input,and no options selected in the dropdown),how can i fix it?

here are my codes:
```

//template
<multi-select:multiple="true" v-model="aLv2" :options="lv2Data"
      :limit="1"
      :taggable="true"
      :searchable="true"
  >
           <template slot="beforeList">
                <div class="select-button-box">
                     <div @click="selectAll(aLv2,lv2Data)" class="select-button">{{$t('fault.selectAll')}}</div>
                      <div class="middle-line"></div>
                      <div @click="deselectAll(aLv2)" class="select-button">{{$t('fault.deselectAll')}}</div>
                </div>
           </template>
  </multi-select>

//script

methods:{
    selectAll(selectedOpt,options) {
           selectedOpt = [...options];
           console.log(selectedOpt);
    }
}
```

### Expected behaviour
all the tags added into input and all the dropdown item selected
### Actual behaviour
none are be done

**Comment by CathyZYF** [comment]
problem solved.
Change the parameter to selecAll function like this:
`div @click="selectAll('Lv2')" class="select-button">{{$t('fault.selectAll')}}</div>`


then Modify the selectAll function like this:
```
selectAll(level) {
       switch (level) {
             case 'Lv2':
             this.aLv2 = [...this.lv2Data];
             break;
       }
}
```
and everything goes well  :)

**Comment by shentao** [comment]
Glad you found the solution! 😄
