### ISSUE TITLE
Impossible to handle the ESC key

### ISSUE THREAD

**Issue by francoismassart** [shentao/vue-multiselect#1068]
Hi,
I did read the documentation but I was not able to find a solution, so here is my problem...

I'd like to be able to handle a key down/press/up of the ESC key but it looks like the event does not bubble up, it might be prevented by the `@close` event.

My scenario is the following:

1. Search for a string
2. The results are live filtered and if I blur the field, I keep the current value and its filtered results.

I only want to blur and erase the current search by using the escape key.

Thank you for your help.

https://jsfiddle.net/francoismassart/nksbya92/2/

**Comment by francoismassart** [comment]
Solution I found... Binding `@keyup.esc` on the parent element in the template...

https://jsfiddle.net/francoismassart/zh4tLx69/4/

WDYT?

**Comment by shentao** [comment]
The content that you type is not treated as a value so this wouldn’t work. You have to select something, this is not a typeahead component. :(
