### ISSUE TITLE
MultiSelect VueSax

### ISSUE THREAD

**Issue by madn3z** [shentao/vue-multiselect#1076]
hello, I am trying to implement this object with vuesax, for the moment of selecting an item from a popup, the following problem appears to me.

![image](https://user-images.githubusercontent.com/19242896/64481671-fb2c2600-d1ae-11e9-9a8e-bc8cf7d04400.png)

Try adding a z-index, but still the problem persists.

Does anyone have any idea how to fix it?

Beforehand thank you very much

**Comment by shentao** [comment]
The reason for this must be that the vuesax modal and it having an `overflow: hidden` property. 
There’s a nice trick for that.
https://css-tricks.com/popping-hidden-overflow/

**Comment by eybarta** [comment]
> 

Nice trick (gotta love CSS hidden wonders), though in this case **.multiselect** is positioned, so for this to work you'd have to 'unposition' it which mispositions the arrow (that is absolutely positioned relative to .multiselect)
