### ISSUE TITLE
V-slot doesn't work

### ISSUE THREAD

**Issue by Dual-Ice** [shentao/vue-multiselect#1080]
In VueJS 2.6.0 appeared v-slot syntax ([release-link](https://github.com/vuejs/vue/releases/tag/v2.6.0), [api-link](https://vuejs.org/v2/api/#v-slot)), but I have a proplem using it with vue-multiselect.
In fiddle bellow you will find 2 multiselets, one of this with usual slot, second with v-slot.
If I using slot (usual, or template v-slot) to show the custom message - everything ok, when I want to add an event, it doesn't work
### Reproduction Link
https://jsfiddle.net/qafu9j3c/4/
### Expected behaviour
Events should work with template v-slot
### Actual behaviour
Events work only with span slots

**Comment by shentao** [comment]
You can’t set event handlers on a template tag. Move it to a span.
https://jsfiddle.net/shentao/L5syx839/

**Comment by Dual-Ice** [comment]
facepalm.. Thank's!

**Comment by shentao** [comment]
Glad to be able to help!
