### ISSUE TITLE
[Feature Request] Drag and drop tags

### ISSUE THREAD

**Issue by jllagerberg** [shentao/vue-multiselect#1083]
I would like to request a feature where the tags in the multiselect are drag and droppable, in order to change the positions.

Are there any plans for this or can anyone suggest an already working solution?

**Comment by shentao** [comment]
This could be possible with v3 given you’re ready to implement your own drag and drop and connect it with the v3 API.

**Comment by jllagerberg** [comment]
Any estimate on v3?

**Comment by jllagerberg** [comment]
> This could be possible with v3 given you’re ready to implement your own drag and drop and connect it with the v3 API.

Any estimate on v3?

**Comment by shentao** [comment]
Really hard to say. :( Could use some help from people trying to use it (might release a beta soon).

**Comment by timsayshey** [comment]
Can we open this back up so it can be worked on? Seems like an important feature to be able to sort and reorder the selected options.

**Comment by shentao** [comment]
I don’t think this is an important enough feature to be included in the core. But the v3 version already supports this indirectly. It means that you can replace the way the values/tags are displayed with a drag-n-drop functionality that you can the connect with Multiselect.
