### ISSUE TITLE
[Feature Request] Delay on Async

### ISSUE THREAD

**Issue by renanleandrof** [shentao/vue-multiselect#1084]
It would be nice if we could set a minimum delay between typing before triggering the change event.

That is a very common typeahed feature to avoid multiple useless ajax requests when autocompleting from the server.

**Comment by shentao** [comment]
Just set that delay (debounce would be best) in your `@search` handler.

**Comment by renanleandrof** [comment]
How can i set delay on @search handler, or the Debounce you mentioned?

Thanks

**Comment by ravipatel2293** [comment]
I have figured it out another way to implement the required feature. I have used setTimeout to resolve this issue.
You can find code below which i have used to get debouce effect on search change.
Hope this will help to someone.

```
asyncFind($event){
    if(typeof window.LIT !== 'undefined') {
          clearTimeout(window.LIT);
      }
      window.LIT = setTimeout(() => {
           // You can write your logic here
      }, 500);
}
```
