### ISSUE TITLE
No slot "selection" find 

### ISSUE THREAD

**Issue by bsdbc** [shentao/vue-multiselect#1086]
In multiple select exmple , a "selection" slot is used, but i did't find it in "slot" menu, and i imitate the exmple,it dose't work

**Comment by jwkicklighter** [comment]
Not sure if this is the same issue I was about to report, but the slot `selection` is not documented with the other available slots.

@shentao I'd be happy to add documentation, if you'd like someone to do so.

**Comment by shentao** [comment]
@jwkicklighter If you have a moment to do that, that would be awesome!

**Comment by jwkicklighter** [comment]
I made the changes locally, but I can't get `yarn install`/`npm install` to succeed properly.Is there a particular version of `npm`, `yarn`, or `node` being used?

**Comment by shentao** [comment]
Uh. I think this might be the result of the recent dependency updates. Might have to postpone it a bit. Please submit a PR with that change and once the dependency issue is solved, I will be able to rebuild the docs.
