### ISSUE TITLE
is there a way to use vue multiselect to populate cities from multiselect country?

### ISSUE THREAD

**Issue by rapgithub** [shentao/vue-multiselect#1089]
Let us say I have a multiselect that list all countries after I select a country I need to populate the multiselect cities with the changes... the cities multiselect is empty and needs to be filled with cities after I select the country...

my question is:

how do I populate the second multiselect cities after I select an option from multiselect country in vue?

Any sample how to achieve this ?

thanks

**Comment by thedamon** [comment]
Using v-model and an object that has cities sorted by country it should be fairly simple:

```
<multiselect v-model="country" :options="countries"/>
<multiselect v-model="city" :options="citiesByCountry[country]"/>
```

You might need to do some data transformation depending on how your data is stored (strings vs objects of countries etc), but this is more a javascript/Vue question than something specific to the multiselect component itself.

**Comment by shentao** [comment]
That is a perfect answer!
