### ISSUE TITLE
Custom html in placeholder

### ISSUE THREAD

**Issue by Venegrad** [shentao/vue-multiselect#1126]
Im trying insert span in placeholder, for color change. 

```
computed: {
      customPlaceholder () {
        let numLength = this.options.length;
        return this.placeholder + "<span>"+numLength+"</span>"
      }
}
```

But placeholder returns only string, ow to fix that?

**Comment by worldofprasanna** [comment]
@Venegrad Did you try using the placeholder slot ? Like this,

`  <template slot="placeholder">
      <span>testing span</span>
    </template>`

Also note that it will not display placeholder when dropdown is open and searchable is true
