### ISSUE TITLE
When click on close at selected ithem, that not closed, that repeats

### ISSUE THREAD

**Issue by OussamaAlouat** [shentao/vue-multiselect#1164]
Hello, I am working on a project with vue and vuex. And my problem is when i try to delete a selected item, it is repeated instead of being deleted. So, when i click on close icon, the item have been repeted instead of been removed.

NOTE: You need to have more than one element selected to reoproduce this issue

npm version: 6.4.1
node version: 10.14.2
vue version: 2.6.10

### Reproduction Link
https://jsfiddle.net/Sama_Dev/8tkab76q/

### Expected behaviour
The expected behaviour is remove the item, but now it repeats that item instead of remove them.
### Actual behaviour
The actual behaviour is that the item is repeated when i click on close icon.

**Comment by JerryKusenberger** [comment]
Add track-by="value"

```
<div id="app">
  <multiselect 
      v-model="selected"
      :options="autonomousCommunities"
      :multiple="true"
      :close-on-select="true"
      label="text"
     track-by="value"
  >
  </multiselect>
  <pre class="language-json"><code>{{ value  }}</code></pre>
</div>
```

**Comment by OussamaAlouat** [comment]
Thanks, I added track-by="value" and works well.
Thanks

**Comment by jaswinder97** [comment]
Now first item is not removable and it repeats the same on closing it
