### ISSUE TITLE
Issue with checkbox in options

### ISSUE THREAD

**Issue by kapilsharma** [shentao/vue-multiselect#1167]
## Description

When we have checkbox in options, and apply filter, checkbox behaviour is unexpected.

### Reproduction Link

Following JS fiddle is taken from issue #574 but is reproduction the problem.

https://jsfiddle.net/3numjz68/

### Steps to reproduce

In above JS Fiddle

- Open dropdown
    - We can see 3 options
- Filter options, Press `d` so than only last option is available.
- Click on checkbox (Not label)
- Result
    - Validate got bold and shown as selected.
    - However, if we open dropdown again, checkbox of 'Vue.js' is selected.
    - Assumption, when we filter, checkbox gets selected from original location, not from filtered result.

### Expected behaviour

In above case, Checkbox against Vuelidate must be checked.

### Actual behaviour

Checkbox against 'Vue' is selected.

**Comment by kapilsharma** [comment]
This issue could be marked as invalid. Issue is not with the `vue-multiselect` library but not correctly using vue in above fiddle.

## Solution

Just for future visitors, I've updated fiddle with working solution [https://jsfiddle.net/rn6x32Lb/2/]()

## What was the problem

Problem in fiddle given in this issue and issue #574 is:

- When Vue JS update (re-render) DOM, it try to reuse as much as possible elements.
- Here, Vue was re-rendering the label, but not the checkbox as VueJS has no way to know checkbox is tied with label.
    - As a result, even though option labels are updated, checkbox were now. (Checkbox were not pointing to correct label)
- To fix it, we need to tell Vue that checkbox are tied with label. This can be achieved through [:key](https://michaelnthiessen.com/force-re-render/)
- Updated fiddle shows how to do it. We basically added `:key="scope.option.library"` in `input` tag.

**Comment by larrykkk** [comment]
> https://jsfiddle.net/rn6x32Lb/2/

https://jsfiddle.net/rn6x32Lb
