### ISSUE TITLE
How to disable tags/pills creation when multiple selection is allowed ?

### ISSUE THREAD

**Issue by BorisAng** [shentao/vue-multiselect#1173]
Heya, is it possible to allow multiple selection without creating any pills/tags when options are selected. I know the default behavior is to create the pills with `:multiple="true"` but we don't actually want this functionality.

**Comment by JerryKusenberger** [comment]
This does appear to be possible. 

Check the 'Multiple Select' example in the documentation.

https://vue-multiselect.js.org/#sub-multiple-select

**Comment by BorisAng** [comment]
@JerryKusenberger Yep, ended up using this. Thank you

**Comment by jebarjonet** [comment]
The answer is to remove `taggable`, which does not display tags (this comes from `multiple="true"`) but directly allows tags creation
