### ISSUE TITLE
autocomplete 'nope' works less than 'off', can we randomize name attr?

### ISSUE THREAD

**Issue by gregg-cbs** [shentao/vue-multiselect#1182]
Hey,

So autocomplete 'nope' looks like it is less effective than 'off'. And judging by browsers, 'off' is more supported.

But seeing as 'off' or 'nope' isn't respected by browsers completely, a work around is to randomize the name property.

So perhaps for the name property you can accept the name prop and add a math.random to it? The name prop isn't being used for anything else so this seems acceptable.

It is unlikely anyone will want to get the input element by name, and if they do want to get it they can always use get by id instead.

**Comment by sontd-0882** [comment]
Any update?

**Comment by gregg-cbs** [comment]
@sontd-0882 
It looks like Google has taken a hard stand on autocomplete and it has stated that Chrome it will override/ignore developers settings and replace them for users settings.

So now in Chrome as a user in settings you can specify if you want autocomplete on or off.

My advice is to not fight it, auto complete will be on and it's a browser thing now. Users will have to get used to this.

**Screenshots of Chromes settings:**
<img width="692" alt="Screenshot 2020-02-10 at 09 29 37" src="https://user-images.githubusercontent.com/57114335/74137542-ec2b2300-4be7-11ea-86b5-15dd2c0adb07.png">
<img width="690" alt="Screenshot 2020-02-10 at 09 29 29" src="https://user-images.githubusercontent.com/57114335/74137546-ecc3b980-4be7-11ea-9db2-790413e53482.png">
<img width="690" alt="Screenshot 2020-02-10 at 09 29 18" src="https://user-images.githubusercontent.com/57114335/74137547-edf4e680-4be7-11ea-8b59-ba2fabc9f61e.png">

**Comment by alc32** [comment]
Any update?
