### ISSUE TITLE
Lazy mode in SearchChange

### ISSUE THREAD

**Issue by alexsonnay** [shentao/vue-multiselect#1194]
Is there a way to add "laziness" on @search-change ?

With Async Select an ajax request is made on every new key input. I'd like to have it when user stops writing. Is it possible ?

Thanks !

**Comment by viT-1** [comment]
Use debounce e.g. https://github.com/kaorun343/vue-property-decorator/pull/134#issuecomment-423424397

**Comment by alexsonnay** [comment]
Any idea how to implement it with vue-multiselect ? There's no doc.

**Comment by alexsonnay** [comment]
Answer with Lodash : https://github.com/shentao/vue-multiselect/issues/955
