### ISSUE TITLE
Add button action in slots

### ISSUE THREAD

**Issue by lainesonny** [shentao/vue-multiselect#1224]
Hello,
I am using your plugin which works well however I would need your help.

I would like to add a "Delete" button in an "option" slot.
Unfortunately, when I click the button, it selects the item.
I would only need to trigger my function without selecting the item from the list.
It's possible ?

Exemple JSFiddle : 
https://jsfiddle.net/Sonny_L/hy132rLs/4/

**Comment by andykulakov** [comment]
Hi,
You should use `.stop` modifier to stop propagation on the 'delete' button click event. The template looks like this:
`<i class="item--delete" @click.stop="deleteItem(option.id)">X</i>`
This would prevent the click event from bubbling up.

**Comment by akki-jat** [comment]
@lainesonny Please reopen the issue if you are still facing the same problem. Thanks @andykulakov for jumping in with solution.
