### ISSUE TITLE
Unable to add tag and keep selected as non listed option on tab or blur event

### ISSUE THREAD

**Issue by aherrao** [shentao/vue-multiselect#1229]
### Steps to reproduce
1. Create an async type of multi-select
2. Type search name out of the options
3. Press tab to leave the field

### Expected behavior
1.  Input search term should persist as it is
2. The non-matching text should be added in the tag
3. Tab button should add tag as well 

### Actual behavior
1. search team get clear
2. for adding tag need to enter

**Comment by OleksandrSymonov** [comment]
Or could you add @blur event?

**Comment by swan03** [comment]
Nope even on blur it's make it empty

**Comment by OleksandrSymonov** [comment]
I meant, Will be nice to add @blur to library.

**Comment by akki-jat** [comment]
@aherrao Please provide reproduction link
