### ISSUE TITLE
Show selected options by number

### ISSUE THREAD

**Issue by osmanustalar** [shentao/vue-multiselect#1234]
https://vue-multiselect.js.org/#sub-multiple-select

I want to do this. "1 options selected"
![screen](https://user-images.githubusercontent.com/60302329/78911169-a0cdad80-7a8e-11ea-932c-ed89f70fdce7.PNG)

I did not want with these codes.
https://jsfiddle.net/enqhkxfu/1/

Can you help me?
Thanks.

**Comment by leeniu** [comment]
Hey @osmanustalar, in the fiddle you provided you use the version 2.1.0 of the project. Here is a fiddle with version 2.1.6 used. It should work as intended:

https://jsfiddle.net/leeniu/h470mkbr/

So please update the package to the latest version.
