### ISSUE TITLE
White empty rows with initialized options.

### ISSUE THREAD

**Issue by Edmaniak** [shentao/vue-multiselect#1236]
Hi,
I've just set up the library and ended up with an issue. I'm filling the options prop with an async backend call that results with eg. ['A', 'B']. The multiselect component renders with the correct amount of rows but they are empty. It's not a styling issue since the span tag itself doesn't contain any text. Does anybody have any idea what's going on? 
![d](https://user-images.githubusercontent.com/23060360/79007489-8dd4df00-7b5b-11ea-8b9a-2bda7b69bfb5.jpg)

**Comment by Zyberg** [comment]
Check out `label` property in the docs :)

Basically you are not telling the component how you want the response to be displayed.
If you want to construct some kind of a custom label with html inside, you are better off using option scope for this:

```
<template #option="option">
   <h5>{{ option.title }}</h5>
   <code>{{ option.code }}</code>
</template>
```

**Comment by akki-jat** [comment]
@Edmaniak Please look at @Zyberg comment. If you are still facing issue then open issue with more details.
