### ISSUE TITLE
group-label with Custom option template

### ISSUE THREAD

**Issue by frederic117** [shentao/vue-multiselect#1238]
Hello :)
Thanks a lot for this components !!

I don't know how to make the group-label appears with Custom option template...

Please could you help me ?
THanks a lot

### Reproduction Link
https://jsfiddle.net/nxgeo04r/

**Comment by anthonywebster** [comment]
https://github.com/shentao/vue-multiselect/issues/761#issuecomment-399146476

**Comment by frederic117** [comment]
thanks :)
