### ISSUE TITLE
Add custom option if not in list

### ISSUE THREAD

**Issue by tiagosiebler** [shentao/vue-multiselect#1242]
In the single-select with search example, I'd like the ability to add a new item to the list if it's not found. Example:
- Go to here: https://vue-multiselect.js.org/#sub-select-with-search
- Type one not in list, e.g "Node.js"
- Hit enter to submit

I guess I would need to use an event to push the new search result into the options array? Is there a single event I can use when I hit enter?

I see "SearchChange":
https://vue-multiselect.js.org/#sub-events

But that would match each query, which could result in a very large array very quickly.

I also see "Close" but it doesn't carry last search value. Should I use searchChange to store last search, and get last search value on close? What would be the light approach to this?

**Comment by Zyberg** [comment]
You would have to use @search-change to save the query and then @keyup event for enter to save the option. I've included a fiddle to show how this could be implemented:

https://jsfiddle.net/es8p2nrg/

**Comment by tiagosiebler** [comment]
> You would have to use @search-change to save the query and then @Keyup event for enter to save the option. I've included a fiddle to show how this could be implemented:
> 
> https://jsfiddle.net/es8p2nrg/

Thanks, I'll play with that - appreciate the fiddle. Do you know if it's possible to override the "no elements found" to something like "hit enter to use this new element"?

**Comment by leeniu** [comment]
Hey @tiagosiebler. I am not sure If I understood you correctly, but you can actually replace the content that shows up when nothing is found by utilizing the slot. In your template you can do something like this:
```
        <multiselect ...>
            <template v-slot:noResult>
               <!-- Your custom html content -->
            </template>
        </multiselect>
```
Everything within <template> will replace what you currently see when "nothing is found".

I hope this helps you.

**Comment by tiagosiebler** [comment]
> Hey @tiagosiebler. I am not sure If I understood you correctly, but you can actually replace the content that shows up when nothing is found by utilizing the slot. In your template you can do something like this:
> 
> ```
>         <multiselect ...>
>             <template v-slot:noResult>
>                
>             </template>
>         </multiselect>
> ```
> 
> Everything within will replace what you currently see when "nothing is found".
> 
> I hope this helps you.

This is exactly what I'm looking for - thank you!
