### ISSUE TITLE
inputmode

### ISSUE THREAD

**Issue by SnoxiK** [shentao/vue-multiselect#1245]
hello, i wish i could put the input field with "inputmode =" numeric "" how can i do that please?

Other than doing that in jquery I don't see how. Basically I would like the input to remain an input text but on mobile I would like the numeric keyboard to appear first!

I did like this at first I look for the class then I will look for the input and I add to it what I want!
`setTimeout(function(){
                    $('.inputproduct :input').attr("inputmode", "numeric");
                }, 500)`
Thanks, have a good day.

**Comment by shentao** [comment]
Hey, sorry this is not possible in v2. Perfectly possible with v3, once it is released.
