### ISSUE TITLE
Make "index" available in "options"-slot within the list

### ISSUE THREAD

**Issue by leeniu** [shentao/vue-multiselect#1248]
Hey @shentao and team!

First up, thanks for this package. I like the usage of slots here! It makes it quite easy to modify the behavior the way you wish to.

I'd like to request having access to the index within the slot named "option". 

You actually get the index in the surrounding `<li>` for loop, so I guess it should be a simple change from

```
<slot name="option" :option="option" :search="search">
  <span>{{ getOptionLabel(option) }}</span>
</slot>
```

to

```
<slot name="option" :option="option" :search="search"  :index="index">
  <span>{{ getOptionLabel(option) }}</span>
</slot>
```
Is there an argument against it? 

I'd offer to create a PR for that.

Cheers and thanks again.

**Comment by shentao** [comment]
Hey! That sounds like a good idea. I don’t think there is anything preventing that change. Feel free to open a PR. Though be warned, it might take a few weeks before I will be able to release it... Lately, I’m a bit behind on this project.

**Comment by leeniu** [comment]
@shentao I am glad that you like the idea.

I'd like to work on the project, but in relation to this issue: https://github.com/shentao/vue-multiselect/issues/1241 and some linting errors during `npm run dev`, I can't get the dev environment to work properly.

I'll try to resolve the issues during the weekend, if there is no quick fix on your part. Hopefully I can commit something useful :).

Nonetheless, thank you again for taking the time.

**Comment by shentao** [comment]
That would be great! The issues most likely come from automatic updating the dependencies (had to disable the dependabot as it turns out, even minor updates can cause breaking changes...).

**Comment by leeniu** [comment]
Hey again @shentao. I am trying to fix the dev env with this PR https://github.com/shentao/vue-multiselect/pull/1251. If this looks good to you, I would create another PR for this topic on the basis of that commit :).

**Comment by shentao** [comment]
Reviewed – looks great! Really appreciate the help!

**Comment by leeniu** [comment]
I am happy to be of use here :). I'd gladly support you further on this project as much as I can. Another PR for this ticket here will follow soon.

**Comment by shentao** [comment]
This sounds like a spark of hope for the project! 🤞 Thank you! Happy to have someone on board to help with the maintenance!
