### ISSUE TITLE
Disable tags if multiple

### ISSUE THREAD

**Issue by jakubm95** [shentao/vue-multiselect#1249]
Hello @shentao 
How disable tags if multiple is true?

:taggable="false" - dont work ;/

The code is copied from the documentation and does not work as in the example
https://vue-multiselect.js.org/#sub-multiple-select

Codepen:
https://codepen.io/jakub40/pen/KKdZyLa

![image](https://user-images.githubusercontent.com/18602411/81059517-d53b5a80-8ed0-11ea-82a4-503846950bc3.png)

**Comment by shentao** [comment]
Hey!

Use something like this:
```html
<template 
  slot="selection" 
  slot-scope="{ values, search, isOpen }"
>
  <span class="multiselect__single" v-show="values.length && !isOpen">
    {{ values.length }} options selected
  </span>
</template>
```

If the `<template>` tag ends up empty, the slot’s content won’t be replaced. The above code will help as `v-show` will just hide the element but not remove it from the DOM.

**Comment by michaelschofield** [comment]
So I just want to echo @shentao's statement here

> The code is copied from the documentation and does not work as in the example https://vue-multiselect.js.org/#sub-multiple-select

Where I am encountering a similar problem. Basically, the most dead simple implementation of multiple select (`<multiselect :multiple="true" ... />`) is rendering tags, but the documentation suggests we shouldn't see tags unless we add `:taggable="true"`. 

So if I want to have a multiple select _without_ tags, I can't - as per the docs. This is as of version 2.1.6.

**Comment by shentao** [comment]
Hey! I think I need to clear one possible misunderstanding. By `tagging` the docs mean being able to add new properties by typing text that does not match any of the existing options. For example when you need to add tags to something. Some of the tags will already exist, others not and will be created once you type it and press enter.

Here’s an example from the docs. `hello` is not an existing option.
![Screen Shot 2020-05-11 at 22 34 28](https://user-images.githubusercontent.com/3737591/81609133-9c6f1a00-93d7-11ea-910b-cf8b4c779ce2.png)

But when it comes to showing multiple results the `pills` that you can see (which might also look like tags) are the default way to display those results. 
The example https://vue-multiselect.js.org/#sub-multiple-select is a special case where additional template was passed into the `selection` slot. This replaces the `pills/tags` with whatever template you pass there. Here it was a simple text:
```html
<template
      slot="selection"
      slot-scope="{ values, search, isOpen }"
>
      <span class="multiselect__single" v-if="values.length && !isOpen">
        {{ values.length }} options selected
     </span>
</template>
```

I hope this clears it!

**Comment by jaytdev** [comment]
@michaelschofield If you leave out the `!isOpen`, this will work like in the example: you won't see the tags when the select is open. Took me a while to figure that out.

**Comment by gregoryfm** [comment]
Is it possible to have tag layout, but for single selection?
