### ISSUE TITLE
Can't use @tag for Asp .Net Solutions

### ISSUE THREAD

**Issue by villar35738** [shentao/vue-multiselect#1262]
Hello, I followed the instructions to install via CDN but it gives the following error on HTML:

CS0103: The name 'tag' does not exist in the current context

My html:

`<multiselect v-model="value" tag-placeholder="Add this as new tag" placeholder="Search or add a tag" label="name" track-by="code" :options="options" :multiple="true" :taggable="true" @tag="addTag"></multiselect>`

My script:

`    methods: {
        addTag(newTag) {
            const tag = {
                name: newTag,
                code: newTag.substring(0, 2) + Math.floor((Math.random() * 10000000))
            }
            this.options.push(tag)
            this.value.push(tag)
        }
    }`

Can Anyone helps me?

**Comment by shentao** [comment]
The code you showed looks fine. Could you provide a reproduction? Were you able to reproduce that in a JSFiddle?

**Comment by villar35738** [comment]
> The code you showed looks fine. Could you provide a reproduction? Were you able to reproduce that in a JSFiddle?

See it here:

[](https://jsfiddle.net/p8rc9Lg7/)

But I think that the problem is that Asp .Net doesn't recognize @tag event. Is there another way to call this event?

**Comment by shentao** [comment]
You could try `v-on="{ tag: addTag }"`. Or `v-on:tag="addTag"`. But generally `@tag` should be compiled by the Vue template compiler. How does your setup looks like?

**Comment by villar35738** [comment]
> You could try `v-on="{ tag: addTag }"`. Or `v-on:tag="addTag"`. But generally `@tag` should be compiled by the Vue template compiler. How does your setup looks like?

It works, thanks!
