### ISSUE TITLE
How to select key in Vue multiselect and preselect option? Vue

### ISSUE THREAD

**Issue by AleksandarMiha** [shentao/vue-multiselect#1264]
### Actual behaviour

Check my all question on stackoverflow and if you can send me

https://stackoverflow.com/questions/61762464/how-to-select-key-in-vue-multiselect-and-preselect-option-vue

**Comment by AleksandarMiha** [comment]
@shentao @jbruni @phlegx @antony @arran4

**Comment by antony** [comment]
@AleksandarMiha please don't do this. It's incredibly annoying.

**Comment by AleksandarMiha** [comment]
Ok no problem just hint me how to solve my problem

**Comment by arran4** [comment]
https://stackoverflow.com/

**Comment by AleksandarMiha** [comment]
????????
