### ISSUE TITLE
Using scrollbar clears search text on IE11

### ISSUE THREAD

**Issue by saskaak** [shentao/vue-multiselect#1268]
Reproduceable on at least this example: https://vue-multiselect.js.org/#sub-custom-option-template 

### Steps to reproduce
0. Use IE11
1. Write "m" to the search box to filter the results to 3 (of 4) items.
2. Click/drag the scrollbar on the right of the results list. Don't use mouse wheel / trackpad, this only reproduces when you actually click the scrollbar.

### Expected behaviour
The search text is 'm' and the list stays filtered.

### Actual behaviour
The search text is cleared and the list is no longer filtered.

**Comment by akki-jat** [comment]
@saskaak IE11 reached the end of life. We don't have any plan to support it further.
