### ISSUE TITLE
Limited customization issue

### ISSUE THREAD

**Issue by cizza** [shentao/vue-multiselect#1272]
Hi Shentao,

thank you for the plugin. I've got an issue with the slots. It's not a bug. I find the slots to be not that useful as I would like them to be. My issue is with styling. I would like to reskin the plugin completely but I can't. The structure of the plugin is too tight. And whatever I add as a markup won't be picked up. E.g.

 ```
<multiselect
        v-model="selectedTag"
        :options="blockTags"
        :close-on-select="true"
        :show-labels="false"
      >
        <div class="flex items-center">
          <template slot="singleLabel" slot-scope="props">
            <span class="option__title">{{ props.option.title }}</span>
          </template>

          <template slot="caret" slot-scope="toggle">
            <span class="p-2 text-red-500" @click="toggle">
              <font-awesome-icon :icon="['fas', 'caret-right']" />
            </span>
          </template>
        </div>

        <div class="demonstration">
          <template slot="option" slot-scope="props">
            <div class="option__desc">
              <span class="option__title">{{ props.option }}</span>
            </div>
          </template>
        </div>
      </multiselect>
```
Cuz each slot is a named slot and that limits the customization quite a lot. The solution for this would be make the component a renderless component. I know it would be probably quite a lot of work and I'm not going to be moaning if it won't happen. But on the other hand it would be great way forward with this. 

Thanks man!

**Comment by Zyberg** [comment]
You can always ”reskin” a component by overriding css from within css. Personally I prefer to do that instead of using more style markup in the template part of the file.
Chrome dev tools -> inspect dom and you may change whatever you want :)

**Comment by akki-jat** [comment]
@cizza I think what you are looking for is selection slot. Here is the example for the same https://vue-multiselect.js.org/#sub-multiple-select
