### ISSUE TITLE
Glitch in the select box

### ISSUE THREAD

**Issue by ivanradojevic-web-dev** [shentao/vue-multiselect#1273]
![zthzt](https://user-images.githubusercontent.com/59580150/82302202-8eae2b80-99b9-11ea-882b-bbb1d655bbdf.JPG)

I have some glitch in the select box?!

**Comment by Zyberg** [comment]
You are overriding the default style somehow. Check out what is happening via chrome developer tools.

**Comment by akki-jat** [comment]
@ivanradojevic-web-dev Please reopen issue with reproduction link.
