### ISSUE TITLE
Bug: Cannot setAttribute if no search

### ISSUE THREAD

**Issue by chavlji** [shentao/vue-multiselect#1277]
This commit seems to produce some **unhandled exception**:
https://github.com/shentao/vue-multiselect/commit/58e7634afbc42dbaf9f82da56185d73158fac745#diff-a47ed716b33c7bfe4e779fcd440c7b38R39

If you use it with the following params:
`<vue-multiselect :searchable='false' v-model='value' :options='options'/>`

...it will crash when user will try to mouseEnter any dropdown item:
![Screenshot 2020-05-27 at 12 31 21](https://user-images.githubusercontent.com/5729421/83009955-d109e500-a017-11ea-9708-496e80ffb32e.jpg)

Problem is that if it is not searchable, then `<input v-if="searchable" ref="search">` doesn't exist...

**Comment by shentao** [comment]
Fixed
