### ISSUE TITLE
change multiselect drop down menu to drop up menu

### ISSUE THREAD

**Issue by bnping** [shentao/vue-multiselect#1278]
Hi, 
 Can we change the position of selection menu to up, the current is drop down menu. Can we change it to drop up menu ?.
I need like this;
![image](https://user-images.githubusercontent.com/63243110/83073377-a304bf00-a070-11ea-85a2-ab7a44dd1367.png)
thanks

**Comment by Zyberg** [comment]
Hello, please check out documentation! You need to add `openDirection='top'` to your multiselect component.
https://vue-multiselect.js.org/#sub-props

**Comment by akash14204** [comment]
<multiselect v-model="selectedCountries" id="ajax" label="name" track-by="code" placeholder="Type to search" open-direction="top" :options="countries" :multiple="true" :searchable="true" :loading="isLoading" :internal-search="false" :clear-on-select="false" :close-on-select="false" :options-limit="300" :limit="3" :limit-text="limitText" :max-height="600" :show-no-results="false" :hide-selected="true" @search-change="asyncFind">


but it always show..dropdown below ... please help !!!
