### ISSUE TITLE
Suggestion: Don't delete query on window switch

### ISSUE THREAD

**Issue by Tobi406** [shentao/vue-multiselect#1293]
One of our users reported (lucko/LuckPermsWeb#284) that the query is getting reset when switching to a different tab and back, this not just conflicts with the rest of our input files but also is not convenient if using much text.
Is this expected?

### Reproduction Link
- https://jsfiddle.net/25zcskfe/5/
- Fiddle is taken from the project home page: https://vue-multiselect.js.org/#sub-select-with-search

### Steps to reproduce
- Enter anything
- Switch to different browser tab
- Switch back to tab with multiselect

### Expected behaviour
Query is not cleared and you can continue typing your search query

### Actual behaviour
Query is cleared

**Comment by akki-jat** [comment]
@Tobi406 Please look the preserveSearch prop (https://vue-multiselect.js.org/#sub-props)
