### ISSUE TITLE
ag-grid

### ISSUE THREAD

**Issue by qxygene** [shentao/vue-multiselect#1295]
Not working with ag-grid. Drop down is hidden under row. Tried z-index no luck.

**Comment by glentsch** [comment]
@qxygene You should add isPopup method to your cellEditor vue component.  In the docs: https://www.ag-grid.com/javascript-grid-cell-editing/#in-cell - you can see that the content will be constrained. If you use a popup, you can display more content, such as in the. example of https://www.ag-grid.com/javascript-grid-cell-editor/#example-cell-editing-using-vuejs-components

**Comment by csicky** [comment]
@qxygene the problem is that ag grid has the rows with transform translate. I resolved this by creating a custom cell and opening the multiselect inside a portal vue component. That way the multiselect flies above the grid and is not constrained inside it.

**Comment by akki-jat** [comment]
@qxygene If this issue still persists then open the new issue with more details.
