### ISSUE TITLE
Is there a way to insert this tag on the right of select option?

### ISSUE THREAD

**Issue by villar35738** [shentao/vue-multiselect#1297]
I need to insert a "tag" on the right of select option, like on [https://vue-multiselect.js.org/](https://vue-multiselect.js.org/) initial page.

Can anyone helps me?

Thanks!

![image](https://user-images.githubusercontent.com/36749385/86418701-60ee1f00-bca7-11ea-8386-dd04a5b84324.png)

**Comment by akki-jat** [comment]
@villar35738 It's doable with option slot.

Please look at the documentation.
https://vue-multiselect.js.org/#sub-custom-option-template
https://vue-multiselect.js.org/#sub-slots

You can also directly look at the code of documentation here - https://github.com/shentao/vue-multiselect/blob/master/documentation/MultiselectExample.vue
