### ISSUE TITLE
New release to resolve TypeError: Cannot read property 'focus' of undefined

### ISSUE THREAD

**Issue by rnunezherrer** [shentao/vue-multiselect#1303]
fix #966

Reproduction Link
https://jsfiddle.net/1e97k8pf/

Steps to reproduce
click gotobar
open the select dropdown
click browser back button
errors in console

Still there is not release with the problem solved

As mentioned above, this is still a problem with the latest release @p-adams and it would be appropriate to reopen the ticket until it gets resolved. Are there any blockers for getting a new release out with the relevant changes?

_Originally posted by @Etheryte in https://github.com/shentao/vue-multiselect/issues/966#issuecomment-624677348_

**Comment by rnunezherrer** [comment]
Some news?

**Comment by akki-jat** [comment]
Will be fixed with 2.1.7 released.
