### ISSUE TITLE
Can't disable taggable option

### ISSUE THREAD

**Issue by sergeyzlobin** [shentao/vue-multiselect#1310]
### Reproduction Link
https://jsfiddle.net/oaue3y2r/

### Steps to reproduce
Set taggable option to "false"

### Expected behaviour
The documentation states that taggable option default value is false, and i expect that they will dispaly by setting taggable option to true. 
 
### Actual behaviour
The documentation states that taggable option default value is false, but when i initalise vue multiselct without this option tags is apear. I can't disable tags appearance by setting taggable option to false.

**Comment by jhosein** [comment]
Having the same issue here. I've been banging my head against a wall for a week trying to figure this out.

**Comment by michaelschofield** [comment]
Did anyone figure this out?

**Comment by Shaninjah** [comment]
same here

**Comment by akki-jat** [comment]
@sergeyzlobin taggable prop is not for tag appearance. It is for allow user to create their own tags if not available in option.

If you looking for changing appearance of selected tags than look into https://github.com/shentao/vue-multiselect/issues/1343
