### ISSUE TITLE
Searching from a virtual keyboard

### ISSUE THREAD

**Issue by marioene** [shentao/vue-multiselect#1318]
First, it is a great package!

I have a little problem:

How can I change search text (also visual in my interface) from a virtual keyboard ?
I am using [https://virtual-keyboard.js.org/vuejs/](url)

I couldn't find a reference in your docs for the search text to be manipulated from javascript or vue methods.

I succeeded to search in background (in Laravel 7.x) with array values returning for v-model attached to vue-multiselect, but I also want that the end user to view the text searched with virtual  keyboard inside the vue-multiselect search area.

Any help would be very welcome!

**Comment by reenekt** [comment]
Hi, here's example solves your problem https://jsfiddle.net/o3srp2cb/  
Search input uses `search` variable from component's `data()` - see [this](https://github.com/shentao/vue-multiselect/blob/ac46a71a38d9d2b01df560091992d38d712e857c/src/Multiselect.vue#L57) and [this](https://github.com/shentao/vue-multiselect/blob/ac46a71a38d9d2b01df560091992d38d712e857c/src/multiselectMixin.js#L67), so you need to change value of this variable, in example above used `$refs` to change `search` (and also used `activate()`/`deactivate()` to toggle multiselect's state)

**Comment by akki-jat** [comment]
@marioene Let us know if you still have any query, Closing it for now.
