### ISSUE TITLE
can we add "activate" method in docs?

### ISSUE THREAD

**Issue by ishpartko** [shentao/vue-multiselect#1320]
Hi there,

Can we add "activate" method in docs?

it's would be helpful to open select programmatically. I can't found any describe of this method.

Example of usage: 
```
...
<Multiselect ref="multiselect"/>
...
this.$refs.multiselect.activate()
this.$refs.multiselect.deactivate()
...

**Comment by eybarta** [comment]
This can be done  >> 
this.$refs.multiselect.toggle()

**Comment by akki-jat** [comment]
@ishpartko Done via https://github.com/shentao/vue-multiselect/pull/1609
