### ISSUE TITLE
Uncaught (in promise) TypeError: selfHook.call is not a function

### ISSUE THREAD

**Issue by nafeeur10** [shentao/vue-multiselect#1321]
I have followed the documentation. But facing this error. I am trying to add this in Modal of Bootstrap. 

Image of the Error in Console of Browser: https://ibb.co/nLbB34v

Now, what can I do?

**Comment by jonny7** [comment]
I'm seeing this too in a TypeScript Vue 3.0 project

**Comment by Pezhvak** [comment]
I'm facing the same issue, fresh installation with Vue 3.0

**Comment by alexkobrin** [comment]
Me too  facing the same issue, Vue 3.0.5,

**Comment by MartinKravec** [comment]
Looks like no Vue 3 support. Just migrated whole vue-multiselect instances to another package.

**Comment by OliverGrimsley** [comment]
@MartinKravec - I need to do the same.  Any tips you could provide?  I have a very simple use case in my forms, but still worried about the migration because I have a lot of components that use this ...

**Comment by MartinKravec** [comment]
> @MartinKravec - I need to do the same. Any tips you could provide? I have a very simple use case in my forms, but still worried about the migration because I have a lot of components that use this ...

Well.. you have to know that this alternative library is not 1:1 with original one. There are some missing things, that I mentioned here https://github.com/vueform/multiselect/issues/30
But the best thing is, that they have very very similar API, so that it's easy to migrate.

**Comment by mattelen** [comment]
If you are still using the vue-mulitselect, you can use the `next` release that is built for the new version of Vue. I'll close this issue as using the multiselect V2 with Vue 3 isn't compatible.
