### ISSUE TITLE
css styles are not added when using the component

### ISSUE THREAD

**Issue by maxosp** [shentao/vue-multiselect#1325]
When I import the component "import Multiselect from 'vie-multiselect' it works, but the styles are not imported. But if you make the import explicitly" import Multiselect from 'vie-multiselect / src / Multiselect', then everything works together with styles. What is the problem? And yes, I have included styles in <style src = "vue-multiselect / dist / vue-multiselect.min.css"> </style>

**Comment by aelgn** [comment]
I have a similar problem... Using the import:
`import Multiselect from 'vue-multiselect';`
No css is included in local dev mode, it does however work perfectly in prod build.

Changing the import to:
`import Multiselect from 'vue-multiselect/src/Multiselect.vue';`
Makes the css work with local dev (vue-cli-service serve)
