### ISSUE TITLE
Using scroll bar in IE11 

### ISSUE THREAD

**Issue by JasonCubic** [shentao/vue-multiselect#134]
In IE11 if you try to use the scrollbar it works if you have no items selected.  If you have an item selected the list collapses down to only the item that is selected.  This behavior does not happen in chrome though.

I created a project so you can see this behavior happening.  I tried to make the project as simple as possible and show the error I'm seeing in my project.
https://github.com/JasonCubic/vue_multiselect_bug

Thank You,

**Comment by shentao** [comment]
Thanks! Will look into it during the weekend. I honestly hate IE bugs. 😢
