### ISSUE TITLE
MultiSelect without Pills (like example)

### ISSUE THREAD

**Issue by recoiladam** [shentao/vue-multiselect#1343]
Just to preface, I have read the docs as well as other issues including those that are closed. I using version `2.1.6` and I am getting pills when using `:multiselect="true"` and using the exact same code as the example in the docs. I would like this to work the exact same way where when an option is selected it's highlighed grey and says `Selected` on the far right and no pills are created at all, not even when open. What I am getting is when the user selects options, the pills are created and shown when open and when closed, I get what's in the selection slot. I am expecting this to work exactly like the example where I do not see pills at all, open or closed.

```
<multiselect v-model="field.contacts" :options="contacts" :multiple="true" :close-on-select="false" :clear-on-select="false" :preserve-search="true" :taggable="false" :hide-selected="false" :showLabels="false" placeholder="Select Contacts" label="fullName" track-by="id" :preselect-first="false">
  <template slot="selection" slot-scope="{ values, search, isOpen }"><span class="multiselect__single" v-if="values.length && !isOpen">{{ values.length }} Contacts Selected</span></template>
</multiselect>
```

if I reopen `isOpen` then I get errors all over the place. Here's the code and the error:

**Code**

```
<multiselect v-model="field.contacts" :options="contacts" :multiple="true" :close-on-select="false" :clear-on-select="false" :preserve-search="true" :taggable="false" :hide-selected="false" :showLabels="false" placeholder="Select Contacts" label="fullName" track-by="id" :preselect-first="false">
  <template slot="selection" slot-scope="{ values, search }"><span class="multiselect__single" v-if="values.length">{{ values.length }} Contacts Selected</span></template>
</multiselect>
```

**Error**

```
Failed to compile.

./src/app/fields/components/create.vue
Module Error (from ./node_modules/eslint-loader/index.js):

error  'search' is defined but never used  vue/no-unused-vars
```

Here's a fiddle of what I am seeing. The pills are not in the template so I am not sure what is going on.

https://jsfiddle.net/rmc74gtd/

This is the example I am trying to mirror: https://vue-multiselect.js.org/#sub-multiple-select

**Comment by reenekt** [comment]
The jsfiddle above used vue-multiselect@2.1.0, here is working example -> https://jsfiddle.net/rm83pdaw/1/ (works the same as the example in the docs).  
About error: this error cased by `slot-scope="{ values, search }"` where `search` in not used inside `selection` slot

**Comment by Stalinko** [comment]
I fell into the same issue. Copying the code from docs doesn't work the same as in docs.
But @reenekt's example works. The key is in this little difference:

from docs (wrong way):
`<span class="multiselect__single" v-if="values.length && !isOpen">`

the proper way:
`<span class="multiselect__single" v-if="values.length" v-show="!isOpen">`

I think there is mistake in the docs. Also the docs don't say anything about the "selection" slot in "API - Slots" section. This slot is mentioned only in the examples.
