### ISSUE TITLE
Can an event be triggered on Keyup on search

### ISSUE THREAD

**Issue by jithinb68** [shentao/vue-multiselect#1344]
Can we trigger an event on keyup so that options can be populated from an api response ?

`<multiselect v-model="value" :options="websites" label="url" track-by="url" :allow-empty="false" class="header-select mr-3" v-on:keyup.enter="submit"></multiselect>`

**Comment by akki-jat** [comment]
@jithinb68 You can listen to search change event to update options https://vue-multiselect.js.org/#sub-events
