### ISSUE TITLE
Add prop to edit text of maxElements

### ISSUE THREAD

**Issue by luger95** [shentao/vue-multiselect#1345]
Hello,

Can you add a prop for edit the text of maxElements ?

Thanks

**Comment by mostafa-rahmani** [comment]
Hi. There is a maxElements slot that can use to customize this.

**Comment by akki-jat** [comment]
@luger95 As stated by @mostafa-rahmani, please use maxElements slot (https://vue-multiselect.js.org/#sub-slots)
