### ISSUE TITLE
Hide tags and keep placeholder

### ISSUE THREAD

**Issue by mcnuggetboii** [shentao/vue-multiselect#1346]
I'm in a situation similar to https://stackoverflow.com/questions/62927900/how-to-not-have-tags-in-vue-multiselect where I wish to remove the whole tag div after selecting some option, the proposed solution on stackoverflow though leave an ugly empty box when something is selected.. isn't there anyway to remove the tags and keep the placeholder?

**Comment by harunkocacaliskan** [comment]
You may use css with v-if. 
Or 
```
<template slot="selection"
    slot-scope="{ values, search, isOpen }">
...
</template>
```

**Comment by akki-jat** [comment]
@mcnuggetboii Please take a look at https://github.com/shentao/vue-multiselect/issues/1379#issuecomment-1295953419
