### ISSUE TITLE
Line shows when search is selected

### ISSUE THREAD

**Issue by kriskenyon** [shentao/vue-multiselect#1347]
### Steps to reproduce
When multi-select is not active and search is selected a line for the input box shows on Mac with Firefox and Safari (maybe others this is all I tested). This appears to be because of the browser behavior for the style tag width: 0px 
### Expected behaviour
We should not see a line
### Actual behaviour

I fixed this by adding the following CSS to my site perhaps it could be integrated.
.multiselect .multiselect__input {
  display: none;
}
.multiselect--active .multiselect__input {
  display: block;
}

**Comment by akki-jat** [comment]
@kriskenyon Please provide reproducible link
