### ISSUE TITLE
Asynchronous paginated results

### ISSUE THREAD

**Issue by realnot** [shentao/vue-multiselect#1356]
Anyone know how to handle paginated results for long list of options?

**Comment by bayi** [comment]
Here is an idea:

Add a button in the `afterList` slot with the text 'Load More' and implement the click handler for it which loads your next page.

**Comment by kamirt** [comment]
@realnot maybe its too late but I solved this by infiniti scroll by wrapping this component like below.
It's quite complicated but idea is to give it a vuex action method and it use it for paginated requests. Custom "beautiful" preloaders used for user's detecting that there will be another data when the server will answer.
`
<template>
  <app-select
    ref="appSelect"
    class="select-remote"
    v-bind="mergedSelectOptions"
    :options="options"
    :loading="loading"
    :is-required="isRequired"
    :value.sync="model"
    @search-change="search"
    @open="onOpen($event)"
    @close="onClose($event)"
  >
    <template #beforeList>
      <preloader
        class="select-remote__preloader"
        :show="isShowPrevLoader"
      ></preloader>
    </template>
    <template #afterList>
      <preloader
        class="select-remote__preloader"
        :show="isShowNextLoader"
      ></preloader>
    </template>
    <template #option="props">
      <slot name="option" :props="props.props"></slot>
    </template>
  </app-select>
</template>

<script>
  import { merge, throttle } from 'lodash'

  const defaultSelectOptions = {
    searchable: true,
    preserveSearch: true,
    internalSearch: true,
    optionsLimit: 40
  }

  const SCROLL_THROTTLE_TIME = 500
  const PRELOADER_HEIGHT = 30

  export default {
    name: 'select-remote',

    props: {
      isRequired: {
        type: Boolean,
        default: false
      },
      action: {
        type: Function,
        required: true
      },
      selectOptions: {
        type: Object,
        default: () => {
          return defaultSelectOptions
        }
      },
      paginationSize: {
        type: Number,
        default: 20
      },
      value: {
        type: [Number, String, Object, Array],
        default: null
      },
      sort: {
        type: String,
        default: 'name,asc'
      }
    },

    data () {
      return {
        offset: 0,
        totalElements: null,
        optionsElement: null,
        throttledOnScroll: throttle(this.onScroll, SCROLL_THROTTLE_TIME),
        loading: false,
        showPrevLoader: false,
        showNextLoader: false,
        lockFetch: false,
        options: [],
        direction: '',
        searchString: null,
        isOpened: false
      }
    },

    computed: {
      model: {
        get () {
          return this.value
        },
        set (newVal) {
          this.$emit('update:value', newVal)
        }
      },
      mergedSelectOptions () {
        return merge(defaultSelectOptions, this.selectOptions)
      },
      hasNext () {
        return this.offset + this.paginationSize < this.totalElements
      },
      hasPrev () {
        return this.offset > 0
      },
      isShowPrevLoader () {
        return this.showPrevLoader && this.options.length > this.paginationSize
      },
      isShowNextLoader () {
        return this.showNextLoader && this.options.length >= this.paginationSize
      }
    },

    methods: {
      async search (value) {
        this.searchString = value
        this.isOpened = false
        this.offset = 0
        this.options = []
        await this.getPage()
        this.showPrevLoader = false
        this.showNextLoader = false
        this.isOpened = true
      },

      getSearchData () {
        let data = this.searchString
          ? { search: { value: this.searchString } }
          : { search: { value: '' } }
        if (!this.mergedSelectOptions.searchable) {
           data = null
         }
        return data
      },

      async getPage () {
        this.lockFetch = true
        const { data: { content, totalElements } } = await this.action({
          size: this.paginationSize,
          offset: this.offset,
          sort: this.sort,
          data: this.getSearchData()
        })
        this.totalElements = totalElements
        this.options = content
        this.lockFetch = false
        return { totalElements }
      },

      async getNextPage () {
        this.lockFetch = true
        const { data: { content } } = await this.action({
          size: this.paginationSize,
          offset: this.offset,
          sort: this.sort,
          data: this.getSearchData()
        })
        const current = this.cutCurrentForNext()
        const result = [].concat(current, content)
        this.$set(this, 'options', result)
        await this.scrollToHalfHeight()
        this.lockFetch = false
      },

      async getPrevPage () {
        this.lockFetch = true
        const { data: { content } } = await this.action({
          size: this.paginationSize,
          offset: this.offset,
          sort: this.sort,
          data: this.getSearchData()
        })
        const current = this.cutCurrentForPrev()
        const result = [].concat(content, current)
        this.$set(this, 'options', result)
        await this.scrollToPrevHeight()
        this.lockFetch = false
      },

      cutCurrentForNext () {
        const { paginationSize: pSize } = this
        if (this.offset > pSize) {
          return this.options.slice(pSize, pSize * 2)
        }
        return this.options.slice(0, pSize)
      },

      cutCurrentForPrev () {
        const { paginationSize: pSize } = this
        return this.options.slice(0, pSize)
      },

      async scrollToHalfHeight () {
        await this.$nextTick()
        const { optionsElement: { clientHeight, scrollHeight } } = this
        const to = (scrollHeight / 2) - clientHeight + PRELOADER_HEIGHT
        this.optionsElement.scrollTo({
            top: to,
            left: 0,
            behavior: 'auto'
          })
      },

      async scrollToPrevHeight () {
        await this.$nextTick()
        const { optionsElement: { scrollHeight } } = this
        const to = (scrollHeight / 2) - PRELOADER_HEIGHT
        this.optionsElement.scrollTo({
          top: to,
          left: 0,
          behavior: 'auto'
        })
      },

      hideEndPreloader () {
        const { optionsElement: { clientHeight, scrollHeight } } = this
        const to = scrollHeight - clientHeight - PRELOADER_HEIGHT
        return this.optionsElement.scrollTo({
          top: to,
          left: 0,
          behavior: 'smooth'
        })
      },

      hideStartPreloader () {
        return this.optionsElement.scrollTo({
          top: PRELOADER_HEIGHT,
          left: 0,
          behavior: 'smooth'
        })
      },

      async onOpen () {
        this.isOpened = true
        if (this.$refs) {
          const { list } = this.$refs.appSelect.$refs.select.$refs
          this.loading = true
          await this.getPage()
          this.loading = false
          return this.setDomElements(list)
        }
      },

      setDomElements (optionsEl) {
        this.optionsElement = optionsEl
        this.optionsElement.addEventListener('scroll', this.throttledOnScroll)
      },

      onScroll () {
        this.showPrevLoader = true
        this.showNextLoader = true
        const {
           optionsElement: {
             scrollTop,
             clientHeight,
             scrollHeight
           }
        } = this
        const scrollTotalHeight = scrollHeight - clientHeight

        if (this.totalElements <= this.paginationSize) { return }

        if (scrollTop >= scrollTotalHeight) {
          this.incrementOffset()
        }
        if (scrollTop === 0) {
          this.decrementOffset()
        }
      },

      incrementOffset () {
        if (this.lockFetch) { return }
        if (!this.hasNext) {
          this.hideEndPreloader()
          return
        }
        const { direction } = this
        this.direction = 'forward'
        if (direction === 'back') {
          this.offset += this.paginationSize * 2
          return
        }
        this.offset += this.paginationSize
      },

      decrementOffset () {
        if (this.lockFetch) { return }
        const { direction } = this
        if (!this.hasPrev) {
          this.hideStartPreloader()
          return
        }
        if (this.offset === this.paginationSize && direction === 'forward') {
          this.hideStartPreloader()
          return
        }
        this.direction = 'back'
        if (direction === 'forward') {
          const offset = this.offset - this.paginationSize * 2
          this.offset = offset < 0 ? 0 : offset
          return
        }

        this.offset -= this.paginationSize
      },

      onClose () {
        this.isOpened = false
        this.direction = ''
        this.options = []
        this.optionsElement.removeEventListener(
          'scroll',
          this.throttledOnScroll
        )
        this.offset = 0
        this.optionsElement = null
        this.showPrevLoader = false
        this.showNextLoader = false
        this.totalElements = null
        this.showNextLoader = false
      }
    },

    watch: {
      async offset (val, prev) {
        if (!this.isOpened) { return }
        if (val > prev) {
          return await this.getNextPage()
        }
        return await this.getPrevPage()
      }
    }
  }
</script>

`

**Comment by akki-jat** [comment]
@realnot Please reopen the issue if you are still facing any difficulties for the same.
