### ISSUE TITLE
Can you add the ability to customize the css?

### ISSUE THREAD

**Issue by torressam333** [shentao/vue-multiselect#1358]
I see you have the css for the multiselect in the Multiselect.vue. Would it be possible to add an additional configuration step to allow us to customize the css? For example, you have the multi select background as green but I want to change these colors to suit my app. Thank you.

**Comment by ryrych** [comment]
Try this:
https://github.com/shentao/vue-multiselect/issues/718#issuecomment-692012037

and consider this:
https://github.com/makeless/makeless-ui/blob/master/src/scss/vue-multiselect.scss

The first one works for me (didn't try the second one as I'm not using multiple options). In the `main.ts` I replaced loading minified styles in favor of loading styles from the first link in our app's `main.sass`. To match the styles with our app's theme, I extracted variables to a separate stylesheet and override them in `variables-overrides.scss`.
