### ISSUE TITLE
How to use the vue-multiselec min.css file as a static asset within my app.scss

### ISSUE THREAD

**Issue by torressam333** [shentao/vue-multiselect#1359]
I am trying to load the css as a static asset in my app.scss file but when I try to ```import``` the file, npm does not seem to find it and throws a slew of errors. 

I am trying to import like so in mt ```app.scss```

`@import './node_modules/vue-multiselect/dist/vue-multiselect.min.css';`

But I get all this error:

```
ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleNotFoundError: Module not found: Error: Can't resolve './node_modules/vue-multiselect/dist/vue-multiselect.min.css'

```

I know I can ```require()``` this path in my ```resources/app/js``` file but I want to keep the css and js assets separate.

Anyone know the correct way to import as a static asset into ```app.scss``` ?

The docs just show this but do not elaborate

```
<!-- New step! Add Multiselect CSS. Can be added as a static asset or inside a component. -->
<style src="vue-multiselect/dist/vue-multiselect.min.css"></style>

```

**Comment by kennybuc** [comment]
@torressam333 Hello, I have got the same issue, and were you able to solve this issue?

**Comment by torressam333** [comment]
@kennybuc Hi, actually I was so the issue was a missing tilda when trying to import the vue-multiselect into my app.scss. This is the working line in my app.scss file 

```@import '~vue-multiselect/dist/vue-multiselect.min.css';```

Notice the tilda right before the word "vue"! This did the trick for me. Hope it helps!

**Comment by kennybuc** [comment]
@torressam333 Thank you very much for providing the hint to me.
I actually believe that it would work in vue cli app. And I have got a trouble within my nuxt app, and it looks like there should be a setting to enable this plugin. Didn't check yet.
I just ended up with decision to use the pure html instead. Anyway I appreciate for your info.
