### ISSUE TITLE
Can't remove selected items

### ISSUE THREAD

**Issue by hasan-araav** [shentao/vue-multiselect#1365]
I am trying to remove selected multiple tagged items. But can't remove the items.

**Comment by xt2018** [comment]
Multi - option deletion:
HTML：<multiselect @remove="delItem"></multiselect>
JS:delItem：function(removedOption){}

Single option deletion:
HTML:<multiselect>
                        <template slot="clear" slot-scope="props">
                            <div @mousedown.prevent.stop="delAll"
                                 class="multiselect__clear"
                                 title="Remove this option"
                                 v-if="XXXXX"></div>
                        </template>
                        <span slot="noResult">No match</span>
        </multiselect>
JS:delAll：function(){}

**Comment by akki-jat** [comment]
@hasan-araav / @mayoalexander Please provide reproducible link
