### ISSUE TITLE
Minimal number of characters typed before showing noResult

### ISSUE THREAD

**Issue by Ash-Crow** [shentao/vue-multiselect#1368]
Hi,
I'm using vue-multiselect with ajax to populate the options list, and in order to avoid useless queries the method doesn't actually send a query until the user has typed at least 3 characters. So until that, the options lists stays empty.

The problem with this is that the "noResult" message is shown after the first letter typed in the search bar. Is there a parameter to tell "noResult" not to show up until the user has typed `n` characters? If not, I think it would be useful to create it.

**Comment by xt2018** [comment]
Yes, I've noticed that, but it takes a few more characters to search the data and populate the drop-down selection box, and I don't know if that's a BUG or not

**Comment by bayi** [comment]
You have 2 options here:
 - Use the `show-no-results` prop with a computed val that sets it to false until the user typed in 3 characters.
 - Use the `noResult` slot to display your customized message ( eg. search.length < 3 ?  'Type more characters` : `No results` )

**Comment by xt2018** [comment]
Yes, I do use it that way

**Comment by akashrajum7** [comment]
I think this is solved and can be closed @shentao

**Comment by shentao** [comment]
Thanks @akashrajum7!

**Comment by Mohamadkabalan** [comment]
i have added the noResult slot like below , and it is not working
                <Select2MultipleControl  v-model="booking.leaders" :options="booking.leaders" :settings="{tags: true  }">
                    <noResult>test here</noResult>
                </Select2MultipleControl>

**Comment by Mohamadkabalan** [comment]
![image](https://user-images.githubusercontent.com/33176629/118628961-ccfd4700-b7d5-11eb-80ba-c143c290d596.png)
