### ISSUE TITLE
Custom caret in 2020?

### ISSUE THREAD

**Issue by katerlouis** [shentao/vue-multiselect#1377]
I found this fiddle referenced multiple times in issues when dealing with custom slots.
https://jsfiddle.net/shentao/qojvh1eg/

While this still works with latest Nuxt (v2.14.6) the Vue docs state that `slot-scope` is deprecated and replaced by `v-slot`

1. Could you explain how to use `v-slot` with this?
2. Maybe you could extend the docs by a custom caret example?

**Comment by fabien-ml** [comment]
Hi, you should replace your `span` with this : 

```vue
<template #caret={toggle}>
  <span 
    class="arrow" 
    @mousedown.prevent.stop="toggle"
   >
     oh hi
   </span>
</template>
```

**Comment by katerlouis** [comment]
What kind of syntax is that? `#caret={toggle}`? Can you point to a resource?

**Comment by fabien-ml** [comment]
This is just basic vue scoped slots. 

`#caret` is an shorthand for `v-slot:caret`.

Vue docs => https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots

**Comment by fabien-ml** [comment]
In short you target the slot named "caret" and you use destructuring to access is slot props named "toggle"

**Comment by katerlouis** [comment]
Crazy. How did I not stumble uppon this myself?!
You omitted quotes in your example; why does `#caret={toggle}` work? (Doesn't seem to be reflected in the docs)

**Comment by fabien-ml** [comment]
Yes you need the quotes sorry. 
I've updated the example.

**Comment by katerlouis** [comment]
The funny thing is: I tried it without quotes in the fiddle, and it worked :O
