### ISSUE TITLE
How to make multiselect without tags like in the example?

### ISSUE THREAD

**Issue by katerlouis** [shentao/vue-multiselect#1379]
in the [multi select example ](https://vue-multiselect.js.org/#sub-multiple-select) you don't have the tags when the dropdown is open. 

![want it like that](https://user-images.githubusercontent.com/1983382/101883165-2e6e1980-3b97-11eb-8a59-2e904e8be43c.png)

But even if I copy paste the example including the `<template>`-slot. I get the tags in my front-end.

![but I get that](https://user-images.githubusercontent.com/1983382/101883424-87d64880-3b97-11eb-8c9c-33e9fc95ff30.png)

Why is that and how can I recreate what you have in the example? 

### Reproduction Link
https://jsfiddle.net/jpes4v35/

### Expected behaviour
no tags when dropdown is open

### Actual behaviour
there are tags when dropdown is open :'(

**Comment by tgfighter** [comment]
@katerlouis this was also driving me nuts and I believe I figured out a way to make it work like the example given in the doc.

First off, I needed to change the version from 2.1.0 to 2.1.6. Second, I added the following HTML code just before internal template "selection" tag:
`<template slot="tag" slot-scope="props"><span></span></template>`

Here is the [jsfiddle link](https://jsfiddle.net/thqo1dsy/)

**Comment by akki-jat** [comment]
@katerlouis Here is the example code for the same https://codesandbox.io/s/vue-multiselect-no-tags-when-dropdown-opens-d3n3nc
