### ISSUE TITLE
Is it possible to change the default "Enter" binding to "Space"?

### ISSUE THREAD

**Issue by Stalinko** [shentao/vue-multiselect#1382]
I've got into a situation that I need to change the default behaviour of "Enter" key. I want to make it submit the form (it's easy) and the values in the dropdown will be selected or unselected with Space (this is the issue).

I don't see any options to define another key instead of "Enter". Is there a simple way to achieve that?

**Comment by Stalinko** [comment]
Researched this topic. Unfortunately the "Enter" binding is hardcoded. So the only possible option I found is: get rid of `v-model` and listen to `@select` and `@remove` myself, then implement own bindings.

**Comment by kgrosvenor** [comment]
> Researched this topic. Unfortunately the "Enter" binding is hardcoded. So the only possible option I found is: get rid of `v-model` and listen to `@select` and `@remove` myself to avoid hardcoded bindings, then implement own bindings on top of that.

If i'm going to be honest, keeping the enter to select is standard practice. Even on native select boxes. They prevent the default behaviour of submitting the form.

**Comment by akki-jat** [comment]
@Stalinko As space key can also conflict with search box, we don't have any plan to support it.
