### ISSUE TITLE
Vue-multiselect Dropdown opens but not appear on screen

### ISSUE THREAD

**Issue by fawadahmad** [shentao/vue-multiselect#1386]
I am using vue-mutiselect:2.1.6 on a Laravel 7 project with vue: 2.6.10.

It is working fine on Ubuntu/Windows/Mac Firefox/Chrome/Safari. Also working in chrome's iPhone and iPads emulators. Running good too in Xcode simulators.

But, on real iPhone and iPad, when I click on dropdown icon or placeholder area, the icon rotates, but options are not visible. And when I assume the location of an option and tap on that position, the options suddenly become visible and that option is actually selected.

iPad Pro (9.7"), iOS: 13.4.1

**Comment by holtolee** [comment]
Same here, needs a fix

**Comment by akki-jat** [comment]
@mattelen Please take a look.

**Comment by mattelen** [comment]
I'm having trouble replicating this. I'm using a real device (via Browserstack), and if I click on the dropdown arrow, I see the menu loads fine:
![image](https://user-images.githubusercontent.com/9289772/200018604-8f777982-9289-4571-8e0f-d4faa2ab8a8b.png)
This was on a iPad Pro 11 running iOS 13.

Can you provide a reproducible link so we can replicate the issue (and we can see if we need to use and actual device, or if a real remote device like what Browserstack provides is enough)

Thanks
