### ISSUE TITLE
@select and @input events are only triggered when user selects the option

### ISSUE THREAD

**Issue by AllanOricil** [shentao/vue-multiselect#1392]
### Steps to reproduce
1 - Pass an Array of Objects like ``[{ name; 'A', label: 'A'}, { name; 'B', label: 'B'} ]`

2 - on the Parent component, set `this.selected = { name; 'B', label: 'B'}` anywhere you want. Like make a button that when clicked it will set `this.selected`

3 - Pass `this.selected` to v-model or :value

4 - verify that the input has changed but @select and @input events handlers are not called

5 - click on the option and verify that the event handlers are called

### Expected behaviour
If the input has changed, why the events should be dispatched

### Actual behaviour
@select and @input are only dispatched when the user clicks on the option

**Comment by AllanOricil** [comment]
Im not able to reproduce it. It just does not work in my app. Could you help me to understand what is the possible problem.

````html
<multiselect
                      class="mb-1"
                      v-model="selectedSObject"
                      :options="sobjects"
                      label="label"
                      track-by="name"
                      searcheable
                      :max-height="400"
                      select-label=""
                      deselect-label=""
                      placeholder=""
                      hide-selected
                      @input="onSelectSObject"
                      @select="onSelectSObject"
                    >
                      <template slot="singleLabel" slot-scope="{ option }">{{
                        option.label + ' - ' + option.name
                      }}</template>
````

sobjects is an array of objects containing only name and label keys

![image](https://user-images.githubusercontent.com/55927613/106445552-0e602580-6477-11eb-8a77-a67b931cca80.png)

When my parent component sets the `selectedSObject` I can see that the option was selected with no problem, but the @input and @select events were not triggered

**Comment by AllanOricil** [comment]
I checked every emit('input') for when the internalValue changes and this caught my attention https://github.com/shentao/vue-multiselect/blob/master/src/multiselectMixin.js#L389 why would it emit an input with null or an array with nothing? 

![image](https://user-images.githubusercontent.com/55927613/106449347-ca235400-647b-11eb-888b-fca526d4586f.png)

If I change the value it should dispatch an event so the parent can capture. It can't just depend on user interaction.

If parent changes the :value through v-model, or even just by setting the :value prop, the internal value gets recalculated, and then it has to emit an 'input' event to the parent with the new value.

**Comment by AllanOricil** [comment]
@shentao  could you help with this?

**Comment by font-size** [comment]
try
`<multiselect
                      **label="name"** 
                      track-by="name"
                    >
                `

**Comment by AllanOricil** [comment]
I actually refactored the code to make it work. It was not emitting events when the internal value changed.
