### ISSUE TITLE
Same component data different render in modal window

### ISSUE THREAD

**Issue by d3tr1tus** [shentao/vue-multiselect#1393]
Hi I have problem with vue-multiselect component if `searchable` is `true` and it is in modal window opened. I am setting same data but in modal I can't search in options and also unfocus from component don't close options. I get no error in console. Did someone same issue? 

Right version 
<img width="303" alt="Snímek obrazovky 2021-02-01 v 11 31 29" src="https://user-images.githubusercontent.com/37714206/106446982-38b6e080-6481-11eb-94ee-f076bd077034.png">

Bug version
<img width="261" alt="Snímek obrazovky 2021-02-01 v 11 32 03" src="https://user-images.githubusercontent.com/37714206/106447000-3f455800-6481-11eb-98f4-894da2419289.png">

Thank you for your help.

**Comment by akki-jat** [comment]
@d3tr1tus  - Please provide reproducible link
