### ISSUE TITLE
How to implement a label that is not the same as the value displayed when it is selected

### ISSUE THREAD

**Issue by smartwei** [shentao/vue-multiselect#1395]
I have a function
The data are as follows:
```
data:{ 
	userList:[
		{id:1,name:"tom",code:"10001"}
		{id:2,name:"tony",code:"10002"}
		{id:3,name:"jack",code:"10003"}
		......
		],
		user:{id:2,name:"lily",code:"10002"}
}
```
HTML:

```
<multiselect  v-model="user" label="name" 
:show-labels="false" 
:options="userList"
:hide-selected="true" 
@search-change="findUser" 
@select="setUser($event)">
```

**1. I input "t" to display the following drop-down format:**
tom-10001
tony-10002
When I selected "tony-10002", this input show "tom", not include "10002"

**2. I input "92" to display the following drop-down format:**
tony-10002
When I selected "tony-10002", this input show "tom", not include "10002"

How to implement this feature

**Comment by aamatveev** [comment]
maybe this will help you: [sub-custom-option-template](https://vue-multiselect.js.org/#sub-custom-option-template)

**Comment by akki-jat** [comment]
@smartwei - As suggested by @aamatveev, please look at [sub-custom-option-template](https://vue-multiselect.js.org/#sub-custom-option-template).

If there is still any issue then let us know.
