### ISSUE TITLE
"max" does not work properly when selecting all items in an option group

### ISSUE THREAD

**Issue by Yosi85** [shentao/vue-multiselect#1398]
When using option groups it is possible to select more item than what is defined in max

### Reproduction Link
https://jsfiddle.net/q4xb5ns6/

### Steps to reproduce
Select the "test" group to select all its items

### Expected behaviour
Only 2 items are selected because max is set to 2

### Actual behaviour
All items are selected

**Comment by lehoaibaokg** [comment]
To do that we can remove the last items of the `value` manually (using `splice`) if the `value.length` is greater than or equal to the max value on the `@input` event.

**Comment by akki-jat** [comment]
@Yosi85 Please provide new production link as old one is not working.

**Comment by Yosi85** [comment]
@akki-jat I've created a new jsFiddle as requested. https://jsfiddle.net/10wvLmng/1/

**Comment by akki-jat** [comment]
@Yosi85 - Thanks for quick response.

**Comment by lehoaibaokg** [comment]
> @Yosi85 Please provide new production link as old one is not working.

Just add vue2 cdn url to resources, it will work

**Comment by akki-jat** [comment]
@Yosi85 / @lehoaibaokg Opened the PR, please take a look.

https://github.com/shentao/vue-multiselect/pull/1580

**Comment by Yosi85** [comment]
Thanks for fixing this. Any idea when 2.1.7 is going live?

**Comment by mattelen** [comment]
Check out the discussion happening around the release here: https://github.com/shentao/vue-multiselect/discussions/1589
