### ISSUE TITLE
choose only one option from each group

### ISSUE THREAD

**Issue by DeNIKE666** [shentao/vue-multiselect#1402]
Good afternoon, tell me how can I choose only one option from each group?

I have a price for each option and I only need to choose one option in each group, help me how can I do this

![Снимок экрана 2021-02-26 160937](https://user-images.githubusercontent.com/30469085/109293054-17150300-784d-11eb-8df2-7bae64482b8c.png)

**Comment by nandanv2702** [comment]
I couldn't find a straightforward method to do this in the docs, but using the example they provided [here](https://vue-multiselect.js.org/#sub-option-groups) you could listen to the `@select` event and then filter the `Options` array to see if `value` already has an element from that group. If it does, you can remove the old element from `value` and let the new one remain - this would essentially deselect the previously chosen option from that options group.

Might not be the most efficient way to go about it, but let me know how you solved this!

**Comment by akki-jat** [comment]
@DeNIKE666 As @nandanv2702 suggested this should done from user side as library can't support all of the custom requirements from the different users.
