### ISSUE TITLE
Project Status - Abandoned (?)

### ISSUE THREAD

**Issue by vicenterusso** [shentao/vue-multiselect#1404]
Is there any active fork of this project?

**Comment by devzom** [comment]
Bump bump, lot of Pull request with nice fixes.

**Comment by mattelen** [comment]
We've just published a Vue 3 Upgrade of the multiselect component here: https://github.com/SuadeLabs/vue3-multiselect. The idea is that it is a simple replacement for this component, without needing to tweak anything. Not too sure if this is what you are looking for, but it might help

**Comment by nmauersberg** [comment]
Awesome! Works fine for me in a huge project. <3
Thank you!

**Comment by OliverGrimsley** [comment]
> We've just published a Vue 3 Upgrade of the multiselect component here: https://github.com/SuadeLabs/vue3-multiselect. The idea is that it is a simple replacement for this component, without needing to tweak anything. Not too sure if this is what you are looking for, but it might help

Wow, thank you for doing this! . . . I was getting ready to try a v3 migration in a large app and pretty sure this is the one component that was going to be a nightmare for me.  If I hit issues I will try and help out on your repo/post issues.

**Comment by shentao** [comment]
Thanks to @mattelen, we just released v3.0.0-alpha.1 under the `next` tag. See https://github.com/shentao/vue-multiselect/tree/next
