### ISSUE TITLE
Event onclose the fisrt value is null

### ISSUE THREAD

**Issue by truongnguyengithub** [shentao/vue-multiselect#1409]
When the first choose value and handler event onclose I receive value is null.

**Comment by arusahni** [comment]
I had the same issue. My issue was that I was using objects for options, and had set `:track-by="value"` while also having a `value` prop on my component. I solved it by removing the binding, and using `track-by="value"`.

**Comment by akki-jat** [comment]
@truongnguyengithub Please provide reproduction link
