### ISSUE TITLE
Prevent flickering when multi-select dropdown opens inside a modal inside an Iframe [Chromium only]

### ISSUE THREAD

**Issue by itslit-tech** [shentao/vue-multiselect#1416]
### Reproduction Link
https://helloxolotl.com.au/en/tours#

### Steps to reproduce
1) Visit https://helloxolotl.com.au/en/tours#
2) Scroll down to the cards with the heading "Meetup with Hello Xolotl" or search for the same 
3) On the right side card, click on Book now. 
4) On the first step, open the vue-multiselect dropdown and notice the flickering behind the modal. Here is a video demonstrating the same 
https://user-images.githubusercontent.com/30520766/113866227-b02f2600-97ca-11eb-8737-19c6ac452dfa.mov

5) The same does not happen on Safari or Firefox. Happens on Brave Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (x86_64). 
6) Also the issue does not happen on a similar page - https://melbourne.tashi.travel/ with similar steps to reproduct

### Expected behaviour
There is no flickering when opening the dropdown

### Actual behaviour
There is  flickering when opening the dropdown and making it unusable

**Comment by shentao** [comment]
I assume there might be some conflicting CSS and possibly Chrome misfunctioning, but likely shouldn’t be caused by vue-multiselect.
