### ISSUE TITLE
Change only text in tag slot

### ISSUE THREAD

**Issue by fdellekart** [shentao/vue-multiselect#1420]
I found the `tag` slot to customize the appearance of tags in multiple select. However, with this I am overriding the whole tag.

I want to only customize the appearance of the text in the tag, everything else can stay the same, especially the deletion is needed, how can I do this?

**Comment by fdellekart** [comment]
Found the solution myself:

There is a prop `customLabel` which takes a function to construct a custom label from the option

**Comment by rrpatricio** [comment]
Nice.

You can customize the tags like this too:

```
   <template v-slot:tag="{ option, remove }">
      <div class="multiselect__tag">
        <span>{{ option.yourCustomLabel }}</span>
        <i class="multiselect__tag-icon" @click.prevent @mousedown.prevent.stop="remove(option, $event)" />
      </div>
    </template>
```

And you will have the delete button there. This way you can have a custom label only in the tag, without changing the label in the options list (of course, you can change the options slot to have something different there too).

**Comment by akki-jat** [comment]
@rrpatricio Thanks for jumping in with example.
