### ISSUE TITLE
Cannot read property 'blur' of undefined

### ISSUE THREAD

**Issue by muhammadbima20** [shentao/vue-multiselect#1421]
Hi there, i have a problem while using `vue-multiselect`, i use `nuxtjs`, and `vue-multiselect v2.1.6` and the problem or bugs i found is :

i got an error when i focused / open the select option this multiselect, and then try to redirect to previous page using back button in my chrome, the error message is :

`Cannot read property 'blur' of undefined`

the only thread i found for fixing my problem said that i have to write this one :

`beforeDestroy(){ this.$refs.myMultiSelect.deactivate(); },`

but still got an error `Cannot read property 'blur' of undefined` and a new one : `TypeError: Cannot read property 'deactivate' of undefined`

so what should i do for fixing my problem ? any help will be very appreciated.
Thanks!

**Comment by shentao** [comment]
Thanks for reporting!

**Comment by anilsonlopes** [comment]
You need replace `myMultiSelect` for used ref on element.

**Comment by mylesboone** [comment]
Looks like ln 677 of multiselectMixin.js  
```js
      if (this.searchable) {
        this.$refs.search && this.$refs.search.blur()
      } else {
        this.$el.blur()
      }
```
ends up compiling to 

`this.searchable?this.$refs.search.blur():this.$el.blur()`

**Comment by atilkan** [comment]
Is there any chance of fixing this?

**Comment by shentao** [comment]
@atilkan if you could help me verify if the linked PR works, then I could try to release that fix in the next 2 weeks.

**Comment by Namstel** [comment]
I myself am running into problems using optional chaining. See:
https://github.com/shentao/vue-multiselect/pull/1497#issuecomment-1112148955

**Comment by Namstel** [comment]
> @atilkan if you could help me verify if the linked PR works, then I could try to release that fix in the next 2 weeks.

I looked at it and I can verify that the changes made in the linked PR work.
