### ISSUE TITLE
remove button not working without refreshing

### ISSUE THREAD

**Issue by rushimanche** [shentao/vue-multiselect#1422]
Hello,

I have the code below:

**Unable to include fiddle in this situation due to company issues**

```
    var CatShelter = {
        template:
    '<vue-multiselect' +
    ' :options="options">' +
    '<template> <i v-on:click="removeCats(option)"></i></span> </template>' +
    '</vue-multiselect>' +,
    props: {options: Array},
    methods: {
    removeCats: function (object) {
                self = this;
    this.options.pop();
                $.ajax({
                    type: "PATCH",
                    url: //irrelevant,
                    'data': //irrelveant,
                    'dataType': 'json',
                    success: function (result) {
                        
                    },
                    error: function (result) {
                    }
                });
    
    }
    }
    }

    },
```
Basically, when the icon is clicked it calls this ajax request which removes an option from vue multiselect through DB. This works fine. When I refresh, the changes occur. I wantto be able to remove the options in real time. The options prop is essentially an array of the objects. How can I get vue to update the prop without refreshing which adjusts the vue multiselect?

**Comment by shentao** [comment]
The reproduction code seems broken. Could you create a working fiddle?
