### ISSUE TITLE
Multiselect Search Suggestion not clearing even after text are not present

### ISSUE THREAD

**Issue by joseph-9900** [shentao/vue-multiselect#1423]
Hello everyone,
I know this a past issue and I have gone through almost all issue's here but couldn't find the solution.
In multiselect dropdown, When I search data, data's are showing. After clearing the search text the search suggestion is still showing in the dropdown.

Please can you help me with how to clear the search suggestion that keep on displaying even after the text is not present there.

Thank you :-)

**Comment by shentao** [comment]
Hey! Could you please provide a reproduction fiddle? I’m not exactly sure I understand the problem.
