### ISSUE TITLE
multiple instances not working properly with "Enter" key

### ISSUE THREAD

**Issue by dmcbrn** [shentao/vue-multiselect#1427]
### Reproduction Link

```
<div id="app">
  <multiselect 
    v-model="value" 
    :options="options"
    :multiple="true"
    track-by="library"
    :custom-label="customLabel"
    >
  </multiselect>
  <multiselect 
    v-model="value2" 
    :options="options2"
    :multiple="true"
    track-by="library"
    :custom-label="customLabel"
    >
  </multiselect>
  <pre>{{ value }}</pre>
  <pre>{{ value2 }}</pre>
</div>
```

```
new Vue({
	components: {
  	Multiselect: window.VueMultiselect.default
	},
	data: {
  	value: null,
  	options: [
    	{	language: 'JavaScript', library: 'Vue.js' },
      { language: 'JavaScript', library: 'Vue-Multiselect' },
      { language: 'JavaScript', library: 'Vuelidate' }
    ],
  	value2: null,
  	options2: [
    	{	language: 'JavaScript', library: 'Vue.js' },
      { language: 'JavaScript', library: 'Vue-Multiselect' },
      { language: 'JavaScript', library: 'Vuelidate' }
    ],
	},
  methods: {
  	customLabel (option) {
      return `${option.library} - ${option.language}`
    },
  	customLabel2 (option) {
      return `${option.library} - ${option.language}`
    },
  }
}).$mount('#app')
```
Version `2.1.6`. 

`https://cdnjs.cloudflare.com/ajax/libs/vue-multiselect/2.1.6/vue-multiselect.min.js`
`https://unpkg.com/vue-multiselect@2.1.6/dist/vue-multiselect.min.css`

It seems it was broken somewhere after `2.0.0-beta.15`

You can modify this fiddle https://jsfiddle.net/shentao/c4L3gs91/ by changing vue-multiselect versions and updating the js/html.

### Steps to reproduce

Select 2 options in 1st multiselect instance.
Select 1 option in 2nd multiselect instance.
Select another option in 2nd multiselect using "Enter" key.

### Expected behaviour

Selected option should be added to 2nd instance.

### Actual behaviour

The selected option is added to first instance, not second.

**Comment by dmcbrn** [comment]
It seems it's working correctly in 2.1.1. but broken in 2.1.2.

**Comment by akki-jat** [comment]
@dmcbrn Closing this as working fine in 2.1.6
