### ISSUE TITLE
not able to change the "no result found" text

### ISSUE THREAD

**Issue by Mohamadkabalan** [shentao/vue-multiselect#1436]
i have added noResult slot as below and it is not working
![image](https://user-images.githubusercontent.com/33176629/118629188-059d2080-b7d6-11eb-921d-48ea537fa390.png)

**Comment by seballot** [comment]
Hi,

Here the good way for filling the slot in Vue2
```
<template #noResult>Test Here</template>
```

**Comment by mattelen** [comment]
Hi @Mohamadkabalan 

Like @seballot said, if you want to use a slot, you need to use a template element. Check out this Vue 2 guide on how to use named slots: https://vuejs.org/v2/guide/components-slots.html#Named-Slots. 
I'll close the issue, but if you find another issue, feel free to open one.
