### ISSUE TITLE
Can we get a JSFiddle for vue-multiselect 3.0 branch with Vue 3?

### ISSUE THREAD

**Issue by wkrick** [shentao/vue-multiselect#1439]
Is there a jsfiddle that shows the 3.0.x branch working with Vue 3?

I'm trying to add vue-multiselect to my Vue 3 app.  I'm not using a build manager or npm.

I'm using the following CDN links:

`https://cdn.jsdelivr.net/npm/vue@3.0.11/dist/vue.global.prod.js`

`https://cdn.jsdelivr.net/npm/vue-multiselect@3.0.0-alpha.1/dist/vue-multiselect.js`

I'm seeing two errors in the browser console:

`Uncaught ReferenceError: vue is not defined`

`Uncaught TypeError: window.VueMultiselect is undefined`

**Comment by lebadapetru** [comment]
Sorry i'm budging in but i couldn't find any info on the matter and i don't wanna create a new topic for such a small question.. Will the 3.0 version be compatible with the composition api?

I'm using webpack to completely remove the option api in my project and many other packages that claim they are Vue 3 compatible, are in fact compatible with the option api only

**Comment by mattelen** [comment]
Hi @wkrick looks like our builds aren't quite working as you would expect them. I believe I have implemented a fix for this, and hopefully will be released soon.

@lebadapetru we are wanting 3.0 to be compatible with the composition api when we launch stable, however this is still a WIP and may take some time to actually get there.

**Comment by wkrick** [comment]
> Hi @wkrick looks like our builds aren't quite working as you would expect them. I believe I have implemented a fix for this, and hopefully will be released soon.


@mattelen -  Awesome!  Thank you for looking at this.  I posted some test code over on StackOverflow because I thought I was doing something wrong as the V2 fiddle code didn't work anymore and vue-multiselect 3 was supposed to be "mostly backward compatible" with vue-multiselect 2...

https://stackoverflow.com/questions/67745654/how-do-i-get-vue-multiselect-3-working-with-vue-3-v2-v2-works-fine-in-this-ex

As soon as your fix gets released, I'll update my StackOverflow question.

**Comment by bassref** [comment]
Is it fixed yet? You see I have this project that needs to work yesterday...

**Comment by wkrick** [comment]
@shentao @mattelen - Will there ever be a new release that includes this change?  If not, is there a page somewhere that explains in detail how to make my own release build?

**Comment by jaulin** [comment]
Hiya, was there ever a resolution for this?

**Comment by wkrick** [comment]
@jaulin No resolution.  I don't think this project is active anymore, sadly.  I recently started working with PrimeVue and it meets all my needs.

**Comment by jaulin** [comment]
> @jaulin No resolution. I don't think this project is active anymore, sadly. I recently started working with PrimeVue and it meets all my needs.

Cheers mate 👍 was struggling to find an alternative that supports VueJS 3 and without using NPM.

**Comment by wkrick** [comment]
@jaulin - I understand you not wanting to use NPM.  I was against using npm for a long time too but I finally tried it a few months ago. The new "Vite" build system for Vue3 makes everything so easy.  Here's what it looks like to set up a basic Vue3 project using the vue template and then add PrimeVue...

```
npm create vite@latest my-vue-app -- --template vue
cd my-vue-app
npm install
npm install primevue@^3.12.2 --save
npm install primeicons --save
npm run dev
```

**Comment by PixsaOJ** [comment]
> 

Which alternative?

**Comment by PixsaOJ** [comment]
Why is this issue closed?
