### ISSUE TITLE
Tired of CSS debugging

### ISSUE THREAD

**Issue by Falseclock** [shentao/vue-multiselect#1441]
Is there any possibility to prevent closing, cause clicking in developer's console completely redraw whole component and can't even check what css are used for html element inside multiselect?

**Comment by mattelen** [comment]
Hi @Falseclock - if you are wanting to keep the multiselect open so you can see the CSS of this view, I think what will work better is using the "Emulate a focused page" option in dev tools. By activating this view, you can click open the multiselect, then use dev tools to manipulate the DOM and CSS, while the multiselect stays open. Here is how you can use it in Chrome:
 https://stackoverflow.com/questions/64456886/emulate-a-focused-page-option-not-available-in-chrome-developer-tools

I hope that helps. I'll close this issue as I think this solves your issue, but if you think there is still reason to open this up, let us know
