### ISSUE TITLE
Can we have customizable classname of the module oder prefixes?

### ISSUE THREAD

**Issue by giovanniTramonto** [shentao/vue-multiselect#1442]
### Expected behaviour
+ div :class="someClassName"

### Actual behaviour
+ div class="multiselect"

**Comment by mattelen** [comment]
Hi @giovanniTramonto. If you add a class attribute to the multiselect element, it will add the classes to that element. Check out this jsfiddle I've created demoing this: https://jsfiddle.net/eb7n5sc1/1.  

As a result, I don't think we need to do anything special around this on vue-multiselect. I'll close this issue, but if I have misunderstood anything feel free to comment.

**Comment by giovanniTramonto** [comment]
Hi @mattelen, thanks for answering. my point is that overriding the BEM structure in SCSS can be painful in cases where you want to have two multiselect items with different styles. For example https://codepen.io/gioTramonto/pen/wvJrjWw
