### ISSUE TITLE
Remove event is fired before 'input' event

### ISSUE THREAD

**Issue by sifear** [shentao/vue-multiselect#1444]
Similarly to Issue #484. 
It would be nice if I could work with updated value.

https://github.com/shentao/vue-multiselect/blob/3517065e3714c6b20438c5bb77d3c6f5ebd012ca/src/multiselectMixin.js#L617-L623

**Comment by greendesertsnow** [comment]
Confirmed,
https://jsfiddle.net/greendesertsnow/sdp8wr69/2/

I guess we're expected to filter out the option using (removedOption, id) to update the input values first.

**Comment by code1x1** [comment]
this makes the component almost unusable https://codesandbox.io/s/reverent-cache-shevo
