### ISSUE TITLE
Alters other inputs as well

### ISSUE THREAD

**Issue by pitylee** [shentao/vue-multiselect#1448]
Hi there,

I have an input named date_of_birth which will be reset, amongside any other text field with the following structure on option select:

<input type="text" name="date_of_birth" id="date_of_birth-input" data-name="date_of_birth" class="w-full form-control form-input border-60" value="yyyy-mm-dd">

Why is this happening?

Also multiple instances in one page can not be used, which is almost okay, I use associative array for the value, yet the @tag method should return a second attribute, which could be the :name="{}" or something similar, because right now I can not think of a better solution fo inserting new values with multiple instances on a page.

**Comment by mattelen** [comment]
Hi @pitylee thanks for creating an issue, however without seeing code or providing something like a jsfiddle, we can't figure out what could be going on. I'm going to close this issue, but in the meantime feel free to create a jsfiddle that demonstrates the issue you have, and pop it back in here. We can then have a look. A great start is using this:   https://jsfiddle.net/shentao/jqofkzxc/3296/.
Thanks
