### ISSUE TITLE
Multiselect without tags?

### ISSUE THREAD

**Issue by gotters** [shentao/vue-multiselect#1450]
Trying to use the selected slot as per the examples but its not working.
I am using the component via the CDN. It is operating as expected aside from this. Instead of showing a count for the number of options selected its just showing the selected tags (as per default)

**Comment by rrpatricio** [comment]
Hi,

I did something like this:

   ```
   <template v-if="multiple && withoutTags"  v-slot:selection="{ values }">
      <div v-if="values.length" class="multiselect__single">
        <span>{{ values.length }} {{ values.length === 1 ? 'option selected' : 'options selected ' }}</span>
      </div>
    </template>
```

That "withoutTags" is a prop I created to pass to the component when, well, I don't want to show the tags. But you don't need to use that 'v-if="multiple && withoutTags"'.

**Comment by gotters** [comment]
Thanks for sending that. I must be doing something obviously wrong as its still not working for me. I still see the tags. I removed your v-if completely and still does nothing. This is my code

```
<multiselect v-if="allAssetTypes" v-model="searcharr.AssetType" :close-on-select="false" :clear-on-select="false" :disabled="!properties.$resolved"  :options="allAssetTypes" :multiple="true">
                            <template v-slot:selection="{ values }">
                                <div v-if="values.length" class="multiselect__single">
                                    <span>{{ values.length }} {{ values.length === 1 ? 'option selected' : 'options selected ' }}</span>
                                </div>
                            </template>
                        </multiselect>
```

**Comment by rrpatricio** [comment]
Are you using vue 3? Sorry I am using, so I assumed you too. If you on vue 2, you can try this:

```
<multiselect v-if="allAssetTypes" v-model="searcharr.AssetType" :close-on-select="false" :clear-on-select="false" :disabled="!properties.$resolved"  :options="allAssetTypes" :multiple="true">
                            <template slot="selection" slot-scope="{ values }">
                                <div v-if="values.length" class="multiselect__single">
                                    <span>{{ values.length }} {{ values.length === 1 ? 'option selected' : 'options selected ' }}</span>
                                </div>
                            </template>
                        </multiselect>
```

But I dont know if it is related to some specific problem on the vue 2 version, though.

**Comment by gotters** [comment]
Yes I am using Vue 2 not Vue 3. I tried what you sent but that also didnt work.
I am using the min.js build file from the CDN and not using an npm install. Maybe thats an old version?

**Comment by gotters** [comment]
I believe the CDN link was the problem. I took the one being used in the fiddle attached to this project and its working. Thanks for your help!
