### ISSUE TITLE
vue3 slot option

### ISSUE THREAD

**Issue by Giovanni-Petrella** [shentao/vue-multiselect#1451]
If i try it:     
`    <template slot="option" slot-scope="props"><div class="option__desc">sono qua<span class="option__title">{{ props.option.label }}</span></div>
    </template>`

nothing display on option what's need?

**Comment by rrpatricio** [comment]
Hi,
I did something like this:

<template v-slot:option="{ option }">
      <div class="option__desc">
          sono qua <span class="option__title">{{ option.label }}</span>
      </div>
    </template>

**Comment by Giovanni-Petrella** [comment]
thanks i still don't understand the syntax for vue 3 slots
