### ISSUE TITLE
Aria error on autocomplete value

### ISSUE THREAD

**Issue by GregorioF2** [shentao/vue-multiselect#1454]
Hi, i am trying to support aria rules on my webpage, and with the multi select component im having an issue that says `Autocomplete attribute must be used correctly`.
This is because on the `input` element of the autocomplete component like i can show here

![Screenshot from 2021-06-30 09-28-01](https://user-images.githubusercontent.com/21204940/123960571-d3124600-d985-11eb-98e7-b43e0888caa9.png)

The value for `autocomplete` is `nope`, that well is not valid... The list of valid values for autocomplete is here https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#values. I suggest using `off`

**Comment by mattelen** [comment]
This has been fixed on the project, just waiting for a version release from @shentao. I'm going to close this, as #1518 is open and requesting that
