### ISSUE TITLE
Pressing ESC a second time after deactivate() eats up ESC without doing anything

### ISSUE THREAD

**Issue by bryanluu** [shentao/vue-multiselect#1456]
In the Multiselect Mixin code, [deactivate()](https://github.com/shentao/vue-multiselect/blob/3517065e3714c6b20438c5bb77d3c6f5ebd012ca/src/multiselectMixin.js#L670-L683) is called when ESC key is pressed (see [Multiselect.vue](https://github.com/shentao/vue-multiselect/blob/3517065e3714c6b20438c5bb77d3c6f5ebd012ca/src/Multiselect.vue#L10)) the first time, but not the second time. 

- **The behaviour encountered:** once the Multiselect is deactivated (by pressing ESC once), the ESC key is no longer listened to, the ESC key event cannot be listened to by parent elements. 
- **The expected behaviour:** once Multiselect is deactivated (by a single ESC key press), any subsequent ESC key presses should be propagated without affecting the Multiselect.

**Comment by akki-jat** [comment]
@bryanluu Please provide reproduction link

**Comment by akki-jat** [comment]
@bryanluu Ok . I will try to replicate it. Thanks.

**Comment by akki-jat** [comment]
Not able to replicate this.
