### ISSUE TITLE
List shows "Selected" by every item.

### ISSUE THREAD

**Issue by airliajsmith** [shentao/vue-multiselect#1463]
I love using this. I just need some guidance on one issue.

1. I click on the dropdown and select an item.
2. When I click on the dropdown again so that I can choose a different item, it shows the word "Selected" by every single item.

Here is my code:

`                                           <multiselect
                                                    @input="loadOptions(secondaryCategory)"
                                                    v-model="secondaryCategory"
                                                    track-by="secondaryCategory"
                                                    :searchable="true"
                                                    :multiple="false"
                                                    :options="secondaryCategories"
                                                    label="name"
                                                ></multiselect>
`

**Comment by Lukydemboy** [comment]
Make sure your options contain different ids, so it can differentiate the different items.

An example of an option object could look like this:

```
{
     id: 1,
     name: 'John',
}
```

Note that you are now tracking the options by 'secondaryCategory', so all the options that have the same 'secondCategory' as the selected option will be selected. You should change this to an unique item in the options list. In the case of the example in this comment this would be `track-by="id"`.

**Comment by airliajsmith** [comment]
Using id in the track-by worked. Thanks!!
