### ISSUE TITLE
Provide option to denote readonly on input / disable mobile keyboard (Feature request)

### ISSUE THREAD

**Issue by CosyStudios** [shentao/vue-multiselect#1467]
Clicking on the select element on a mobile activates the mobile keyboard.
However, this gets in the way of the select list itself and I would prefer to make the text search available via an  input box hosted somewhere in one of the slots so that it is optional.
As I understand, the mobile keyboard is commonly disabled by the 'readonly' attribute on the input element, which can then be removed when the intention to search is actively asked for. 

As an example usecase of such functionality - heres a little gin picker ive been sketching out : 
[https://codesandbox.io/s/picker-attempt-2-forked-wmhsi](url)

It uses both text search as well as an internal tag search system for ease of use which should be the main focus over advanced filtering done by text search.. particularly on mobile. 
Whilst ive mucked about with the display as a fixed overlay, i belive this would also apply to cases where the select options are the default dropdown style.

**Comment by CosyStudios** [comment]
I should probably add of the reason i cite more fine grain control is also the fact, it makes sense for the keyboard to appear on first focus to highlight it, but once you close it down, every time you select/deselect an option or im in my case also use a predefined tag filter, the select element is repeatdly reset "in focus" and the keyboard keeps popping up on every selection. 
Ideally, it would appear on first focus and then remain silent during the usage of the selection.... particularly since the primary purpose is a select box and not a search.

**Comment by CosyStudios** [comment]
Part way to making this work acceptably on mobile..
Setting searchable to false does of course remove the input element and thus not enable the mobile keyboard on focus.

In my circumstance, ive added a fresh input element in the beforeList section with a view this could be a selectable text search area, but not one that activates keyboard focus every time you touch anything within the select component
Only trouble is the existing activate() function, forces focus on the select element whenever you try to touch my self created input element. 

Seems to be the same side of the coin whichever way you configure it....
` if (this.searchable) {
        if (!this.preserveSearch) this.search = ''
        this.$nextTick(() => this.$refs.search && this.$refs.search.focus())
      } else {
        this.$el.focus()
      }`

... If (searchable) => focus on the input and bring up the mobile keyboard > which gets in the way every time you try to do something
else => force focus on the main element not allowing focus on any other ui element inside the select. 

perhaps a disable focussing option could be added ?
wondering if it could work to attach a click handler to a manually created input element inside the select, wait for the "next tick" or some small timeout and then put that into focus after this.$el.focus() has happened?

Bit hacky but ill give it a try..

**Comment by johnson0903** [comment]
Hi, the feature of this pull request is not on npm yet on version 3.0.0-alpha.2 . [https://www.npmjs.com/package/vue-multiselect/v/3.0.0-alpha.2?activeTab=explore](url)

Any help?
