### ISSUE TITLE
Problem on tags after creating a new one

### ISSUE THREAD

**Issue by luismabenitez** [shentao/vue-multiselect#1473]
When creating a new tag in a single select, the first option i get is to deselect the new option "Press enter to remove". So the user needs to click twice to make it selected.

Using with Vue 3.

`        
<VueMultiselect
            :options="options"
            track-by="id"
            label="name"
            tag-placeholder="Add new item"
            :multiple="false"
            :taggable="true"
            :loading="isLoading"
            :searchable="true"
            :preserveSearch="true"
            @tag="addItem"
            @search-change="getItems"
            @select="selectDog"
            v-model="selected"
            :disabled="!breed"
            :clear-on-select="false"
        />
`

<img width="617" alt="Captura de pantalla 2021-08-14 a las 15 27 17" src="https://user-images.githubusercontent.com/5616886/129447889-ac467fa9-8e52-4aaf-bc21-fb90e8565b8e.png">

I think the expected behavior should to be to select that item we are creating. isn't it?

**Comment by lehoaibaokg** [comment]
You can try to set the v-model on the addItem method. When pressing enter to create a new tag, it will be selected automatically.

**Comment by akki-jat** [comment]
@luismabenitez - Please provide reproduction link.
