### ISSUE TITLE
Version 3: TypeScript types are missing

### ISSUE THREAD

**Issue by daviddelusenet** [shentao/vue-multiselect#1475]
When installing the `next` branch there are no TypeScript types included. Will these be added in the (near) future?

**Comment by mattelen** [comment]
I'll jump onto this and migrate the existing TS types over

**Comment by louisjeck** [comment]
Any news on this ?

**Comment by paullegrand** [comment]
@mattelen has there been any talk about migrating the project to use TS, so it would include definitions natively? If you'd like any help as well, let me know 😄  Would love to see the TS definitions for this project

**Comment by diegocl02** [comment]
Hey any news on this?

**Comment by milosztisagroup** [comment]
Can you include types, please?

**Comment by maxism** [comment]
Guys, any updates here?

**Comment by mewforest** [comment]
Waiting for a type definition for v3 too.

**Comment by Leonidas777** [comment]
Also interested🙂

**Comment by mewforest** [comment]
I also recommend this library for all who want to use multiselect field in Vue 3: https://github.com/vueform/multiselect. 
It suports TypeScript and has a great possibilities.

**Comment by mattelen** [comment]
Type definitions now exist in 3.0.0-beta.1. This version can be installed with the `next` tag. I've tested it and it seems to be work well for me, but please let us know if this isn't working for you
