### ISSUE TITLE
Is this package still being maintained?

### ISSUE THREAD

**Issue by daviddelusenet** [shentao/vue-multiselect#1476]
270 open issues at the moment of writing, 58 open pull requests, (almost) all of them get zero response whatsoever. Last release is over two years (!) ago.

@shentao nothing personal against you (great work so far on this library!) but shouldn't you be looking for other people who still can/want to maintain this project?

Let me know if you need any help.

**Comment by shentao** [comment]
Hey! That's true, it is not actively developed. There's been a Vue 3 compatible release a while ago thanks to @mattelen.

I could in fact look for some help maintaining it, but sadly most people don't stick around. And my low involvement probably isn't helping. Fixing issues, reviewing PRs is far from exciting. Especially when you see hundreds of them – it can be overwhelming. 

As for the component API, I don't think it needs any new major features, except for a11y improvements. There's a v3 branch that you can take a look at where I experimented with a rewrite a long while ago, but hit a block with a11y. There's a branch with those changes too under a11y-improvements. 

If you (or someone reading this) are interested in helping out - let me know.

**Comment by mattelen** [comment]
Hi @daviddelusenet. I'm still around and enjoy when I can working on this. I've been focused on maintaining the current v3 alpha version, but I'm quite keen to help get something to v3 stable

**Comment by vesper8** [comment]
@mattelen Tomorrow marks the 1 year anniversary of the 3.0.0-alpha.1 release. Is there any chance you will tag a new release.. a beta or release candidate or final 3.0?

Many thanks!

**Comment by mattelen** [comment]
Hi all. You'll be pleased to hear that this package/project is still being actively maintained, and we are working towards multiple releases. You can see a project update here: https://github.com/shentao/vue-multiselect/discussions/1589
