### ISSUE TITLE
github repo could not resolve dependency if forced or legacy unit tests wont work

### ISSUE THREAD

**Issue by code1x1** [shentao/vue-multiselect#1477]
### Reproduction Link

https://github.com/shentao/vue-multiselect/commit/904d10fb1ba92ae9656cd1e569e539e775be3614

### Steps to reproduce

clone repo
checkout tag 2.1.6
npm install

### Expected behaviour

install node modules

### Actual behaviour

vue-multiselect on  tags/2.1.5 [$?] is 📦 v2.1.6 via ⬢ v14.16.0 
➜ npm install                   
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: vue-multiselect@2.1.6
npm ERR! Found: babel-core@7.0.0-bridge.0
npm ERR! node_modules/babel-core
npm ERR!   dev babel-core@"^7.0.0-0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer babel-core@"^6.0.0" from babel-loader@6.4.1
npm ERR! node_modules/babel-loader
npm ERR!   dev babel-loader@"^6.2.10" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/dbehrends/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dbehrends/.npm/_logs/2021-09-14T07_37_36_969Z-debug.log

**Comment by mattelen** [comment]
Hi @code1x1. I'm a bit unsure on what you are trying to achieve here by checking out an old commit. I also couldn't replicate your issue. I'm going to close the issue for now, but if you can provide more details on what you are trying to achieve, we might be able to re-open this and figure out what is going on
