### ISSUE TITLE
Using slots with Multiselect & Vue 3

### ISSUE THREAD

**Issue by TheAustinG** [shentao/vue-multiselect#1481]
We have updated our project to use Vue 3 and as I'm going through and updating all of our vue components, I ran into an issue with multiselect because of how slots were changed in Vue 3.

In Vue 2 I used the single label slot like this:
`<template slot="singleLabel" slot-scope="{ option }">You selected <strong>{{ option.Name }}</strong></template>
`

I tried updating in Vue 3 to the following but obviously it's not right because it's not working. The new slot syntax for Vue 3 still confuses me so I'm probably just doing it wrong.
`<template v-slot:singleLabel="{ option }">You selected <strong>{{ option.Name }}</strong></template>`

Any help or guidance would be appreciated!

**Comment by mattelen** [comment]
Hi @TheAustinG. I believe you are on the right track with using scope. I've just created a quick project and tried it out with your Vue 3 sample code, and it seems to do the trick:
https://github.com/mattelen/vue3-multiselect-slots/blob/master/src/App.vue

Maybe have a look at the connecting components and make sure props/v-models are passing back and forth correctly. Sorry I can't be more helpful than that

**Comment by AlguerGalceran** [comment]
I'm interested to know if you solved the problem somehow. I have similar problem and I found out that is due the camelCase slot names. 
If is that I'll publish a new issue with the finding and see if the slots can be renamed to not be camelCase.
