### ISSUE TITLE
Enter does not de-select current selection

### ISSUE THREAD

**Issue by jcrawfordnexant** [shentao/vue-multiselect#1482]
I have found when using this component everything seems to work based upon selections except for when I want to remove the item from being selected.  I am not allowing multiple selections but when a single item is listed in the drop down and I expand the contents it says hit enter to remove, however hitting enter does not remove the selection.

Is it possible to remove the selected item when I am using the select for a single value and not using muliple?

I have googled and found that due to using Objects the track_by has to be in place for the component to know which one you are de-selecting and I have verified that all 4 of my drop downs have this attribute but NONE of them will allow me to deselect the selection value.

![image](https://user-images.githubusercontent.com/83981713/133850887-60f7f926-ca67-4395-a48a-e935527db7d1.png)
![image](https://user-images.githubusercontent.com/83981713/133850979-a364bbb6-3420-4874-8af4-0d13d7d311e0.png)
![image](https://user-images.githubusercontent.com/83981713/133850944-1ce041e1-6da9-46da-b071-598fb535b436.png)

The above images show the select element where it says I can hit enter to remove and the other two images are the props passed down to the MultiSelect component.

I have even tried to see if `close-on-select` was set to false if it would work and it does not.  I have compared my props to the props on your example page for the first example which works but the props look to be the same.  The only difference is that your example is using an array of strings for options and mine is using an array of objects. 

I have also added multiple elements to it and checked if i arrow to the next and hit enter the selection changes, it just does not de-select the already selected option when selected and enter is hit on the keyboard.

**Comment by iKlsR** [comment]
@jcrawfordnexant What was the issue? Having this as well
