### ISSUE TITLE
importing from dist folder gives error

### ISSUE THREAD

**Issue by excellent-coder** [shentao/vue-multiselect#1491]
Trying to import the package using npm while developing locally, imports the package from ``` dist/vue-multiselect.min.js```  but this gives an error and crashes the application. changing the ```main``` in package.json to ```src/index.js``` solves this issue.

This issue is happening on ``` version 2.1.6 ```

**Comment by akki-jat** [comment]
@excellent-coder - Please provide reproducible repo.
