### ISSUE TITLE
Style using CSS variable

### ISSUE THREAD

**Issue by mrleblanc101** [shentao/vue-multiselect#1493]
Style should use CSS variable so we can easily change the green accent for another background-color.
Same could be said for the text color and the red used to remove a tag.

**Comment by kraxner** [comment]
you could override the default styles.
It is not straight forward to see what classes have to be defined, but you can use your own naming convention.
We did something like:

`.multiselect,
.multiselect__single,
input#activitySel.multiselect__input,
input#locationSel,
.multiselect__tags,
.multiselect--active {
  background-color: var(--clr-secondary-light); 
  border: none;
  height: inherit;
  box-shadow: none;
  margin-bottom: 0;
  margin-top: 0;
}
.multiselect__option--highlight,
.multiselect__option--highlight::after {
  background-color: var(--clr-primary-main);
}
`

**Comment by mattelen** [comment]
You can write your own CSS to override the CSS of the multiselect, and as a result, use CSS variables in your own CSS
There has been many discussions and chat about how best to change the styling of the mutltiselect, including in #287 - so I will close this issue as this is already requested

**Comment by mrleblanc101** [comment]
@mattelen I know it can override the style 🤦‍♂️ Thats exactly what I've done. But using CSS variable in the source code would allow me to change the primary color by overriding only one variable instead of multiple selector...

**Comment by mrleblanc101** [comment]
@shentao Can we revisit this ?
