### ISSUE TITLE
Option to add an x button to the deselect single selected tag?

### ISSUE THREAD

**Issue by thanhnambkhn** [shentao/vue-multiselect#1494]
Sometime the length of option string is long. So it is not easy to find "Deselect text" at the end of selected option.
Please add an x button to the deselect single selected tag at the right of input (such as multiple option).

**Comment by lehoaibaokg** [comment]
You can follow these steps:
- Use option slot for custom option template with label and x button on the same row
- On clicking the x button will call the function that removes the current option from the selected options
- Set deselectLabel prop to an empty string

**Comment by thanhnambkhn** [comment]
thanks @lehoaibaokg !
