### ISSUE TITLE
Default select value

### ISSUE THREAD

**Issue by robertowiest** [shentao/vue-multiselect#1495]
Hi, I have two selects that get data from the database. Data is loaded and displayed correctly. However, I would like that when getting this data from the database, a specific information is automatically selected when loading the multi-select. How can I do this? 

<multiselect
              id="field-planting_system"
              v-model="field.planting_system_id"
              :options="planting_systems"
              deselect-label=""
              select-label=""
              selected-label=""
              track-by="text"
              label="text"
              value="value"
              placeholder="Selecione"
              :searchable="true"
              :allow-empty="false"
              :disabled="mode === 'remove' || existFarmProperty || field.pousio"
            />

**Comment by akc4** [comment]
you have the `preselectFirst` prop or set your v-model to the value you want.

**Comment by WhereJuly** [comment]
If you use this multiselect with objects, then `v-model` value has to be of the same object format, used for `options` props, i.e. `{id: 123, title: 'title here'}`.

**Comment by lehoaibaokg** [comment]
You can use v-model to set the default selection you want. Or if you want to handle the input and output data, you should wrap the vue-multiselect into a component.

**Comment by mattelen** [comment]
As previously mentioned, setting the value of the v-model is a great way to automatically select a value in the multiselect.
