### ISSUE TITLE
Drop down is cut off in short modal window.

### ISSUE THREAD

**Issue by airliajsmith** [shentao/vue-multiselect#1496]
I have tried to set the overflow directly on the select, but no luck. A regular select field works so I know it's not the modal. 

Was this issue ever fixed?

Here is my code:

`                                            
<div
                                                class="input-group">

                                                <multiselect
                                                    v-model="order"
                                                    :options="orders"
                                                    style="overflow: visible!important;"
                                                    name="order"
                                                    :searchable="true"
                                                    track-by="id"
                                                    label="number">
                                                </multiselect>

                                            </div>
`

**Comment by lehoaibaokg** [comment]
You can follow these steps:
- Disable scrolling on the modal popup when opening dropdown, just enable scrolling if necessary
- Use openDirection prop with value "top"

**Comment by lehoaibaokg** [comment]
> I did try the openDirection with value of top, but that didn't work.

It means `open-direction="top"`. Did you use the correct structure?

**Comment by airliajsmith** [comment]
That works. Thanks!
