### ISSUE TITLE
Separate custom search field

### ISSUE THREAD

**Issue by handhikadj** [shentao/vue-multiselect#1502]
how do I create like this with this package:

![image](https://user-images.githubusercontent.com/22522638/143861989-054532bd-2cd1-488d-84df-76c2c38f46bc.png)

can't find it on the docs how to bind the custom input with the tag items

**Comment by lehoaibaokg** [comment]
You mean the dropdown and the search input is are separate, right?

**Comment by handhikadj** [comment]
yea

**Comment by lehoaibaokg** [comment]
I think you can follow these steps
- Use beforeList slot to show the selected options as tag element
- Use tag slot to hide current selected tags on search input `<template slot="tag" slot-scope="props"><span></span></template>`

**Comment by handhikadj** [comment]
ok thanks.
would be helpful if you create an example sandbox for it.

**Comment by lehoaibaokg** [comment]
I just did a basic as my comment above.
Quick implement, you can check https://jsfiddle.net/lehoaibaokg/wph43tb2/
