### ISSUE TITLE
showNoOptions , to hide options when empty, is not in the documentation

### ISSUE THREAD

**Issue by stouch** [shentao/vue-multiselect#1508]
### Reproduction Link

Look at https://vue-multiselect.js.org/#sub-props 

### Steps to reproduce

Just read at https://vue-multiselect.js.org/#sub-props 

### Expected behaviour

`showNoOptions` option exists, but it not in the props list.

### Actual behaviour

`showNoOptions` option exists, but it not in the props list.

**Comment by rosenfeldalon** [comment]
You have the **noOptions** slot; is that what you meant?
![Screen Shot 2022-03-31 at 11 02 18](https://user-images.githubusercontent.com/12997716/161007142-82b4c3b6-d2be-47f6-86c8-947d35bbc2f4.png)

**Comment by mattelen** [comment]
Thanks for creating an issue around this @stouch. I see there is a duplicate issue with #1136 so I'm going to close this, so we can fix it in that issue
