### ISSUE TITLE
[Asynchronous dropdown in multiselect seachable] Search input must be disabled while loading prop is true

### ISSUE THREAD

**Issue by giuseppareitano** [shentao/vue-multiselect#1509]
I'm using 3.0.0-alpha.2 version of vue-multisect for Vue 3.

<multiselect
    v-model="model"
    :options="options"
    :loading="isLoading"
    :internalSearch="false"
    :preserveSearch="true"
    :clearOnSelect="true"
    :closeOnSelect="true"
    @search-change="onChange"
    @select="onSelect"
  />

OnChange method make an API call during which isLoading is True. Is there the possibility to temporarily disable input search?

**Comment by mattelen** [comment]
Hi @giuseppareitano thanks for creating an issue. Are you able to create a reproducible repo so we can see and demo the issue you have?
