### ISSUE TITLE
Feature request: incompatible options in multiple select

### ISSUE THREAD

**Issue by xegulon** [shentao/vue-multiselect#1512]
It would be great to have a way to automatically unselect some options in the multiple select, when a new value is selected an is not compatible with some others.

One would specify an array of length-2 objects which would represent the incompatible options :
```js
incompatibleOptions = [ {option: "hi", incompatibles: ['hola', 'ho']}, {option: "me", incompatibles: ['hi', 'hola']} ]
```

**Comment by akki-jat** [comment]
@xegulon - Please manually update the options based on the selection you get from select / input event.
