### ISSUE TITLE
How to update the hover background color of the multi-select?

### ISSUE THREAD

**Issue by romain130492** [shentao/vue-multiselect#1513]
Just wondering, How to update the hover background color of the multi-select?
i dont see any props? 
thanks

**Comment by lehoaibaokg** [comment]
You can do it through custom CSS style. Just update the background color for each class below:
`.multiselect__option--highlight` the background color for the hovered option
`.multiselect__option--highlight:after` the background color for the selectLabel prop value beside the hovered option value

**Comment by mattelen** [comment]
Hi @romain130492. Like what @lehoaibaokg has mentioned, you can create your own CSS queries to customise the design of the multiselect based off the classes of the component.
Hope that helps.
