### ISSUE TITLE
Problem with testing close dropdown method

### ISSUE THREAD

**Issue by fisherspoon** [shentao/vue-multiselect#1520]
Hi I'm using jest to test a vue app and the tests are complaining about the method to close the dropdown. I try used `this.$refs.multiselectInstitutes.deactivate()` or `this.$refs.multiselectInstitutes.toggle()` but I get the same error.

```jsx
<button class="btn-unselect-all small-button" type="button" @click="cleanSelect">{{ $t("students.clear") }}</button>

cleanSelect: function (){
      this.$emit('cleanSelectInstitutes', [])
      this.$refs.multiselectInstitutes.deactivate();
    },
`

and test
   test('check clear select', async () => {
        let btnClearSelect = wrapper.find('.btn-unselect-all')
        await btnClearSelect.trigger('click')
        expect(wrapper.emitted().cleanSelectInstitutes[0]).toEqual([[]])
    })



Error when I run test
console.error
      [Vue warn]: Error in v-on handler: "TypeError: this.$refs.multiselectInstitutes.deactivate is not a function"

**Comment by mattelen** [comment]
Hi @fisherspoon. Its a bit hard to help troubleshoot without seeing the full code, like how you've setup the ref, as it might be setup incorrectly. I've just created a quick button that toggles, and it works well for me here - https://jsfiddle.net/mattelen/5f1n0mkc/10/
I understand that this isn't with Jest, but if this is working well in a browser, but not in Jest, then the issue might be in Jest. 
Hope that helps. As there isn't anything more we can help with, I'm going to close this issue
