### ISSUE TITLE
Is it possible to make the input field save or change its value to the selected option?

### ISSUE THREAD

**Issue by Pro100Nekit** [shentao/vue-multiselect#1525]
Hello,

I know that it is possible to save the value of user input by :preserve Search = "true"
But I need to be able to edit the value of the previously selected option in the input field when re-editing.

It is possible?

**Comment by mattelen** [comment]
Hi @Pro100Nekit

So, in other words, you are wanting to change something in the options object provided to the component based on the user's previous selection? 
If you are wanting to achieve this, you'll need to do some manipulation of the options object before it gets passed to the multiselect, as the multiselect doesn't change the options that it gets provided. You may also want to use some watches on the value passed to the v-model of the mulitselect so you can fire a method when the value changes. 
To help with figuring out what you could do, I recommend checking out how tagging works with our component, as this includes an example of changing the options object: https://vue-multiselect.js.org/#sub-tagging

Hope this helps
