### ISSUE TITLE
I can't add my own styling and I can't add a ref either.

### ISSUE THREAD

**Issue by marcio1002** [shentao/vue-multiselect#1528]
The component is not flexible in terms of styling the child elements within the multiselect, there is no way to style it at all.

**Comment by mattelen** [comment]
With the styling, you can customise with your own CSS - either by overriding the current CSS, or copying the CSS stylesheet into your own app and making customisation there. 

There are other issues open about how this can be done better, so I'm going to close this issue, but if something doesn't make sense feel free to ask more questions
