### ISSUE TITLE
Multiselect in v-for

### ISSUE THREAD

**Issue by noxsii** [shentao/vue-multiselect#1531]
Hi everyone,
i use vue3... i have a probleme with the multiselect:

```
<div v-for="(test, index) in article" :key="index">
<VueMultiselect
                                                v-model="selected_receipt_article[index]"
                                                :options="options_receipt_article"
                                                class="shadow my-3">
                                            </VueMultiselect>
</div>
```

i get the error **Cannot create property '0' on string ''**
does anyone have a solution?

**Comment by mattelen** [comment]
Hi There. Are you able to provide more of your code, or a repo that shows this error? There could be many reasons why this isn't working, including what is `options_receipt_article` and `selected_receipt_article`. 

I'm going to close this issue, but feel free to re-open it with some more code
