### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_c')

### ISSUE THREAD

**Issue by mauriciolanner** [shentao/vue-multiselect#1533]
I installed vue-multiselect on Laravel 9 with jetsetram, using vue 3.2.31. It is returning the following error in the console.

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c')
     at Proxy.i (app.js:63806:38299)
     at renderComponentRoot(app.js:9876:44)
     at ReactiveEffect.componentUpdateFn [as fn] (app.js:13993:57)
     at ReactiveEffect.run (app.js:16902:25)
     at setupRenderEffect (app.js:14119:9)
     at mountComponent(app.js:13902:9)
     at processComponent(app.js:13860:17)
     at patch (app.js:13461:21)
     at mountChildren(app.js:13648:13)
     at mountElement (app.js:13557:17)

------------------------

my code: 
data() {
    return {
      providersTes: [
        "Select option",
        "options",
        "selected",
        "mulitple",
        "label",
        "searchable",
        "clearOnSelect",
        "hideSelected",
        "maxHeight",
        "allowEmpty",
        "showLabels",
        "onChange",
        "touched",
      ],
      value: null,

-----------------------------------------------

<vue-multiselect
          v-model="value"
          :options="providersTes"
        ></vue-multiselect>

**Comment by wgeronimor** [comment]
Hi @shentao, im experiencing the same issue, im just imported the component in a new vue project, and I just have this component installed. I have the same error.

Im attaching Package.json... for your acknowledge.

{
  "name": "vue-project",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite --port 3033",
    "build": "vite build",
    "preview": "vite preview --port 4173",
    "lint": "eslint . --ext .vue,.js,.jsx,.cjs,.mjs --fix --ignore-path .gitignore"
  },
  "dependencies": {
    "vue": "^3.2.36",
    "vue-multiselect": "^2.1.6",
    "vue-router": "^4.0.15"
  },
  "devDependencies": {
    "@rushstack/eslint-patch": "^1.1.0",
    "@vitejs/plugin-vue": "^2.3.3",
    "@vue/eslint-config-prettier": "^7.0.0",
    "eslint": "^8.5.0",
    "eslint-plugin-vue": "^8.2.0",
    "prettier": "^2.5.1",
    "vite": "^2.9.9"
  }
}

**Comment by dennisego1999** [comment]
Are you using  "vue-multiselect": "^3.0.0-alpha.2"? That version works for me

**Comment by massiws** [comment]
@wgeronimor , in your package.json I see this:
```    
    "vue": "^3.2.36",
    "vue-multiselect": "^2.1.6",
```
Change like this:
```
    "vue": "^3.2.36",
    "vue-multiselect": "^3.0.0-alpha.2",
```
then run `yarn` (or `npm install`)

Max.

**Comment by wgeronimor** [comment]
Thanks so much! Ill test and let you know.

**Comment by jackstruck** [comment]
Can confirm that installing ^3.0.0-alpha.2 resolves the issue but worth noting that the issue exists upon installation following the directions at https://vue-multiselect.js.org/#sub-getting-started and simply running "npm install vue-multiselect --save" without specifying the alpha version installs the broken version.

**Comment by mauriciolanner** [comment]
Thanks guys

**Comment by kinger251285** [comment]
This is still broken for me even after following the instructions from @massiws & @mattelen. Fresh install today.

**Comment by geosemaan** [comment]
> This is still broken for me even after following the instructions from @massiws & @mattelen. Fresh install today.

Me too

**Comment by dangngocbinh** [comment]
Just remove node_modules/.vite folder.
And run yarn dev
I work for me!

**Comment by AzilYahia** [comment]
> @wgeronimor , in your package.json I see this:
> 
> ```
>     "vue": "^3.2.36",
>     "vue-multiselect": "^2.1.6",
> ```
> 
> Change like this:
> 
> ```
>     "vue": "^3.2.36",
>     "vue-multiselect": "^3.0.0-alpha.2",
> ```
> 
> then run `yarn` (or `npm install`)
> 
> Max.

works like chram! thank you

**Comment by emildobber** [comment]
This issue is still occurring for me, even with 3.0.0-beta.2 and even with 3.0.0-alpha.2

**Comment by mattelen** [comment]
I haven't seen this issue occuring, so if this is happening for anyone please create a new issue with a reproduction link. TIA

**Comment by shtse8** [comment]
I fixed this issue by `npm install vue-multiselect@next`
