### ISSUE TITLE
dynamic dropdown for spesific address

### ISSUE THREAD

**Issue by dikdikmusfarp** [shentao/vue-multiselect#1537]
Hello!

For example, I have country and city data, 
in the country there are: id, name. 
Then in the city there are: id, name, country_id. 
how do i make the dropdown dynamic when i select a country with id=1 it will bring up the city city with country_id =1

<multiselect v-model="form.country" 
                  :options="countries.map(type => type.id)"
                  placeholder="Choose country"
                  :custom-label="opt=>countries.find(x=>x.id==opt).name">
</multiselect>

<multiselect v-model="form.city" 
                  :options="cities.map(type => type.id)"
                  placeholder="Choose country"
                  :custom-label="opt=>cities.find(x=>x.id==opt).name">
</multiselect>

Thankyou

**Comment by dikdikmusfarp** [comment]
`<multiselect v-model="form.contry" 
                  :options="countries.map(type => type.id)"
                  placeholder="Choose country"
                  :custom-label="opt=>countries.find(x=>x.id==opt).name">
  </multiselect>`

`<multiselect v-model="form.city" 
                  :options="cities.map(type => type.id)"
                  placeholder="Choose city"
                  :custom-label="opt=>cities.find(x=>x.id==opt).name">
  </multiselect>`

**Comment by mattelen** [comment]
Hi there

To achieve this, in your city select, you would filter your options based `form.country`. For example, you could have a Vue Computed Property that filters your cities based on your form.country selection. Then, in your options prop of your city selector, you can pass the computed property.

Hope this helps
