### ISSUE TITLE
'next' (vue 3) version misses fixes from v2

### ISSUE THREAD

**Issue by mariusa** [shentao/vue-multiselect#1545]
### Reproduction Link
eg v2 includes `id` in events:
https://github.com/shentao/vue-multiselect/blob/731be35ca4172995d85524f18cbb5441e57734e4/src/multiselectMixin.js#L397
vs
https://github.com/shentao/vue-multiselect/blob/5ed71c107e3d9477e8d5a30c5b6556d228492eac/src/multiselectMixin.js#L389

**Comment by runxc1** [comment]
Curious if anyone has merged in the changes from vue2 yet?    I am running into an odd issue that is only affecting one of many deployments and I am running the alpha.2 release and wondering if there will be another release

**Comment by mattelen** [comment]
A new version with the latest patches from V2 has just been published on the `next` release
