### ISSUE TITLE
Dropdown

### ISSUE THREAD

**Issue by oudd1** [shentao/vue-multiselect#1549]
There is something wrong with my multiselect. 

After I linked my API into multiselect, when I open the dropdown all the data is already selected and cant even clicked the datas.
![dropdown](https://user-images.githubusercontent.com/115195634/194444881-808c6537-ff4c-4042-9c69-a713d08fb45f.png)

**Comment by oudd1** [comment]
I Fixed it!

**Comment by Jonatanc05** [comment]
How did you solve? I can't figure out what I'm doing wrong. Exact same problem on this usage:

```html
<MultiSelect :options="[{composicao: 'fck 89'},{composicao: 'fck 86'},{composicao: 'fck 84'}]"
    track-by="composicao" label="composicao" />
```
