### ISSUE TITLE
Value can be set to option which not exist

### ISSUE THREAD

**Issue by dkwebtec** [shentao/vue-multiselect#1622]
`          <VueMultiselect id="form-mkt" v-model="filter.mkt" :show-labels="false" :options="md.market.map(({ name }) => name)" />`

I can set a value into filter,mkt which is not in options and it shows a pill with it. Component is not taggable.

**Comment by akki-jat** [comment]
@dkwebtec Why you are adding the value which is not available in options. If you are adding it manually then you should first check if that value is available in options or not.

**Comment by dkwebtec** [comment]
because the options are filtered by other dropdown. 

md.market is changed by other dropdown but the filter.mkt stays set and some of these values are not in options anymore

**Comment by akki-jat** [comment]
> because the options are filtered by other dropdown. 
> 
> md.market is changed by other dropdown but the filter.mkt stays set and some of these values are not in options anymore

When md.market changes the reevaluate filter.mkt to remove any selection which is not in options anymore.

To do this you can use select event.

**Comment by akki-jat** [comment]
@dkwebtec Please reopen the issue again if still any concern for the same.
