### ISSUE TITLE
[Feature request] Multi select of the same item

### ISSUE THREAD

**Issue by dawadam** [shentao/vue-multiselect#1641]
Hi thanks for this work.

I need to have a multi selection of a same item, like this :

```
[
  {
    "name": "Vue.js",
    "language": "JavaScript"
  },
  {
    "name": "Adonis",
    "language": "JavaScript"
  },
  {
    "name": "Adonis",
    "language": "JavaScript"
  },
  {
    "name": "Adonis",
    "language": "JavaScript"
  }
]
```

Is it possible to add this feature ?

**Comment by akki-jat** [comment]
@dawadam We need to have one unique property to identify the item. Please take a hook at https://codesandbox.io/s/vue-multiselect-multiselect-same-item-ufd80e

**Comment by dawadam** [comment]
Ok, so it's impossible to add an indefinite number of identical objects.
