### ISSUE TITLE
deprecation WATCH_ARRAY

### ISSUE THREAD

**Issue by talaxasy** [shentao/vue-multiselect#1648]
![image](https://user-images.githubusercontent.com/25802675/212497477-0bfd0d32-0a9d-40f6-84ef-3425d0c392cb.png)

I use @vue/compat to migrate from vue 2 to vue 3.
Compat indicates that property 'options' in VueMultiselect component  in watch-effect no deep marker

**Comment by akki-jat** [comment]
@talaxasy Is this happening for vue-multiselect 2.x or 3.x?

**Comment by talaxasy** [comment]
@akki-jat  vue-multiselect 3

**Comment by akki-jat** [comment]
@talaxasy Please provide reproducible link.

**Comment by jkocyigi** [comment]
@akki-jat Created a sandbox for you

https://codesandbox.io/p/sandbox/spring-rgb-wr6gzw?file=%2Fsrc%2Fmain.js&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A14%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A14%7D%5D

**Comment by carvemerson** [comment]
Same issue here. A lot of warnings.
Do you have any plans to deploy a stable version os this component that is compatible with vue3?

**Comment by mattelen** [comment]
Fixed and launched on v3.0.0-beta.2

**Comment by mattelen** [comment]
> Same issue here. A lot of warnings. Do you have any plans to deploy a stable version os this component that is compatible with vue3?

Check out https://github.com/shentao/vue-multiselect/discussions/1589
