### ISSUE TITLE
Options and tags not displaying in input and dropdown with Vue 3 migration build

### ISSUE THREAD

**Issue by giloliveira-nmi** [shentao/vue-multiselect#1652]
Starting with v2.1.7, options and tags don't seem to display when using the Vue 3 migration build.

### Steps to reproduce
1. Use Vue's [migration guide](https://v3-migration.vuejs.org/migration-build.html) to setup a migration build. In short; install `"vue": "^3.1.0"`, `"@vue/compat": "^3.1.0"` and `"@vue/compiler-sfc": "^3.1.0"` and update `vue.config.js` with the following code:
```js
// vue.config.js
module.exports = {
  chainWebpack: (config) => {
    config.resolve.alias.set('vue', '@vue/compat')

    config.module
      .rule('vue')
      .use('vue-loader')
      .tap((options) => {
        return {
          ...options,
          compilerOptions: {
            compatConfig: {
              MODE: 3
            }
          }
        }
      })
  }
}
```
2. Install `"vue-multiselect": "2.1.7"`

### Expected behaviour
Multiselect input with options and tags being displayed

### Actual behaviour
Tags and options are not displaying (labels don't seem to be rendered), but aside from that it technically works.
<img width="612" alt="Screenshot 2023-01-26 at 12 32 20" src="https://user-images.githubusercontent.com/49279126/214877862-ff907659-8ff5-49bb-a34d-a11586df0d53.png">

**Comment by mattelen** [comment]
Hi there. Please install the Vue 3 compatible version by installing `vue-multiselect@next`.
For more info on versions and where the project is heading, please see the project plan at https://github.com/shentao/vue-multiselect/discussions/1589
