### ISSUE TITLE
very slow in vue 3 

### ISSUE THREAD

**Issue by hayrandere1** [shentao/vue-multiselect#1672]
Hi, 
I use a lot multiselect components in one page. When I did change event, the page waiting average 5 seconds. This is very slow for my project. If I dont use v-model, That running fast, but It dont save data. You writed to use :value but dont working it.  

Examples;
https://vue-multiselect.js.org/#sub-custom-configuration We only used :value, don't v-model but I don't working for vue 3 

My codes;

userRoles (  this have 100 parent and children )
[
   {
      "id":"x",
      "parent":null,
      "route_name":"roles.statisticRoles",
      "controller":"#",
      "action":"#",
      "model":null,
      "created_at":"2023-01-31T07:50:35.000000Z",
      "updated_at":"2023-01-31T07:50:35.000000Z",
      "children":[
         {
            "id":"x",
            "parent":1,
            "route_name":"user.statistics.queue_performance",
            "controller":"Statistic/QueueController",
            "action":"queue_performance",
            "model":"[\"queue\"]",
            "created_at":"2023-01-31T07:50:35.000000Z",
            "updated_at":"2023-01-31T07:50:35.000000Z"
         }
      ]
   }
]

 <div class="col-12" v-for="(role,key) in this.userRoles">
        <template v-for="model in JSON.parse(childRole.model)">
            <table class="table table-bordered table-hover m-0">
                <thead>
                <tr>
                    <th>{{ trans('user.user_role_group.form.table.extra') }}</th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="childRole in role['children']">
                    <td>
                        <multiselect
                            :id="'permission_values_'+childRole.id+'_'+model"
                            :name="'permission_values_'+childRole.id+'_'+model"
                            :options="this.values[model]"
                            :multiple="true"
                            placeholder="placeholder"
                            selectLabel="enterToSelect"
                            v-model="this.tempPermissionValues[childRole.id+'_'+model]"
                            label="number"
                            track-by="number"
                        >
                        </multiselect>
                    </td>
                </tr>
                </tbody>
            </table>
        </template>
    </div>

**Comment by mattelen** [comment]
Are you able to provide a link to a repo reproducing this issue? As you can imagine, there are many different variables that contribute to the performance on a webpage. If not using v-model makes your application run faster, then I wonder if its watchers or computed vars outside of the multiselect component that could be contributing. 

By putting the code in question it its own repo, this also help eliminates or proves different theories around what could be the issue of  the slow webpage. So if you could recreate this issue it its own git repo (not a code sandbox) and pop it in the chat, then we can investigate.
