### ISSUE TITLE
Warning with vue/compat: ATTR_ENUMERATED_COERCION

### ISSUE THREAD

**Issue by leitnermatias** [shentao/vue-multiselect#1677]
### Steps to reproduce
Using 3.0.0-beta.1 version while migrating a Vue 2 project to Vue 3 I get ATTR_ENUMERATED_COERCION warning.

### Expected behaviour
No warning should show up.
On file [Multiselect.vue](https://github.com/shentao/vue-multiselect/blob/master/src/Multiselect.vue) line 54 there is an attribute spellcheck="false" that might be what's causing the issue

### Actual behaviour
A warning ATTR_ENUMERATED_COERCION shows up

![imagen](https://user-images.githubusercontent.com/68134378/224345226-b0366c8b-78dc-4ad5-b6f3-5143fcf3918d.png)

**Comment by brnpimentel** [comment]
@mattelen i'm getting this in v3.0.0-beta.2.. Is it fixed?

**Comment by niksy** [comment]
Even though `compatConfig` is set, warning still shows up.

**Comment by brnpimentel** [comment]
Exactly. @mattelen please review https://github.com/shentao/vue-multiselect/pull/1708

**Comment by jpoiron** [comment]
I am also seeing this and I believe the fix in #1708 should do the trick. Thanks!

**Comment by nikkipelchat** [comment]
Just to add the version for anyone reading this thread - it is fixed in v3.0.0-beta.3
