### ISSUE TITLE
@input event doesn't work in vue-multiselect": "^3.0.0-beta.2. Could you please add this event for compatibility with multiselect v2.0

### ISSUE THREAD

**Issue by VladymyrKarpov** [shentao/vue-multiselect#1701]

**Comment by mattelen** [comment]
Can you explain why you would still need this in a Vue 3 application, considering a migration is required from `@input` to `update:modelValue` as part of any Vue 3 migration, regardless if we added this in or not?

**Comment by VladymyrKarpov** [comment]
Hello! It would be great to make it consistent with docs because at this point it is confusing. Documentation for v3.0.0 is the same as for v2.x as it is mostly backward compatible - and when you try use input event boom it just doesn't work. That is why if you can add that listener even if it duplicates the behaviour of update:modelValue would be super helpful. Thank you.

**Comment by ankurk91** [comment]
Please document this breaking change somewhere

**Comment by mattelen** [comment]
Updated https://github.com/shentao/vue-multiselect/blob/next/README.md. Thanks crew
