### ISSUE TITLE
Clicking outside doesn't close the dropdown in 3.0.0-beta.2

### ISSUE THREAD

**Issue by mkantautas** [shentao/vue-multiselect#1702]
version: ^3.0.0-beta.2
Clicking outside doesn't close the dropdown. 

Just pointing this issue out if it's not known so we have it patched in the actual release.

**Comment by ankurk91** [comment]
It is working fine for me with ` "vue-multiselect": "3.0.0-beta.2",`

**Comment by mattelen** [comment]
@mkantautas please provide a link where we can reproduce the issue. Thanks

**Comment by mkantautas** [comment]
Actually, it was a parent component(`vue3-drag-resize` ) bug/side effect - suppressing the click event. Without this parent component such problem doesn't occur.
