### ISSUE TITLE
Feature request I guess?

### ISSUE THREAD

**Issue by TheDeluxeThrowaway** [shentao/vue-multiselect#1704]
yeah apparently Tandoor uses this for their ingredients but it doesn't allow for text editing so I have to type in/scroll past 100's of ingredients to fix it and I was wondering when or even if it's ever going to be implemented

**Comment by mattelen** [comment]
This sounds like a feature request for Tandoor, rather than something we could implement. There are ways you can add in multiple items too, like using the tagging feature (https://vue-multiselect.js.org/#sub-tagging). I would recommend contacting them directly for a feature request

**Comment by TheDeluxeThrowaway** [comment]
![image](https://github.com/shentao/vue-multiselect/assets/134332457/c7c1bec6-3b2c-44d1-b245-f8e4bb3c7ef2)

**Comment by mattelen** [comment]
They can look at the tagging feature, but they would need to implement it: https://vue-multiselect.js.org/#sub-tagging

**Comment by TheDeluxeThrowaway** [comment]
@mattelen Any way to deal with empty lines? Like

This kind of empty line.
