### ISSUE TITLE
@tag event not working 

### ISSUE THREAD

**Issue by Avi9631** [shentao/vue-multiselect#1706]
Hi, @tag event is not working for Vue3 . vue-multiselect version -^3.0.0-beta.2

**Comment by syafiqmuda** [comment]
Hello I also have the same issue but I use in nuxt2,

![image](https://github.com/shentao/vue-multiselect/assets/80864791/59c3f32e-ed7a-4b18-98a9-0bfb94826bf5)

![image](https://github.com/shentao/vue-multiselect/assets/80864791/ce46d8d4-af3b-4cad-aad0-9f37f3bf92d9)

and it wont show in the console

**Comment by mattelen** [comment]
Need reproducible link
