### ISSUE TITLE
v-model returns null for options array of object data

### ISSUE THREAD

**Issue by aqordeon** [shentao/vue-multiselect#1711]
The documentation for this link is not work: https://vue-multiselect.js.org/#sub-single-select-object

I have followed the exact code but the result is not the same as what showed in the documentation. The v-model value always returns null data and all options are checked.

### Expected behaviour
v-model returns the selected option object data and only the selected option is checked

### Actual behaviour
v-model returns null data and all options are checked

Dependencies:
Vue 3.2
Multiselect 2.6.2

**Comment by smirnov-d** [comment]
Hello, @aqordeon. U should use the ```npm install vue-multiselect@next``` with vue v3.
see the Readme https://github.com/shentao/vue-multiselect/tree/next.
