### ISSUE TITLE
Problem with Vue 3 and v-model

### ISSUE THREAD

**Issue by Mobin-khorushi** [shentao/vue-multiselect#1714]
Hi sorry I'm new with Vue and sadly it seems i faced a big update and all docs are old or like you they throw a big hint but its not what i can discover can you please explain what i made wrong my prop is not getting updated ?! 

here is my code 

![image](https://github.com/shentao/vue-multiselect/assets/63199334/9d43eeab-6e50-45dc-ade1-86176c44dd34)

This is the SelectInput.vue

![image](https://github.com/shentao/vue-multiselect/assets/63199334/a29d2944-5972-4f8b-a4ec-a31207db48d8)

**Comment by mattelen** [comment]
Are you emitting your value to your parent component? I'm not seeing where that is happening. In all honesty I'm still picking up composition API so please "point out the obvious" if it is.

**Comment by smirnov-d** [comment]
@Mobin-khorushi, this is a working example of the ```SelectInput.vue```
```
<template>
  <vue-multiselect
    :options="options"
    :model-value="modelValue"
    @update:model-value="$emit('update:modelValue', $event)"
  />
</template>

<script setup>
import VueMultiselect from 'vue-multiselect'

defineProps(['modelValue'])
defineEmits(['update:modelValue'])

const options = [
  'Vue.js',
  'React.js',
  'Angular.js'
]
</script>
```

**Comment by ilyen85** [comment]
You have to change this line:
`@update:model-value="modelValue"`

To this:
`@update:model-value="$emit('update:modelValue', $event)"`

You need to $emit the `update:modelValue` event and the value will be a special event called `$event` which will be the select field's value.

**Comment by Mobin-khorushi** [comment]
thanks alot guys sorry for late reply I actually find out your answers my self after trying a lot but anyway thanks

**Comment by gurparshad** [comment]
does not work
