### ISSUE TITLE
Dropdown do not render with v2.5.x

### ISSUE THREAD

**Issue by sandeepscet** [shentao/vue-multiselect#1721]
The dropdown does not render with Vue@2.5..x versions. It render properly with 2.6 though.

### Reproduction Link
- Not Working - https://jsfiddle.net/h19ytrsz/ (V2.5.15)
- Working - https://jsfiddle.net/kshx046t/ (V2.6.14)

### Steps to reproduce
- Please check the above both links

**Comment by komxvl** [comment]
Hi @sandeepscet, both of your links don't render select, very strange...

**Comment by mattelen** [comment]
I don't believe Vue 2.5 or lower is supported by Vue, and therefore we're not in a position to support it as well. I would recommend installing older versions of the multiselect to see if they work for the older versions, or look at updating your Vue version.
