### ISSUE TITLE
multiselect completely broke

### ISSUE THREAD

**Issue by WernerACQ** [shentao/vue-multiselect#1724]
Hi, the library suddenly stopped working

### Reproduction Link

https://jsfiddle.net/shentao/jqofkzxc/

### Steps to reproduce

see link

Can you please provide info on how to fix this?

**Comment by mrckzgl** [comment]
You need to include the vue framework as library in the jsfiddle: https://jsfiddle.net/4ot8d1bz/
Problem is unrelated to this repo.

**Comment by mattelen** [comment]
Yes, in the jsfiddle you need to include the vue framework.
