### ISSUE TITLE
Vue3 NoOptions slot not working

### ISSUE THREAD

**Issue by abab5601** [shentao/vue-multiselect#1727]
### Issue Description

Followed the documentation but for some reason the `noOptions` slot isn't working. The text is not getting displayed

```vue
<template v-slot:noOptions="">New Text</template>
```
I edited the source code to print _ctx.$slots and it shows 'nooptions.' I can't make the slot name uppercase."

**Comment by OsamaNagi** [comment]
- make sure you use the right name in the component like this:

![image](https://github.com/shentao/vue-multiselect/assets/63210048/a375fec4-4fef-4908-8ec6-075b14e889ba)
- you can write v-slot in two ways like this:

![image](https://github.com/shentao/vue-multiselect/assets/63210048/8a062f78-8b9f-4444-9362-3a1cd2336f9b)

**Comment by abab5601** [comment]
I wrote my Vue 3 code using the CDN approach. If I write the template in JavaScript, I can achieve the desired effect:

![image](https://github.com/shentao/vue-multiselect/assets/36041090/e49d191d-3d22-4fcc-a107-e758c1c90396)

However, if I move the interface to HTML:

![image](https://github.com/shentao/vue-multiselect/assets/36041090/18e718f9-a412-4336-9483-b0586574c30c)

The result is not as expected. I believe it's because HTML is not case-sensitive.

**Comment by abab5601** [comment]
I wrote my Vue 3 code using the CDN approach. If I write the template in JavaScript, I can achieve the desired effect:

![image](https://github.com/shentao/vue-multiselect/assets/36041090/e49d191d-3d22-4fcc-a107-e758c1c90396)

However, if I move the interface to HTML:

![image](https://github.com/shentao/vue-multiselect/assets/36041090/18e718f9-a412-4336-9483-b0586574c30c)

The result is not as expected. I believe it's because HTML is not case-sensitive.

**Comment by mattelen** [comment]
Would using a kebab case approach work? like `v-slot:no-options`?
If not, please create a jsfiddle with the issue, so we can figure out what could be going on here

**Comment by viT-1** [comment]
I have same problem, slot noOptions ignored in all ways of declaring.

**Comment by mattelen** [comment]
Need repro link
