### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_c')

### ISSUE THREAD

**Issue by inlancersystem4** [shentao/vue-multiselect#1735]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c')

**Comment by MRezaKarimi** [comment]
Duplicate issue
See: #1533

**Comment by mattelen** [comment]
@inlancersystem4 Do you have a reproductive link so we can replicate this?

**Comment by mattelen** [comment]
But also please check what other people have done to fix their issue in #1533, incase that fixes it for you

**Comment by kokorevdev** [comment]
Check your versions & compatibility, I have had the same issue when using the Vue 2 version of the component in my Vue 3 app.
