### ISSUE TITLE
Property maxHeight did not change anything

### ISSUE THREAD

**Issue by Carsak** [shentao/vue-multiselect#1736]
From the docs 
maxHeight | Integer | 300 | Sets max-height style value of the dropdown

### Reproduction Link
https://jsfiddle.net/ju317xba/

### Steps to reproduce
Just add :maxHeight=1500

### Expected behaviour
Changed the 
`<div tabindex="-1" class="multiselect__content-wrapper" style="max-height: 1500px; display: none;">`

### Actual behaviour
`<div tabindex="-1" class="multiselect__content-wrapper" style="max-height: 300px; display: none;">`

Version
`"vue-multiselect": "^3.0.0-beta.3",`

**Comment by lehoaibaokg** [comment]
Try to using :max-height="50" as kebab case.

**Comment by mattelen** [comment]
@lehoaibaokg suggestion does the trick here
