### ISSUE TITLE
Outer combobox container is not stylable

### ISSUE THREAD

**Issue by kokorevdev** [shentao/vue-multiselect#1739]
There seems to be no functionality (or documentation) on styling the outer container of the combobox (the box with the .multiselect class). The apperance of all inner components such as tags, options, placeholder text etc. can be altered via slots or changing the CSS. However, the outer component itself (in particular, border radius, background color) seem to be missing any styling options.

Please correct me if I'm wrong on this or if this feature is just not documented.

**Comment by mattelen** [comment]
The outer components can be changed by adding in your own CSS in your app, and by targeting the classes used in the component. You can check out the full CSS styling here: https://github.com/shentao/vue-multiselect/blob/next/dist/vue-multiselect.css
