### ISSUE TITLE
singleLabel slot can not read nested property

### ISSUE THREAD

**Issue by DarkMode1426** [shentao/vue-multiselect#1745]
<template>
    <multiselect
        :loading="isLoading"
        v-model="selectedOption"
        @select="handleChange"
        :options="options"
        :placeholder="Lang.get('lang.Machineries')"
        track-by="id"
        :showLabels="false"
        :allow-empty="false"

    >
        <span slot="noResult">Oops! No elements found. Consider changing the search query.</span>
        <template v-slot:singleLabel="{ option }">
            <div>{{ option.machinery.en_name }}</div>
        </template>
        <template v-slot:option="{ option }">
            <div>{{ option.machinery.en_name }} <br>Batch No: {{ option.batchNo }}</div>
        </template>
    </multiselect>
</template>

For this code option slot can read the nested property which is en_name, but the singleLabel slot throws an undefined error.

**Comment by lehoaibaokg** [comment]
It works for me, I don't think the nested object is the problem from the library.
Try using another syntax like this, to ensure the `option.machinery` is not `null/undefined` before accessing en_name, you can add `v-if="option.machinery"`
```
<template slot="singleLabel" slot-scope="props">
    <div v-if="option.machinery">{{ option.machinery.en_name }}</div>
</template>
```

**Comment by mattelen** [comment]
Agree with @lehoaibaokg. If you need more help, I recommend creating a JSFiddle with a full reproducible example so we can take a closer look

**Comment by DarkMode1426** [comment]
Thank you for your response!
The issue has been resolved, and I really appreciate your time and
assistance. Your help is much appreciated!
