### ISSUE TITLE
Search doesn't work with Vue 3.4.x

### ISSUE THREAD

**Issue by leopowershield** [shentao/vue-multiselect#1748]
### Reproduction Link
no link.

### Steps to reproduce
Update any Vue 3 project using vue-multiselect v3.0.0-beta.3 to the version 3.4.15 

### Expected behaviour
Search on vue-multiselect working

### Actual behaviour
Search doesn't work, it shows this error in console:

![image](https://github.com/shentao/vue-multiselect/assets/149634217/ff3f6bc3-65f6-4e6c-add3-613e7a0948c9)

**Comment by mattelen** [comment]
I can't replicate this issue, nor is there a link to reproduce this error. Please provide a reproduction link and I'll have a look

**Comment by leopowershield** [comment]
I have found the issue. If one of the options had a null value, on the search it was crashing. I've just populated it with non-null values and it is working fine using the latest versions.
