### ISSUE TITLE
Select doesn't working

### ISSUE THREAD

**Issue by sergey-horoshko** [shentao/vue-multiselect#1752]
Hello, your plugin is not working. I use this "vue-multiselect": "^3.0.0-beta.3", in my package.json. 

Dropdown is not show, after click. Style display none, not change. Please fixed it.

**Comment by LepuavkoDV** [comment]
![image](https://github.com/shentao/vue-multiselect/assets/5073761/7eeedd06-92fe-445c-a648-cda20d4470c9)
can confirm that display:none option is not being removed after you trying to open multiselect

**Comment by romamaslennikov** [comment]
help pls

**Comment by mattelen** [comment]
@sergey-horoshko can you either provide a reproducible link, or a git that shows an example of this error?

**Comment by sergey-horoshko** [comment]
@mattelen 
https://github.com/sergey-horoshko/multiselect

**Comment by LepuavkoDV** [comment]
> @mattelen https://github.com/sergey-horoshko/multiselect

almost completed my replica to reproduce issue. Tnx alot

**Comment by mattelen** [comment]
Ok, so as a temp workaround, this only affects Vue 3.4.15+. I've found 3.4.14, it seems to work fine. I'll look into creating a fix for this

**Comment by mattelen** [comment]
This is an issue as a result of a Vue Core bug. It is recorded here: https://github.com/vuejs/core/issues/10294. I hope they will jump into this and fix this - please jump into this issue and make a reaction to indicate this is affecting you. 

In the meantime, I won't update anything and will wait for this issue to be fixed there

**Comment by LepuavkoDV** [comment]
so the only way to make plugin work - downgrade to 3.4.14 for now?

**Comment by LepuavkoDV** [comment]
well, sounds fair. Ty alot for your quick response and workaround. Saved my a**

**Comment by mattelen** [comment]
Vue has just released 3.4.17 (https://github.com/vuejs/core/blob/main/CHANGELOG.md). I've installed it on sergey-horoshko's repo, and it no longer faults. 

**So to fix this issue, install Vue version 3.4.17+**

Thanks everyone for contributing and figuring out what is going on here

**Comment by abdouthetif** [comment]
The issue concerns Vue version 3.2.45 also
