### ISSUE TITLE
Create prop :requiered=true

### ISSUE THREAD

**Issue by hdev07** [shentao/vue-multiselect#1759]
They need to add the required prop to emit an event and be able to do validations with that prop and event

**Comment by amchconsult** [comment]
Yes, please add required prop.
Thank you

**Comment by mattelen** [comment]
Required prop was added as part of 3.1.0.

**Comment by amchconsult** [comment]
Great. 
I was just trying and I found a problem using multiple="true". It keeps saying This is Field is required.
