### ISSUE TITLE
Need slot for leading icon before label

### ISSUE THREAD

**Issue by solidevolution** [shentao/vue-multiselect#1774]
### Reproduction Link

I want to add a custom icon from our design system as prefix for tags. (search icon)

### Steps to reproduce

Currently I found no slot to make this work.

### Expected behaviour

There could be a new slot for leading informations.

### Actual behaviour

There is no slot available for this.

**Comment by idlethumbs** [comment]
@solidevolution you could just use the slot that overwrites the whole tag to achieve this
<template #tag>
