### ISSUE TITLE
Slots are mis-named in the examples

### ISSUE THREAD

**Issue by amchconsult** [shentao/vue-multiselect#1776]
Hi,
Question per example. To assign in slot a different color per item selected.
Slot does not seems to be working. Same with tags.
Do you have any other example.

```
<div><label class="typo__label">Single select / dropdown</label>
    <multiselect v-model="value" deselect-label="Can't remove this value" track-by="name" label="name"
                 placeholder="Select one" :options="options" :searchable="false" :allow-empty="false">
      <template slot="singleLabel" slot-scope="{ option }"><strong>{{ option.name }}</strong> is written in<strong>
        {{ option.language }}</strong></template>
    </multiselect>
    <pre class="language-json"><code>{{ value }}</code></pre>
  </div>
```

thank you

**Comment by mattelen** [comment]
Ah looks like we missed this as part of the Vue 2 -> Vue 3 docs.

I'll make updates to the docs, but in the meantime, this line of code:
``
<template slot="singleLabel" slot-scope="{ option }"><strong>{{ option.name }}</strong> is written in<strong>
``

becomes

``
<template v-slot:singleLabel="{ option }"><strong>{{ option.name }}</strong> is written in <strong>
``

Give this a try on your codebase, and it should work
