### ISSUE TITLE
Rework event system to better support mobile? 

### ISSUE THREAD

**Issue by arronf2e** [shentao/vue-multiselect#178]
I use this in my project, but I think it's not smooth in my project. why

**Comment by shentao** [comment]
I will look into it. What mobile device do you use? :)

**Comment by arronf2e** [comment]
@shentao I'm in china , an android mobile.

**Comment by zipme** [comment]
hi @shentao , the component currently uses `focus` and `blur` events together with `tabindex` to trigger `activate()` and `deactivate()`, this works great on desktop browsers, however it does not work so well on Mobile Safari, when touching a `div` with `tabindex` attribute, the `focus` event is not getting triggered and you can only click the small arrow to toggle the dropdown. 

A related issue #147

**Comment by Spittal** [comment]
Could falling back to the native `<select multiple></select>` on the platform if on mobile be a good solution?
