### ISSUE TITLE
autocomplete="off" not working in chrome

### ISSUE THREAD

**Issue by sholzer** [shentao/vue-multiselect#1802]
Hello,
autocomplete="off" attribute is not working in chrome, can you please change it to autocomplete="none" ? 

Regards :)

**Comment by mattelen** [comment]
My concern with switching this is that it goes against the HTML spec, as there is no "none" in the spec (https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete). I'd rather this as a prop so it can be set for each use case. So I'll create an Idea in the discussion area, feel free to continue the conversation and ideas in there.
