### ISSUE TITLE
How to handle directly focus and blur event on an input element.

### ISSUE THREAD

**Issue by geguriyj** [shentao/vue-multiselect#214]
Hello folks.

Can I keep the value of an input element and the status of "multiselect__content" as open when a blur event happens?

Do you have any idea?

**Comment by shentao** [comment]
I guess that's not possible atm. Sorry :(

**Comment by garhbod** [comment]
Yeah same issue here. Focus and blur are not emitted

**Comment by garhbod** [comment]
There is an open and close event which appears to be the same as focus and blur. Maybe focus and blur could be emitted at the same time as open and close. In any case @geguriyj for the time being just use as follows
`<multiselect @open="focusHandler" @close="blurHandler" ...`
