### ISSUE TITLE
function for @select is not called on ipad (both Chrome and Safari)

### ISSUE THREAD

**Issue by masoudmemariani** [shentao/vue-multiselect#257]
Hi,

My multiselect works perfectly on desktop. 
In **Safari and Chrome on ipad** on the other hand, I can choose between the options and it shows the highlighting and updates the selected option in the dropdown, but it does not call the function I specified in @select (applyFilter below). Am I missing something?

It works though in **Chrome on Samsung Galaxy Tab.**

` <multiselect
            id="categoryselector"
            :value="filterCategories[0]"
            :searchable="false"
            :show-labels="false"
            placeholder=""
            :close-on-select="true"
            :hide-selected="true"
            :allow-empty="false"
            @select="applyFilter"
            :options="filterCategories"></multiselect>`

Thank you in advance.

**Comment by shentao** [comment]
Might be a problem with events on mobile Safari. I will look into it, thanks!

**Comment by masoudmemariani** [comment]
It's both Safari and Chrome on ipad. 
I wonder if this can be related to delays between the touch and click events?

**Comment by shentao** [comment]
That’s because underneath everything uses Safari on iOS devices.

**Comment by janardhanchinna** [comment]
Any news on this please?

**Comment by sirchas** [comment]
Should be merged with https://github.com/monterail/vue-multiselect/issues/363 ? Same issue? Just wondering if there is a small workaround.

**Comment by washingtonbr** [comment]
Would it be merged into trunk? I really need it to my project. Thanks in advance.

**Comment by shentao** [comment]
Still needs some investigation. :/

**Comment by clay-spfmlp** [comment]
Any updates for this?
