### ISSUE TITLE
[v 1.1.4] currentOptionLabel being set but not showing on select

### ISSUE THREAD

**Issue by almcewen** [shentao/vue-multiselect#298]
I've just switch to v1.14 and cant seem to display the `currentOptionLabel `

When an item is selected it fires the custom update function, updates the selected item and the option label is computed correctly (verified with vue inspector). However, the label remains the input with placeholder text.

I have found that if i give the component a `ref` and access via` this.$refs.mySelect.search` I can set the search to value

Any ideas why this could be?

**Comment by shentao** [comment]
Hey!
If possible you should upgrade to Vue 2.x and to the recent beta release of vue-multiselect.

Please provide your markup and scripts for me to able to help.

**Comment by almcewen** [comment]
We are planing on moving to v2.0 when we can make some time. The app is pretty complex with many dependencies to that's making finding the time even harder but defiantly take your point.

Here's a summary file with the code based of the example in the docs. One thing is we use 3 multiselects in the same component. 

[MultiselectCodeInfo.md.txt](https://github.com/monterail/vue-multiselect/files/813548/MultiselectCodeInfo.md.txt)
