### ISSUE TITLE
Issue when clicking on the placeholder in IE11 on not searchable fields 

### ISSUE THREAD

**Issue by thupi** [shentao/vue-multiselect#307]
I do experience a issue when clicking on the placeholder to open det dropdown in IE11. This issue can be seen by going to the documentation page in IE11 and scroll down to the single select object without search. When clicking on the placeholder on that component nothing happens. However i am able to click on the icon og the right hand side.

I have only tested this in Chrome and IE11 and as far as i know it works perfect in chrome while being an issue on IE11 :-)

**Comment by yassineMDC** [comment]
I have the same probleme , the mousedown event is not attached to the .multiselect div on IE11
