### ISSUE TITLE
Using SelectLabel globally?

### ISSUE THREAD

**Issue by Fohlen** [shentao/vue-multiselect#335]
Heya there. Is there a way to globally initialise the `SelectLabel` property? I'd like to localise `vue-multiselect` but couldn't find a lot of information in the documentation. Passing the `SelectLabel` did not work for me, and neither is it a pretty option to pass translation to every single select.

**Comment by shentao** [comment]
Improving the internationalization support should be the focus for the next releases.

Currently you can create a wrapper for Multiselect that would take care of the repeating props.

**Comment by toabi** [comment]
@shentao do you have a rough timeframe for that? Then I can estimate if it's worth to wrap or wait ;)

**Comment by shentao** [comment]
It’s definitely better to wrap. This can also help you with simplifying the rest of the configuration.

**Comment by shentao** [comment]
After some thinking about it, I guess I could use the provide/inject functionality that shipped with Vue v2.2.0 to be able to set global defaults for `selectLabel` and similar. What do you think?

**Comment by Fohlen** [comment]
A faster working solution will be to use `extends` for now, until you make `vue-multiselect` a [plugin](https://vuejs.org/v2/guide/plugins.html), which is definitely less hacky / more clean than using `inject` (wouldn't require people to implement the custom provider logic themselves).
