### ISSUE TITLE
Options to close menu when clicked on existing value

### ISSUE THREAD

**Issue by ricardobanegas** [shentao/vue-multiselect#342]
There's a UI problem I'm trying to deal with. 

In native select-boxes, if you click on the selected value is just closes the option.

![screenshot 2017-04-02 10 32 34](https://cloud.githubusercontent.com/assets/943250/24585689/e97763c8-1790-11e7-8285-7f5356fb31f2.png)

![screenshot 2017-04-02 10 32 38](https://cloud.githubusercontent.com/assets/943250/24585691/ec01ce6c-1790-11e7-9c9c-417f822ef676.png)

Tried using `:allow-empty="false"` to achieve this, but clicking on the selected value doesn't close down the menu. I've tried to use `@select` to programatically fix this but it is not fired on existing values. 

I've attached a simple Fiddle. Any help in this appreciated! Thanks for a great plugin.

[https://jsfiddle.net/ce9duodo/](https://jsfiddle.net/ce9duodo/)

**Comment by shentao** [comment]
This might be implemented in the 3.0 release.
