### ISSUE TITLE
problem with scrollbar & pointer

### ISSUE THREAD

**Issue by razuli** [shentao/vue-multiselect#358]
Hi, great component!

There is a small issue that bothers me:
when using the arrows to go up and down in the options list, the pointer behave strangely on the bottom and the top of the scrollbar. 

for example, if you will take the first example from your website (the single select) - 

click on the first item of the list ("select option"). then click arrow-down 7 times, until the pointer points on "hide selected element". now, the next arrow-down click should move the pointer to the next item ("maxHeigth"), but instead, the pointer jumps up to the second element ("options")!

same problem happens when clicking arrow-up.

Thanks!

**Comment by shentao** [comment]
Oh, I think that’s because when the scroll happens and the mouse pointer is over an option it actually triggers the mouse hover event and highlights the element.

**Comment by NguyenVanTuanGit** [comment]
I'm working with multi selected in vue is, I have dropdown list, when I click at dropdown list, the verticall scrollbar apearance, every thing ok on chrome ,fifox, but IE the scrollbar alway hide and show at the time,I click,please help me now
