### ISSUE TITLE
usage 'v-model' in vue-multiselect

### ISSUE THREAD

**Issue by G2linkweb** [shentao/vue-multiselect#368]
when I use 'v-model' in vue-multiselect ,there will be a warning,   "v-model does not support element type: DIV". this is why?

                       <multi-select
                          v-model="selectedCountries"
                          id="ajax"
                          label="userName"
                          track-by="code"
                          placeholder=""
                          :options="userNames"
                          :multiple="true"
                          :searchable="true"
                          :loading="isLoading"
                          :internal-search="false"
                          :clear-on-select="false"
                          :close-on-select="false"
                          :options-limit="300"
                          :limit="2"
                          deselect-label=""
                          select-label=""
                          :hide-selected="true"
                          @search-change="asyncUserFind"
                          @update="updateUserSelected8">
                          
                      </multi-select>

**Comment by shentao** [comment]
Could you elaborate? Provide a JSFiddle maybe?

**Comment by stesi561** [comment]
This fiddle generates the same warning: https://jsfiddle.net/04jvjuv3/43/

**Comment by stesi561** [comment]
This generates the same warning https://jsfiddle.net/04jvjuv3/44/

**Comment by pczarn** [comment]
@G2linkweb @stesi561 Please make sure you have version 2.0 of multiselect. The support for `v-model` was added in that version. In the jsfiddle, v1.1.4 is loaded, so it won't work.
