### ISSUE TITLE
customize input

### ISSUE THREAD

**Issue by xralphack** [shentao/vue-multiselect#371]
is there chance to customize the template of input part

**Comment by marlonbuendia** [comment]
Do you mean the selected value that will be displayed in the input? I don't think custom-label recognizes html.

**Comment by xralphack** [comment]
@marlonbuendia 

I mean I want to fully customize the input component,

For example, we can customize options now.

If the input part can have the same style like one of the options. It can be more possibility

**Comment by marlonbuendia** [comment]
@xralphack 
You are talking about the :custom-label?

check my other questions maybe you can also help me:
https://github.com/monterail/vue-multiselect/issues/377
https://github.com/monterail/vue-multiselect/issues/376

**Comment by xralphack** [comment]
@marlonbuendia 

yes, what I want is add html to custom-label

:custom-label seems only handle the data

but I think using slot maybe be better ?

**Comment by shentao** [comment]
Added slot for tags. You can now customise them. See: https://github.com/monterail/vue-multiselect/commit/41fc501e1e572d6c80451788743a6b41520a4454

Working on a release.

**Comment by fanckush** [comment]
it is still not passable to add custom html in customLabel in case of single select..

**Comment by fanckush** [comment]
Are there any down sides to simply changing from v-text to v-html in this line?
https://github.com/shentao/vue-multiselect/blob/08fc1a1b575cfa5b374743b40a4b1d2fdb5440c2/src/Multiselect.vue#L58

**Comment by shentao** [comment]
I think the best way would still be to use a scoped slot to implement it

**Comment by fanckush** [comment]
True. i'll try to make a pull request

**Comment by fanckush** [comment]
I have made a pull request (https://github.com/shentao/vue-multiselect/pull/645) to include a scoped slot + an example in the documentation

**Comment by shentao** [comment]
PR was merged. Thanks!
