### ISSUE TITLE
<template> not working with :taggable="true" and @tag="addtag"

### ISSUE THREAD

**Issue by marlonbuendia** [shentao/vue-multiselect#376]

**Comment by shentao** [comment]
More details would be welcome.

**Comment by marlonbuendia** [comment]
@shentao have you tried using <template> with :taggale=true? it doesnt show the results, only the new tag. Im doing asynchronous.

**Comment by rickbolton** [comment]
Like @shentao said more details would be good. I've used :taggable=true and works fine with asynchronous so I guess it's an implementation issue. If you could share your code example and we can then advise on a fix. :)

**Comment by marlonbuendia** [comment]
@rickbolton you have also used <template>?
