### ISSUE TITLE
Disable internal-search when using group options with an empty list displays an object as item

### ISSUE THREAD

**Issue by Finrod927** [shentao/vue-multiselect#378]
Hi

In my project, I'm using vue-multiselect with group options and an ajax based list, so I disabled the internal search with `:internal-search="false"` and I just found an issue when one of the group list is empty.

When a group list is empty, it will display the Json object as an item: https://jsfiddle.net/tetr7v1x/2/

![2017-05-24 11_41_49-vue-multiselect - jsfiddle](https://cloud.githubusercontent.com/assets/14069298/26397262/01ab1e90-4076-11e7-9fde-542683afcea8.png)

Working fine when removing `:internal-search="false"`

**Comment by JoeMugen** [comment]
I had another problem with this option and ajax request. When value query got space or dash or quote, like `word-o'something` or `word- osomething`. My props filled up but nothing was rendered. I added `:internal-search="false"` and boom everything was fine.

**Comment by shentao** [comment]
This should not happen on the current master. Preparing a new release.
