### ISSUE TITLE
Clicking on scrollbar triggers @close and @open events

### ISSUE THREAD

**Issue by roylkng** [shentao/vue-multiselect#403]
on http://monterail.github.io/vue-multiselect/ in Options Groups, if you click on scroll bar and watch for the events though a chrome-vuejs extension, you can see the @close and @open calls happening in the background, i am consuming those events for resetting the options so clicking on scrollbar screws up the multiselect altogether for me.

**Comment by shentao** [comment]
Doesn’t happen to me. What browser/OS are you using? 
Would be best if you could provide a repro using the JSFiddle example.

**Comment by mastokley** [comment]
i'm seeing this issue too, as are my coworkers. we're using chrome and chromium on windows, osx, and ubuntu.
