### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by 304NotModified** [shentao/vue-multiselect#413]
Is there a changelog?

Older versions has the changelog in [Releases](https://github.com/monterail/vue-multiselect/releases), but I can't find the changelog for 2.0.2, 2.0.1 and 2.0.0

**Comment by shentao** [comment]
Working on it. Need to figure out a way to automatically generate changelogs from commits.

**Comment by 304NotModified** [comment]
I'm using github changes: https://github.com/lalitkapoor/github-changes

**Comment by 304NotModified** [comment]
But you need git tags or github releases for it, although that's good practice anyway

**Comment by shentao** [comment]
Thanks :) Will be using it for the release notes.
