### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by shentao** [shentao/vue-multiselect#42]
I could really use some help with the documentation and examples. ;)

I’ve just split the documentation into smaller partials to make it easier to work with.
https://github.com/monterail/vue-multiselect/blob/master/docs/index.jade

If any of you have any cool ideas how we could improve the documentation, let me know! PRs are obviously welcome too! :)

**Comment by mstnorris** [comment]
First of all, apologies that I can't offer any support for the documentation as I am new to this. I was actually looking at the documentation and couldn't get my head around it.

Your plugin is very nice and as per the examples that you _do_ have I can see it works very well.

A few suggestions if I may, please could you add a "Getting Started" section that walks someone through from start to finish. I don't see any other of these plugins online doing this, and they always assume that the user knows what to do in the very first instance... i.e setting up browserify, gulp, web pack, rollup etc.

Secondly, could you provide more JavaScript examples alongside the Jade.

Thank you again, it looks great!

**Comment by shentao** [comment]
Hey!

Yeah, I know the documentation isn't perfect. It is in the road map to further improve it. I already have some ideas how to accomplish this. Before this happens, I want to finish the new release as it will introduce some changes to the component's API.

**Comment by mstnorris** [comment]
Thanks for your reply! Someone helped me get a basic select up and running... I'm using Laravel and Elixir. However I need to get searching, tagging, and AJAX working.

Thanks for this though, I'll be sure to check back soon.

If I think of a way I can help then I'll let you know. Likewise, if you get stuck with anything, then ask, if it is in my remit, and if I can help I will.

**Comment by dabernathy89** [comment]
Hey, this component looks awesome. Can't wait to use it. The only thing in the docs that didn't seem too clear to me is "tagging" - I just don't understand what it means. The async example and the tagging example look exactly the same to me (apart from the async-ness, of course).

**Comment by shentao** [comment]
Tagging makes it possible to actually create your own options based on the search phrase. This can be useful for situations where you provide a basic list (for example a list of hobbies that other users already submitted), but also give the user the ability to create a new option for their hobby if it wasn’t on the list already. 
As for the example in the docs, just type something that isn’t on the list and press enter.
The function called `@tag` is basically taking the search phrase and creating a new option object, with the search query as the `name` and a random integer as `code`. After this it gets pushed into both the selected and the available options list.

**Comment by dabernathy89** [comment]
@shentao thanks, that makes a lot of sense now.

**Comment by shentao** [comment]
I can understand that it might not be clear, especially today, there was a small bug (not showing the highlight labels introduced this morning) that you actually helped to fix! 👍 
Thanks!

**Comment by flip-santos** [comment]
Hey guys, I'm trying to use this awesome component with plain ES6 and raw HTML, but i'm having trouble with this documentation. It's seems that I can only send data to populate the component with array, and when I send a collection to the ":options" the component won't render the content.

Also, how do I sync a model to this component, It's not clear in this documentation.

I'm willing to do this native JS and HTML examples for this project if I can resolve this.

Thanks ;)

**Comment by shentao** [comment]
@flip-santos The `options` prop has to be an Array. Maps and Objects are not yet supported.
By design two-way binding (aka syncing) is not supported. You pass the `selected` value and then listen to the `@update` events and change the `selected` value accordingly.

http://monterail.github.io/vue-multiselect/#select-primitive This is a basic example of how to update the model.

**Comment by shentao** [comment]
@sigalZ please refer to the docs. The `.sync` modifier is deprecated. You have to use the `@update` event to handle the updating of the selected prop
.

**Comment by SigalZ** [comment]
@shentao thank you, but I didn't ask about the selected prop, I asked about how do I populate the options. I read the docs I could not get it.

**Comment by SigalZ** [comment]
If anybody is interested, I got an answer here: [http://stackoverflow.com/questions/39792864/vue-multiselect-with-laravel-5-3](Stackoverflow)

**Comment by shentao** [comment]
Ouch, sorry! Replied from a bus and didn't really read deep into the question after I saw an error in the code. Glad it already works!

**Comment by viraj-khatavkar** [comment]
@shentao I can lend you a hand on documentation. Let me know what you are planning and I will try to take it from there :)

**Comment by shentao** [comment]
That would be nice @viraj-khatavkar :) You can go to the `groups` branch and work on grouping documentation there. :)

**Comment by viraj-khatavkar** [comment]
Sure, will look at it :)
