### ISSUE TITLE
Jumping behaviour when selecting options

### ISSUE THREAD

**Issue by pepf** [shentao/vue-multiselect#437]
Great work on the lib so far, really enjoy using it!
The main prop config in which we use the component is as follows:
```html
  :multiple="true" 
  :taggable="true" 
  :close-on-select="false"
```
which results in a multiselect that allows selection of multiple (predefined) tags and doesn't close on select. 

**Observed**
In combination with a restricted width, and quite a few selectable options, this can result in a sub-optimal selection experience. 
The dropdown with options will "jump down" when a tag is selected that will overflow the tag container.
 
**Expected**
The dropdown with options stays in the same place, allowing the user to quickly select and deselect, regardless of the combination of tags displayed in the container.

I'm aware this is not a functional bug, but we are currently trying to solve this problem in our own wrapper component, while the solution can be valuable for this lib as well :)

**The fiddle:**
https://jsfiddle.net/6eu5q13o/1/

![kapture 2017-07-18 at 9 53 07](https://user-images.githubusercontent.com/1265435/28306282-05730e6c-6b9f-11e7-83c3-dc22f3ae7cdc.gif)

**Comment by shentao** [comment]
Hey! That is certainly unfortunate, however quite hard to solve before 3.0. Will keep that in mind though.
