### ISSUE TITLE
When using the 'option' template with :taggable="true" and asynchronous select, the header should not be influenced by the template

### ISSUE THREAD

**Issue by Hillcow** [shentao/vue-multiselect#439]
<img width="219" alt="screen shot 2017-07-18 at 14 08 12" src="https://user-images.githubusercontent.com/20979750/28316299-9455f3ec-6bc2-11e7-997b-b493bf5fefba.png">

Normally, the header should represent the query the user is typing in. If I use props.search, I get it for every single row. I hope you can get the idea.

Here is an example without the asynchronous select: https://jsfiddle.net/c4L3gs91/291/

You can see that the "-----" is still visible when typing something new. Now when you use asynchronous select, your options don't disappear and you are writing all over the place in every single row.

Thank you

**Comment by pczarn** [comment]
@Hillcow 

I can see a solution -- you should display text conditionally inside the `option` slot, based on the option being a tag or not. The right way to fix the fiddle is with this code
```
    <template slot="option" scope="props">
      <template v-if="props.option.isTag">
        {{ props.search }}
      </template>
      <template v-else>
        {{ props.option.language }} ----- {{ props.option.library }}
      </template>
    </template>
```

Unfortunately the `isTag` attribute is not yet documented
