### ISSUE TITLE
Can't select or add more than one tag in PhoneGap/Cordova

### ISSUE THREAD

**Issue by rokgfx** [shentao/vue-multiselect#451]
I need to use the tagging feature for a PhoneGap app. I'm using the exact same code as written in the docs and the tagging works as expected but **only** for the first tag. I can add or select a tag from the dropdown and the tag appears in the list. After that, the whole input seems to get disabled (but not actually disabled visually) and can't interact with it. Simply nothing happens when I try to click anywhere in the input (or on the tag to try to delete it).

I don't get any errors in the console and looked at the css in case anything is blocking it there. Also the same thing happens if I pre-populate the input with one tag (can't add any more).

I'm using PhoneGap with Vue + Framework7. This issue happens in both the browser (Chrome) and on iOS.

**Comment by shentao** [comment]
Really weird. Could you please provide a reproduction repo? That could help.
