### ISSUE TITLE
Is it possible to show nested items ?

### ISSUE THREAD

**Issue by hskrishna29** [shentao/vue-multiselect#465]
Is it possible to show nested items as is in multiselect?

my array structure looks like this

```
[
  {
    text: 'level1-a',
    children: [
      {
        text: 'level2-a',
        id: 1
      },
      {
        text: 'level2-b',
        id: 2
      },
      {
        text: 'level2-c',
        children: [
          {
            text: 'level3-a',
            id: 3
          }
        ]
      }
    ]
  },
  {
    text: 'level1-b',
    id: 4
  }
]
```

**Comment by hskrishna29** [comment]
previously, this was achieved with select2 formatSelection/formatResult, how would achieve this with multiselect? 

From what i have understood, i need to create a custom template that represents my option, and then handle the rendering as a part of the option scoped slot?

**Comment by shentao** [comment]
This is only possible for the 1st layer of nesting if you use groups. Although the group name can’t be picked as it’s just a wrapper.

This could be possible in the 3.0 release though.

**Comment by shentao** [comment]
With the upcoming release the group names will allow for picking the whole group if `groupSelect` is enabled.
