### ISSUE TITLE
Selecting option with circular reference causes errors

### ISSUE THREAD

**Issue by SkaceKamen** [shentao/vue-multiselect#480]
**Description**
When you have option, which referes some kind of cycle, `RangeError: Maximum call stack size exceeded` occurs.

**Example**
https://jsfiddle.net/qfja0nnv/

**Steps to reproduce**
1. Create option which refers itself
2. Select this option in multiselect
3. Option won't get assigned to model,  `RangeError: Maximum call stack size exceeded` occurs.

**Observations**
I looked at the sources, and it looks like the component is making deep copy of its options at some point. Is this neccessary?
If it's so, some kind of circular reference protection would be nice.

**Comment by shentao** [comment]
I believe it’s a bad idea to use unserialisable data as options. The copying is necessary at the moment. Might not be necessary for the 3.0 rewrite I’m planning. 

Thanks for noticing though! :)

**Comment by hbrackmann** [comment]
This also brakes typescript support. An array of typescript objects is passed as option but  the resulting values bound with v-model contains copied json objects.
Probably it also brakes normal js objects with methods.

**Comment by shentao** [comment]
This should no longer be a problem after the changes to master branch (removed deep cloning).Preparing a release.
