### ISSUE TITLE
Pressing Alt causes select box to loose focus

### ISSUE THREAD

**Issue by ingria** [shentao/vue-multiselect#487]
Shift+Alt is a popular shortcut for keyboard layout switching. That's why it is a problem: one have to click on the select box every time they change a kbd layout.

**Comment by shentao** [comment]
Didn’t know that (I don’t change keyboard layouts). Should be an easy fix by catching the keys pressed.
```
@keyup.tab.shift.prevent=""
```

**Comment by codefuhrer** [comment]
No, that didn't work. Neither `@keyup.tab.shift.prevent=""`, nor `@keyup.shift.alt.prevent=""`
