### ISSUE TITLE
The examples page does not work on IE 11

### ISSUE THREAD

**Issue by anhmv** [shentao/vue-multiselect#490]
I have tried to visit the examples page by using IE 11, but I don't see any select box. Did you stop support IE?

**Comment by Frizi** [comment]
I didn't stopped, but I also didn't paid too much attention. If you can tell me what's the error you are seeing, I might fix it. There is nothing inherently incompatible with IE in this library.

**Comment by anhmv** [comment]
That is what I saw on my PC (Win 10, IE 11)
![multiselect-does-works](https://user-images.githubusercontent.com/5557464/29767830-1ec41f02-8c0e-11e7-95e2-717fa78d2009.png)

**Comment by shentao** [comment]
Oh, so it’s not a problem of Vue-Multiselect itself, just the docs page (lack of the mentioned polyfill for Promises). Thanks!
