### ISSUE TITLE
@Close event occurs when using options scrollbar on IE 11

### ISSUE THREAD

**Issue by sebCBien** [shentao/vue-multiselect#494]
HI,

I'v encounter an issue using multiselect (2.0.2) on IE 11

Please try this exemple : https://jsfiddle.net/568tq6pr/2/

When the user tries to scroll, options list is cleared and the @close is called. 
The only way to see last options is to use the mouse Wheel.

This issue not occurs on Chrome.

Is it possible to have a fix for it ?

Thanks

**Comment by abellion** [comment]
I have the same issue. Found that's coming from IE, though it seems there are workarounds available : 

- https://github.com/sagalbot/vue-select/pull/373/files
- https://github.com/selectize/selectize.js/issues/1004#issuecomment-346324568

**Comment by abellion** [comment]
Hey,

I still face the issue, just tested on the latest release. Here is a fiddle to demonstrate it : https://jsfiddle.net/y6xu72hk/42/

The `close` event is fired when clicking on the scrollbar in IE11 : 

![multiselect](https://user-images.githubusercontent.com/9916488/50640330-d4a15580-0f64-11e9-8766-614c12090d90.gif)

Do you have any workaround ? Seems like other select libraries have the same :

https://github.com/ant-design/ant-design/issues/7934
https://github.com/selectize/selectize.js/issues/1004
https://github.com/JedWatson/react-select/issues/1020
https://github.com/corejavascript/typeahead.js/issues/166
