### ISSUE TITLE
Custom scrollbar

### ISSUE THREAD

**Issue by rootboard** [shentao/vue-multiselect#519]
Hello,

Has anyone tried apply custom scrollbar for multiselect? It would be nice if you show any solutions.
How do you think about to implement custom scrollbar into the multiselect, because I think default scrollbar takes much space, when you need to make in a small row three or more selects (like a 280px block and there 3 selects for date of your birth).

Best regards.

**Comment by Koc** [comment]
have anybody find the sollution how combine vue-multiselect with custom scrollbar?

**Comment by launchriot** [comment]
Here is a pure css solution that only works for webkit-based browsers:

`.multiselect__content-wrapper::-webkit-scrollbar-track
{
  -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
  border-radius: 10px;
  background-color: #F5F5F5;
}

.multiselect__content-wrapper::-webkit-scrollbar
{
  width: 12px;
  background-color: #F5F5F5;
}

.multiselect__content-wrapper::-webkit-scrollbar-thumb
{
  border-radius: 10px;
  -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,.3);
  background-color: #555;
}`

source:  https://codepen.io/devstreak/pen/dMYgeO

For a vue-based solution, I started looking at this: https://github.com/BosNaufal/vue2-scrollbar, but have not yet tried to implement it. I suppose you can implement it and call it to appear on the div that has the .multiselect__content-wrapper class.
