### ISSUE TITLE
Release last version

### ISSUE THREAD

**Issue by Aymkdn** [shentao/vue-multiselect#555]
Hi,

This select is one of the best for Vue. Good job :-)

I saw on the homepage that the current release is 2.0.6, however the [releases page](https://github.com/monterail/vue-multiselect/releases) says it's 2.0.3.

Could you release the lastest version please?

Thanks

**Comment by shentao** [comment]
Sure, just need to finally collect all the changes/fixes that were done through the versions. Once I do that, it should write up proper release notes. I should probably think about some kind of automation for this.
