### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking Warning in Chrome

### ISSUE THREAD

**Issue by Codermar** [shentao/vue-multiselect#556]
Hi,

I am getting this warning in the console using Chrome Version 62.0.3202.75:
I am using vue-multiselect 2.0.6, in vue 2.5.2 using 3 instances of the component.

vue.runtime.esm.js?ff9b:6285 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

The functionality does not seem to be affected but this maybe something you may want to look into.

Thanks.

**Comment by shentao** [comment]
Great advice. Would you like to add a PR for this? That should be relatively simple.

**Comment by shentao** [comment]
The event listener is no longer present.
