### ISSUE TITLE
Input disabled when :searchable="false"

### ISSUE THREAD

**Issue by JordanMartin** [shentao/vue-multiselect#557]
When I want to use the component as tag only. There is no input text in the DOM and so, I can't enter text.
```js
 <multiselect 
    v-model="value" 
    :options="[]"
    :searchable="false"
    :taggable="true"
    :multiple="true"
    track-by="library"
    :custom-label="customLabel"
    >
  </multiselect>
```
Please see the jsfiddle to reproduce https://jsfiddle.net/x231u6s2/.

If we only want taggable mode we can just omit the searchable prop and it is working.
But it's not the expected result when seachable is set to false.

**Comment by shentao** [comment]
`taggable` requires `searchable`.

**Comment by dabernathy89** [comment]
Surprised this isn't more requested. It'd be great to be able to use Vue Multiselect as a tagging-only input, and the requirement to show search results while tagging seems arbitrary.
