### ISSUE TITLE
CustomLabel is not working when value is false

### ISSUE THREAD

**Issue by SidKwok** [shentao/vue-multiselect#561]
CustomLabel is blank when value is false(`''`, `false`, etc...).

```vue
<select-box
      :multiple="false"
      :options="[false, '1', '2']"
      :searchable="false"
      v-model="m"
      :custom-label="val => val ? `${val}:00` : 'none'"
/>
```
<img width="204" alt="5e93054805690d3ddc2a49861f0c1b8a" src="https://user-images.githubusercontent.com/13268747/32310092-ed0c6b40-bfca-11e7-8581-f8ea9349ded7.png">

this first option should be 'none'

[jsfiddle](https://jsfiddle.net/jqofkzxc/133/)

**Comment by shentao** [comment]
That’s indeed a bug. Thanks! :)
