### ISSUE TITLE
"Select option" text doesn't disappear when Multiselect is wrapped into another component

### ISSUE THREAD

**Issue by miccio-dk** [shentao/vue-multiselect#565]
Here's a demo: https://www.webpackbin.com/bins/-KyGioWCl2ROvC5oz38Y
If you select an entry from either inputs (they share the same data), one will correctly hide the label, whereas the other will stubbornly show it. In scenarios with proper CSS rendering (sorry about the demo, couldn't really get it to work :stuck_out_tongue:) this causes the label to wrap onto a new line, since no inline style is applied to `multiselect__input` making it fall back to `width: 100%`.

I suspect it has something to do with having `v-bind="$attrs"` and `v-on="$listeners"`.
Any help or indications on how to fix it are welcome.

**Comment by miccio-dk** [comment]
Here's a newer demo: https://codesandbox.io/s/6jv189rq13

Error still occurs, lack of styling still occurs. If anyone knows of a way to sharing vue-related samples which allows for multiple components, please post it here and I will happily port the demo.

 Thanks in advance!

**Comment by shentao** [comment]
You did not add the `vue-multiselect/dist/vue-multiselect.min.css` styles to your app. Here’s a working version: https://codesandbox.io/s/4z5zr3k4v9 (see main.js).

**Comment by miccio-dk** [comment]
@shentao thanks for fixing the styling!
However, that was not the main point of the issue, which instead focused on how vue-multiselect misbehaves when wrapped into another component. 

Therefore, I would like to ask you to investigate this issue further, by looking at how the two instances of vue-multiselect (the wrapped one and the normal one) behave compare to each other. For instance, the "select option" placeholder text doesn't ever disappear, and - since v2.1.0 - the multiple selection is broken.

PS: on an unrelated note, the docs only mention appending the CSS to the <style> section of the component, which didn't seem to work on codesandbox.

**Comment by shentao** [comment]
Seems the issue was with `v-model`. Maybe you need to specify your own `model`? If you use `:value` and `@input` it works. https://codesandbox.io/s/r9pl5mnxq

That’s a good suggestion to move the CSS information to a more prominent position and possibly communicate why it’s needed.
