### ISSUE TITLE
Cannot scroll the options list on mobile/touch devices

### ISSUE THREAD

**Issue by cotej** [shentao/vue-multiselect#566]
Looks like a recent change has broken scrolling through the options list on mobile.  Works fine on 2.0.3, and is broken on 2.0.4+.  Now once you attempt to scroll, it immediately picks the option you landed on.

Fiddles:
v2.0.3 - https://jsfiddle.net/eqn2re9j/3/
v2.0.4 - https://jsfiddle.net/eqn2re9j/4/

Confirmed affected: Chrome on Android, but can also be reproduced using Chrome Dev Tools' responsive design on desktop

**Comment by J-Marriott** [comment]
I'm having the same issue, chrome and safari on iOS.

**Comment by rbnschlz** [comment]
Same problem here as well 2.0.6, Safari and Chrome on iOS.

**Comment by jayjun** [comment]
@tusmumbric highlighted that 9e30fb60d60236d3d226a2dd48a70df35d82249f broke touch scrolling.

**Comment by vaniyokk** [comment]
+1, Great component but weird issue

**Comment by cotej** [comment]
The change that introduced this behavior was reverted, and scrolling on mobile now works correctly again in v2.0.8 (fiddle: https://jsfiddle.net/eqn2re9j/7/).  Closing this issue.

**Comment by chocochaii** [comment]
@cotej I've tested multiselect on https://vue-multiselect.js.org/ from my iphone and found that both scrolling and single-tap on option selecting work. I'm a bit curious that is it really v2.0.8 implemented on site. I tried building my own project with v2.0.8 but single-tap selecting didn't work as you mentioned that it was removed.

**Comment by cotej** [comment]
@chocochaii The behavior you're describing is basically what I would expect.  The workaround for single-tap selection on iOS was reverted (see #581) because it broke scrolling.

I don't have an iOS device to confirm, so I can't explain why you single-tap would be working for you on js.org demo site, but not in your project.  Might be worth having #363 re-opened, or just opening a new issue.

**Comment by shentao** [comment]
Reopening #363. I plan on refactoring the whole interaction part so hopefully we will have both the scroll and selecting working properly on all devices.
