### ISSUE TITLE
Components as Templates with Optional Prop

### ISSUE THREAD

**Issue by launchriot** [shentao/vue-multiselect#569]
This should probably be labeled "Help Wanted".

Is it possible to call components as templates? I would like to add a prop called "template" and do something like this:
```
<multiselect v-model="value" :options="options3" field-label="Content Select With Images" template="content-select-images"></multiselect>
<multiselect v-model="value" :options="options3" field-label="Content Select, No Images" template="content-select"></multiselect>
```
And not have to do this:
```
              <multiselect v-model="value" :options="options3" field-label="Content Select With Images">
                  <template slot="option" slot-scope="props">
                    <img class="option__image" :src="props.option.img" alt="No Man’s Sky">
                    <div class="option__desc">
                      <span class="option__title">{{ props.option.title }}</span>
                      <span class="option__small">{{ props.option.desc }}</span>
                    </div>
                  </template>
              </multiselect>
...
```
(FWIW, "fieldLabel" is a prop I already added.)

And then in actual .vue file, where there is currently the multiselect__content-wrapper, I would have v-if and v-else statements on different template options which would be referencing imported components that contain my various dropdown templates.

Is this feasible?

**Comment by shentao** [comment]
I’m not sure how the `template` prop could work. 
Just put the `v-if` inside the slot, it should be working with custom components inside.
