### ISSUE TITLE
Add class then value is selected

### ISSUE THREAD

**Issue by dimensi** [shentao/vue-multiselect#589]
Add class then value in muitiselect.vue selected, please.
For case where need change border-color if value was selected. Thx in advance.

**Comment by feedgit** [comment]
Let's put it in your methods @select:
```
var e = document.getElementById('your-class')
e.classList.add('your-class-adding')
```

**Comment by shentao** [comment]
Interesting. Will think about it!

**Comment by dimensi** [comment]
@shentao Maybe I close this?
