### ISSUE TITLE
Why clear the text input when we do not select any option?

### ISSUE THREAD

**Issue by ahosseinich** [shentao/vue-multiselect#590]
i am new to vue and vue-multiselect
i want the text input remain when the user do not select any option, then he/she can edit the input parameter not retyping whole text again. is there any solution?

**Comment by davodaslanifakor** [comment]
I do not know way do that but fine some solution so test this...
first add ```:preserve-search="true"``` and then you must add some class in ```multiselect``` and then add method for close ``` @close="closed" ``` 
and write this method 

```
	closeDoc(param,id){
		var thisVal = document.querySelector(`.${id} input`).value
		var thisInput = document.querySelector(`.${id} input`)
		if (!param){
	            this.nameSearch = {fname:thisVal,lname:''}
		}
	},
```
i hope useful this solution...

**Comment by xxRockOnxx** [comment]
`:preserve-search` is not documented. Will try that.

**Comment by davodaslanifakor** [comment]
this is just for when time your v-modal don't has value but when you has value in v-modal 
and focus clear your input
