### ISSUE TITLE
Make background green when remove not allowed in search, and alter deselect-label

### ISSUE THREAD

**Issue by aske-cph** [shentao/vue-multiselect#594]
With singleselect when setting: 

    :allow-empty='false'

The already selected element still shows up with a red background when scrolling in the search, also the element still has the deselect-label "press enter to remove".

Why does the interface present an option to do something the user can't do? Nothing happens when it is pressed, so the option works as expected, but the interface confuses the user.

For now i have fixed by setting: 

    deselect-label="currently selected"

and overidding the red highlight so it still shows green background with css:

	.multiselect__option--selected.multiselect__option--highlight {
		background: #41b883 !important;
	}
	.multiselect__option--selected.multiselect__option--highlight::after {
		background: #41b883 !important;
	}

**Comment by Kocal** [comment]
I agree, it's really confusing ..
