### ISSUE TITLE
Feature: add event of scrollToBottom

### ISSUE THREAD

**Issue by aHxShUM** [shentao/vue-multiselect#601]
As pagination may be used for async select with a long list, it would support more use cases with this event.

Reference: [React-select](https://github.com/JedWatson/react-select) > `onMenuScrollToBottom`

**Comment by shentao** [comment]
On one hand, this seems useful, but on the other – if you can use search, why do you need pagination?
I believe that scrolling a select drop-down might be the least user-friendly experience for long lists.

**Comment by aHxShUM** [comment]
It is just a suggestion to cover more complicated use case.

1. the search in `vue-multiselect` is hard to be complicated.
2. when come to a long list, the search may not be effective.
3. and sometimes pagination is used as the list may be costly to be loaded completely.

FYR, you may try the input box at [Select2](https://select2.org/data-sources/ajax).

**Comment by zsimple** [comment]
+1

**Comment by ealcantara22** [comment]
+1

**Comment by teripaquitinho** [comment]
+ 1

**Comment by teripaquitinho** [comment]
hello @shentao  

I managed to have infinite scroll without a button by adding vue-observe-visibility to the afterList slot like this:

  <multiselect ... >
   [ ... ]
    <template slot="afterList">
      <div v-observe-visibility="reachedEndOfList" v-if="hasNextPage" />
    </template>
  </multiselect>
and

  reachedEndOfList(reached) {
    if (reached) {
      this.fetchNextPage();
    }
  }
more info here https://github.com/Akryum/vue-observe-visibility

hope this helps

**Comment by shentao** [comment]
This looks awesome! Thanks for sharing!

**Comment by roopika-rao** [comment]
@teripaquitinho Could you please elaborate on how did you make the afterList show up as multi-select options after the original list of options in the dropdown?

**Comment by pikachu-03** [comment]
@teripaquitinho 
Could you please elaborate on how did you make the afterList show up as continuation to the multi-select options after the original list of options in the dropdown?
