### ISSUE TITLE
Passing parameter to the @tag function for a special use case.

### ISSUE THREAD

**Issue by Arwany** [shentao/vue-multiselect#603]
Hi,

I added your vue-multiselect inside a loop and I would like to use the tagging feature [found here](https://vue-multiselect.js.org/#sub-tagging) in order to add new tags.

Here is an example:

https://jsfiddle.net/jqofkzxc/235/

The problem: I can't pass the `detective` parameter to the function `addAbility`.

I would like to be able to make the settings something like: 

`@tag="addAbility(newAbility, detective)"`

Currently I can only mention the function without passing any parameter (as per the docs), that's why the user must first add the item to the list, then again select it, which is really confusing.

I don't care if the new item is added to all lists or not.

**Comment by shentao** [comment]
Hey! This is already present. 
Please see the events docs: https://vue-multiselect.js.org/#sub-events

As you can see the `tag` event sends a second argument which is the `id` prop of the vue-multiselect. 

Here’s an edited version of your example that uses it: https://jsfiddle.net/fwfg557o/

Regards
