### ISSUE TITLE
Using option subproperty as option label

### ISSUE THREAD

**Issue by gerardreches** [shentao/vue-multiselect#605]
I'm using a [countries JSON](https://restcountries.eu/rest/v2/all?fields=name;alpha2Code;translations) as my options array. I want to use a translation of each object as the labels, but `label="translations.language"` doesn't work, the label appears empty.

Sample demo: https://jsfiddle.net/jqofkzxc/241/

How can I achieve this?

**Comment by shentao** [comment]
Hey! For that, you can use the `custom-label` prop. It can be a function that will return a custom label based on the option it gets as the first argument.

Here’s your updated example: https://jsfiddle.net/op3cwjww/
I also added a way to pick your current language so you can pick the language you want to translate the country names.

Here are the docs: https://vue-multiselect.js.org/#sub-select-with-search
