### ISSUE TITLE
Style not working on Multiple Select

### ISSUE THREAD

**Issue by nusendra** [shentao/vue-multiselect#608]
![screenshot from 2017-12-13 09-16-24](https://user-images.githubusercontent.com/8466308/33918531-7acb3dae-dfe6-11e7-9984-bdc286f75bdd.png)
my multiselect is not like the example
![screenshot from 2017-12-13 09-18-13](https://user-images.githubusercontent.com/8466308/33918564-a2aaea04-dfe6-11e7-9bb0-ab8966ca0b09.png)

I'm using Laravel vuejs with webpack
npm install vue-multiselect --save

help me please

**Comment by shentao** [comment]
Seems you have the CSS added properly. It might be that for some reason you have some additional custom CSS rules that override the default styles. Also, please make sure you’re not using the `slot="tag"` slot, as it’s not needed if you want default tags.
