### ISSUE TITLE
Feature: beforeDestroy event

### ISSUE THREAD

**Issue by gerardreches** [shentao/vue-multiselect#610]
Hi,

My `<vue-multiselect>` is rendered in a slot of a component that is dynamically rendered by `v-if="condition"`.

I need to reinitialize my `selectedOptions` array binded to the multiselect (`<vue-multiselect v-model="selectedOptions">`) when the componing is being destroyed.

Could it be possible to add a new `beforeDestroy` event to the component?

```
beforeDestroy: function () {
    this.$emit( 'beforeDestroy' );
},
```

So we can do something before the component is destroyed: 
```
<vue-multiselect v-model="selectedOptions" @beforeDestroy="selectedOptions = null">
```

I know that I could do something like make `condition` a computed property and reinitialize the array when it becomes *false*, but I really can't do something like that, because there could be more conditional renderings uppon that one, and I need to reinitialize `selectedOptions` every time the component is destroyed, regardless of the cause.

**Comment by shentao** [comment]
Sure. Feel free to add a PR for this. :)

**Comment by gerardreches** [comment]
Vue's `beforeDestroy` lifecycle hook doesn't work as expected in Chrome, for some reason it's executed on after the `mounted` hook. That doesn't happen on Firefox. So, for this proposal, `destroyed` should be used instead of `beforeDestroy`.

**Comment by otijhuis** [comment]
Isn't this possible with a custom directive? You could pass a function to the directive and have it call the function when executing the `unbind` hook. That hook gets called just before the component gets destroyed.
