### ISSUE TITLE
tabbing through a multiselect with a value already set

### ISSUE THREAD

**Issue by SmarterPhoneLabs** [shentao/vue-multiselect#617]
I have a vanilla instllation of vue-multiselect and I have made a video of my issue you can see here:

https://youtu.be/DJ28zFdX0F0

Basically what happens is if a user has set a value on a multiselect and then sets the focus "BRFORE" it and starts tabbling, when the multiselect gets focus,  the value gets reset to the topmost or bottommost value in the list depending where the mouse is located/.

**Comment by shentao** [comment]
Thanks for reporting. Will try to fix it before 3.0 :)
