### ISSUE TITLE
Append dropdown to body

### ISSUE THREAD

**Issue by Hauptsatana** [shentao/vue-multiselect#618]
Is it somehow possible to append dropdown list to body? I found nothing in docs.
I have `overflow: auto` container and would like to see `.multiselect__content-wrapper` over any other element
![multiselect](https://user-images.githubusercontent.com/4078263/34380397-f65bf71e-eb22-11e7-83b7-ddd90a92372a.png)

**Comment by shentao** [comment]
No plans for it right now, though I imagine it might be possible after the 3.0 release and something like vue-portal.

**Comment by talberkoSB** [comment]
+1

**Comment by talberkoSB** [comment]
I have a workaround. Wrap the multiselect element. add `ref=multiselect`, and use an event handler `@open` that will invoke this function:

```javascript
updateDropdownSize(){
	const ms = this.$refs.multiselect;
	ms.$refs.list.style.width = `${this.$el.clientWidth}px`;
	ms.$refs.list.style.position = 'fixed';
}
```

PS: You can also use on resize event to watch window resize, and invoke this function.

**Comment by csmoakpax8** [comment]
@talberkoSB thank you for this! I also added a scroll handler to move with the dropdown input

**Comment by alexbudure** [comment]
+1 You can also utilize a library like popper.js

**Comment by csmoakpax8** [comment]
@pdcmoreira Sorry for the delay. I have notifications turned off.

```js
mounted() {
  window.addEventListener('scroll', this.repositionDropDown);
},
destroyed() {
  window.removeEventListener('scroll', this.repositionDropDown);
},
```
```js
repositionDropDown() {
  const { top, height } = this.$el.getBoundingClientRect();
  const ref = this.$refs[`multiselect-${this.id}`];
  ref.$refs.list.style.width = `${this.$el.clientWidth}px`;
  ref.$refs.list.style.position = 'fixed';
  ref.$refs.list.style.bottom = 'auto';
  ref.$refs.list.style.top = `${top + height}px`;
},
```

I also have `@open` event call the `repositionDropDown` method.

**Comment by pdcmoreira** [comment]
@csmoakpax8 Thanks for sharing. I went with kind of a similar approach.

**Comment by SmelayaPanda** [comment]
Vue.component('multiselect', VueMultiselect)

overrided multiselect **VueMultiselect.vue**:

`<template>
    <vue-multiselect-original
        :ref="$attrs.id"
        v-bind="$attrs"
        v-on="listeners"
        class="position-relative"/>
</template>

<script>
    import Multiselect from 'vue-multiselect'

    export default {
        props: {
            reposition: {
                type: Boolean,
                default: false
            }
        },
        components: {
            'vue-multiselect-original': Multiselect
        },
        computed: {
            listeners() {
                return {
                    ...this.$listeners,
                    open: () => this.onOpen()
                }
            }
        },
        methods: {
            onOpen() {
                if (this.reposition) {
                    if (!this.$attrs.id) {
                        console.error('No multiselect id')
                        return
                    }
                    const {top, height, width, left} = this.$el.getBoundingClientRect()
                    const ref = this.$refs[this.$attrs.id]
                    if (ref) {
                        ref.$refs.list.style.width = `${width}px`
                        ref.$refs.list.style.position = 'fixed'
                        ref.$refs.list.style.bottom = 'auto'
                        ref.$refs.list.style.top = `${top + height}px`
                        ref.$refs.list.style.left = `${left}px`
                    }
                }
            }
        }
    }
</script>
`

**Comment by shentao** [comment]
This is now on the current 3.0 release todo list, once the a11y issues have been solved. Shouldn’t be long!

**Comment by ryzhak-andrii** [comment]
@SmelayaPanda this solution doesn't cover the case if a dropdown placed in the horizontal scrollable element
![Screenshot 2021-05-06 at 14 35 19](https://user-images.githubusercontent.com/55483532/117291986-54fb5c80-ae78-11eb-87f0-6fcde6edfa48.png)

**Comment by entioentio** [comment]
@ryzhak-andrii I've stumbled upon similar problem. Check out my gist inspired by all comments above: https://gist.github.com/entioentio/83e4bd4f759669eda6898292544e3e52

**Comment by eybarta** [comment]
@shentao 
Hey man, thanks for all your work!
Do we have a built-in solution for this issue yet?
thx 🙏

**Comment by shentao** [comment]
Sadly not at the moment. :(

**Comment by KaloyanYosifov** [comment]
Thank you for the snippet @hamonCordova 

Using it works fine, except whenever we have to show the select (above) and there were some flickering issues.

---

Here is the revised snippet if it helps anybody: 

```
const wrapperClass = '.multiselect__content-wrapper';

const calculateBase = (el) => {
  const wrapperElement = el.querySelector(wrapperClass);

  wrapperElement.style.width = `${el.clientWidth}px`;
  wrapperElement.style.position = 'fixed';
  wrapperElement.style.bottom = 'auto';
};
const calculateWrapperPosition = (el) => {
  const { top, height } = el.getBoundingClientRect();
  const wrapperElement = el.querySelector(wrapperClass);
  const wrapperHeight = wrapperElement.getBoundingClientRect().height;
  const isAbove = el.classList.contains('multiselect--above');

  const newTop = isAbove ? top + 2 - wrapperHeight : top + height;

  if (newTop === 0) {
    return;
  }

  wrapperElement.style.top = `${newTop}px`;
};

/**
 * Unfortunately vue-multiselect does not support being appended to another element
 * since we use multiselect in modals, and the modals can be small, the select is not visible
 * to mitigate this we create a custom directive to append multiselect to another place, so that it is visible
 * even in small modals
 *
 * Inspired by a comment in vue-multiselect issue
 * @see https://github.com/shentao/vue-multiselect/issues/618#issuecomment-1597431685
 */
const directive {
  beforeMount(el, binding) {
    const parentElement = document.querySelector(binding.value);

    const calculatePositionCallback = () => calculateWrapperPosition(el);

    calculatePositionCallback();

    // Store the callback function on the element itself.
    el._calculatePositionCallback = calculatePositionCallback;

    if (parentElement) {
      parentElement.addEventListener('scroll', calculatePositionCallback);

      // Create a new MutationObserver that recalculates the position when the children of parentElement are modified.
      const observer = new MutationObserver(calculatePositionCallback);
      // Start observing parentElement for childList changes.
      observer.observe(parentElement, { childList: true });

      // Store the MutationObserver on the element itself, so we can disconnect it later.
      el._observer = observer;
    }

    document.addEventListener('scroll', calculatePositionCallback);
  },
  mounted(el) {
    calculateBase(el);
  },
  updated(el) {
    if (!el?.classList?.contains('multiselect--active')) {
      return;
    }

    el?._calculatePositionCallback();
  },
  beforeUnmount(el, binding) {
    const parentElement = document.querySelector(binding.value);

    // Disconnect the MutationObserver.
    el._observer?.disconnect();

    parentElement?.removeEventListener('scroll', el._calculatePositionCallback);
    document.removeEventListener('scroll', el._calculatePositionCallback);

    // clean up styles on unmount
    const wrapperElement = el.querySelector(wrapperClass);
    wrapperElement.style.width = '';
    wrapperElement.style.position = '';
    wrapperElement.style.top = '';
    wrapperElement.style.bottom = '';
  },
};

  // use the `createApp` instance to set directive
  app.directive('floating-select', directive)
```

Use:

`<Multiselect v-floating-select ...`

Optionally with an element: 

`<Multiselect v-floating-select="body" ...`

or

`<Multiselect v-floating-select=".a-parent" ...`
