### ISSUE TITLE
[Bug] TextInput doesn't disappear unless :value is specified

### ISSUE THREAD

**Issue by danielbastos11** [shentao/vue-multiselect#619]
### What is the problem

The expected behaviour is to have the `.Multiselect__input` go away when Multiselect is closed, by setting its style to `width: 0` (according to [Mutiselect.vue, ln256](https://github.com/shentao/vue-multiselect/blob/master/src/Multiselect.vue#L256)). However, unless the user specifies a `:value` prop, this won't happen.

While I do understand that in most cases the user will provide the prop either directly or through `v-model`, I have run into use cases where I didn't have to do it, and it took me hours to figure out while the Input wasn't going away.

### Demo

I've made this JSFiddle: https://jsfiddle.net/danielbastos/1qxq19g0/1/

### Possible solution

Maybe we could use `internalValue` instead of `value` to calculate the Input style in [Multiselect.vue, ln254](https://github.com/shentao/vue-multiselect/blob/master/src/Multiselect.vue#L254)

**Comment by shentao** [comment]
I think this is already fixed on master branch. Let me know if it’s not. Preparing a release.
