### ISSUE TITLE
when :tagging=true, why is @tag=addTag necessary to update the v-model reference?

### ISSUE THREAD

**Issue by akhoury** [shentao/vue-multiselect#621]
I am under the impression that `v-model` will provide a 2-way data-binding to its `data` reference, so i think it would make sense, when I add a tag, even if it's not in the `:options` to still auto-push it to the referenced `array` in `v-model` attribute?

However, if you comment out this line below `this.list.push(tag);` the `data.list` never gets updated __when you select a NEW tag__ that does not exists in the `data.options`

```html
 <multiselect 
    v-model="list" 
    :options="options"
    :multiple="true"
    :taggable="true"
    :searchable="true"
    @tag="addTag"
    >
```
```javascript
// ... trimmed
  data: {
  	list: [],
  	options: ['abc', 'vue', 'vuemutlselect']
  },
  methods: {
  	addTag(tag) {
                // why is this line necessary? isn't updating the list implied by v-model?
   		this.list.push(tag);
        }
  }
// .... trimmed
```

Working fiddle
https://jsfiddle.net/c86n383x/1/

**Comment by tungserver** [comment]
Exactly, This will a problem when using this component in loop because no way to add new item to selected list

**Comment by shentao** [comment]
This is necessary because the component can’t predict how to construct a tag when the option list is an array of objects.

@tungserver you can figure out which component called the `addTag` method by the 2nd param which is `id` that you can pass to the component.

For example in a loop:
```
<div v-for="(item, index) of items">
  <multiselect v-model="item.value" :options="item.options" @tag="addTag" :id="index"/>
</div>
```

```
addTag (tag, index) {
  this.items[index].value.push(tag)
  this.items[index].options.push(tag)
}
```

**Comment by mkantautas** [comment]
@shentao What if I have multiple multiselects in my loop? Need to not only pass the index, but also the attribute name via the `:id` then? 😂
