### ISSUE TITLE
Odd behaving of dropdown

### ISSUE THREAD

**Issue by mautone89** [shentao/vue-multiselect#623]
Anyone who can point me in the right directions of when using keyboard arrows to navigate in the dropdown, the selected <li> element disappear when I'm reaching a point.
![create](https://user-images.githubusercontent.com/4007209/34518254-ec941df4-f07e-11e7-9657-a00c49263b57.png)
If you look at the image, the dropdown I'm at the bottom, but it does not show.

Anybody having the same issue?

**Comment by shentao** [comment]
It seems your options have a different height than the default ones. Please see the `:option-height` property: https://vue-multiselect.js.org/#sub-custom-option-template
