### ISSUE TITLE
CaseSensitive Search

### ISSUE THREAD

**Issue by ayaz323** [shentao/vue-multiselect#624]
Hey, 
I'm searching "istanbul" but my data "İstanbul" so first letter is Capital letter and so does not find result, How can I fixed ? 

thanks

https://imgur.com/a/NJOC4

**Comment by abdujuk** [comment]
+

**Comment by shentao** [comment]
This problem is not related to case sensitivity.
`İ` is a different letter than `i` or `I`.
 Please implement your own filtering and disable `internal-search`. See docs for example: https://vue-multiselect.js.org/#sub-asynchronous-select
