### ISSUE TITLE
Group Label with icon

### ISSUE THREAD

**Issue by bernardocs** [shentao/vue-multiselect#626]
Hey guys!

As the title of the issue suggests I'm trying **really** hard to override the `option` slot (like proposed at #485 ) to get this kind of result:
![image](https://user-images.githubusercontent.com/513789/34893378-077ae89a-f7c4-11e7-8972-4f09dc067d10.png)

And because of [multiselectMixin.js#47](https://github.com/shentao/vue-multiselect/blob/master/lib/multiselectMixin.js#L47) I simply **can't** pass on another property (say... `icon`, containing the name of the icon to be concatenated with the string `"fa-"`). Like this:
```javascript
// options that will go on `options` multiselect attribute
options: [
  {
    label: 'The Group Label',
    icon: 'location-arrow', // an extra property
    options: [
      // this group options
    ]
  }
]
```

Instead, the `option` object turns to be something like this:
```json
{
  "$groupLabel": "The Group Label that I've defined",
  "$isLabel": true
}
```
... even if I put a bunch of extra useful properties there...

What can I do to make this happen? :confused:

**Comment by shentao** [comment]
You can use the `option` slot. It also applies to the option group label.
