### ISSUE TITLE
Default local options with AJAX

### ISSUE THREAD

**Issue by vanpet** [shentao/vue-multiselect#630]
I don't know how to implement the follwing functionality:

- when the component load, I want to fill the options from a local array that the user can select by clicking in the list.
- when the user starts to type in the search box, I want to replace the options with those returned by the AJAX server.

It this possible?

**Comment by mt89vein** [comment]
Yes, you can.

Make a wrapper-component to vue-multiselect and pass prop to him "options"
``` javascript
props: {
   options: {
       type: Array,
       required: false,
       default () { 
         return [] 
       }
   }
}
```
then in data declare empty array "loadedOptions: []" and timer for debounce

```javascript
data () {
    return {
        loadedOptions: [],
        debounceTimer: null
    }
}
```
then on @search-change event attach event listener, which will send ajax requests to server:
p.s. as an optimization you also need to add debounce, to prevent much count of requests on key pressing :)
```javascript
asyncFind(query) {
    if (query.match(/^\s*$/)) {
       return
    }
    this.isLoading = true
    clearTimeout(this.debounceTimer)
    this.debounceTimer = setTimeout(() => {
        axios.get(url, params)
                .then(response => { 
                    this.loadedOptions = response.data
                    this.options = []
                    this.isLoading = false
                })
	}, 500)
}
```

computed property, it will choose which of datasource to use. After first success ajax request, ```this.options``` will be an empty array, and vue-multiselect use ```this.loadedOptions```:

```javascript
computed: {
   currentOptions () {
      return this.options.length > 0 ? this.options : this.loadedOptions
   }
}
```
and pass currentOptions property to vue-multiselect as :options
