### ISSUE TITLE
When clicking on <label> it does not trigger multiselect element

### ISSUE THREAD

**Issue by LAUVz** [shentao/vue-multiselect#631]
When clicking on `<label>` it does not trigger multiselect. It's obvious that this will not work as it does not use standard form elements as the base. Would it be possible to create this behaviour with multiselect?

https://jsfiddle.net/kps0hj2z/

**Comment by shentao** [comment]
It does work if you pass the `id` prop.
https://jsfiddle.net/shentao/bq3rafmo/
