### ISSUE TITLE
Text in :options are not reactive with vue-i18n

### ISSUE THREAD

**Issue by DaxChen** [shentao/vue-multiselect#636]
https://jsfiddle.net/daxchen/quefhq9p/4/

As in the repro, the selected label is not reactive, when locale changes.

Is there a workaround to force-rerender / force-update the label?

Great thanks!

**Comment by DaxChen** [comment]
Maybe related to https://github.com/shentao/vue-multiselect/issues/578?

**Comment by shentao** [comment]
Sadly it might related to the above problem. Can’t think of a workaround now.

**Comment by shentao** [comment]
This should be fixed on the current master since the component finally skips deepCloning :) Working on a release.
