### ISSUE TITLE
options exceed container width

### ISSUE THREAD

**Issue by johannes-z** [shentao/vue-multiselect#641]
# Reproduction Fiddle

https://jsfiddle.net/xp7xsc6z/1/

# Issue

When the container of the `multiselect` is of limited width, any selected option that it's longer than the container width exceeds the container. The option should have `max-width` set and something like `text-overflow: ellipsis`

**Comment by shentao** [comment]
Sounds very reasonable! Would you like to create a PR with those changes?

**Comment by johannes-z** [comment]
This is actually already implemented in `2.0.7`. The jsfiddle points to version `2.0.3`. Closing this as resolved.
