### ISSUE TITLE
tokenize search

### ISSUE THREAD

**Issue by thejams** [shentao/vue-multiselect#644]
lets asume that the options of the select have an array of objects with the following info: "user.firstName", "user.lastName".
Example: "user.firstName" = "Jose Alfredo", "user.lastName" = "Montero Subero".
How can i make that the search query return the previously specified user by typing "Jose Montero"

**Comment by shentao** [comment]
Disable `internal-search` and filter it yourself using the `@search-change` event. Example: https://vue-multiselect.js.org/#sub-asynchronous-select

**Comment by thejams** [comment]
Yes, what i did was use the "@search-change" event and add my own logic for the search and work just fine, thank you very much for your response.
