### ISSUE TITLE
Sortable tags

### ISSUE THREAD

**Issue by gemp** [shentao/vue-multiselect#651]
Following issue #26 could it be possible to make the div `.multiselect__tags` a slot to be able to add a `v-sortable` directive to its template using [vue-sortable](https://github.com/sagalbot/vue-sortable) (or another)?

It works using jQuery `$('.multiselect__tags-wrap').sortable()` but it needs a dirty hack to link to the Vue data.

PS: The [documentation slots' list](https://vue-multiselect.js.org/#sub-slots) apparently lacks three of them: clear, loading and tag. The last one is prettyyyy useful (tho [documented elsewhere](https://vue-multiselect.js.org/#sub-multiple-select)) 😊

PPS: ❤️

**Comment by shentao** [comment]
I think you can try to sort the `value` prop. For example instead of passing the raw value you can pass a sorted, computed property. It should affect the order of the tags.

**Comment by gemp** [comment]
Yes, that's the «dirty hack» I mentioned. But in order to work as intended, out of the box, `v-sortable` needs to be applied directly on the list you want to make sortable. Therefore a slot would be required. (I looked at the code to see if I could implement it myself, but it's waaay out of my league.)
