### ISSUE TITLE
Can we have  v-on:change function?

### ISSUE THREAD

**Issue by vishal2947** [shentao/vue-multiselect#653]
I am trying to implement a function which will invoke whenever a user selects or removes the item. Do we have "change" or similar functionality?

**Comment by gemp** [comment]
```javascript
methods: {
  selectItem: function(item) { /* do something with selected item */ },
  removeItem: function(item) { /* do something with removed item */ }
},
template: '<multiselect @select="selectItem" @remove="removeItem" ... />'
```

**Comment by shentao** [comment]
As @gemp mentioned. You can also use `@input` which is called whenever the value changes.

**Comment by mariusa** [comment]
`@input` doesn't work. 
`@select / @remove` do work
