### ISSUE TITLE
Multiselect content z-index bug 

### ISSUE THREAD

**Issue by burlakko** [shentao/vue-multiselect#662]
Default z-index of multiselect content is 1. If there is another element with higher z-index nearby it always appears above multiselect content.
To set a higher z-index to multiselect__content-wrapper class should help but it does not.
Here is a fiddle: [https://jsfiddle.net/burlakko/qj7xovms/18/](https://jsfiddle.net/burlakko/qj7xovms/18/)

Setting higher z-index to it's descendants also doesn't help
`.multiselect__content-wrapper * {position: relative; z-index: 6;}`

**Comment by m0ngr31** [comment]
Same issue here

**Comment by shentao** [comment]
Add
```
.multiselect--active {
  z-index: 10;
}
```

This also doesn’t happen on the current master, thus it should be fixed in the new release.

**Comment by doncatnip** [comment]
I suppose this hasn't been fixed in 2.1.0 yet.
.multiselect z-index defaults to 9
.multiselect--active defaults to 1
This means that active multiselects will always be below inactive ones.

**Comment by vmarcelo** [comment]
Hi everyone

The error continues to appear, I recommend that you modify the z-index but in 2 css tags: vue-multiselect.min.css

Style CSS:
.multiselect--active => z-index: 20
.multiselect__content-wrapper => z-index: 20

In my case I only put 20, because in my project I have another z-index.
Thank you

**Comment by laurent-brisbois** [comment]
On my side I use Vuetify and the multiselect is in a v-toolbar.
The only way I've found is to do this :

```css
.v-toolbar {
  z-index: 10;
}
```
Otherwise nothing worked.
