### ISSUE TITLE
Keeping currently selected option visible during dropdown?

### ISSUE THREAD

**Issue by ggJSC** [shentao/vue-multiselect#663]
Is there a way to not clear the value of `.multiselect__input` when multiselect is activated? I'd prefer to have the currently selected value stay showing instead of the the placeholder `"Select option"` (in the default case).

**Comment by shentao** [comment]
This already works as described if `searchable` is false. Otherwise we need that space for the search input. You can see the currently selected value highlighted in the dropdown.
