### ISSUE TITLE
How to customize selected item display in textbox but not change dropdown custom label

### ISSUE THREAD

**Issue by kevinding0218** [shentao/vue-multiselect#668]
Hi, this is the greatest multi select I've seen so far!
I have a question regarding format selected item, I know there is a prop method of customLabel, but this method will format both selected item and dropdown item, 
e.g
https://jsfiddle.net/shentao/c4L3gs91/

Current selected item in dropdown box is `${option.library} - ${option.language}` (like "Vue-Multiselect - Javascript"), what I want in dropdown box is only the '${option.library}'(like 'Vue-Multiselect'), is there any way to achieve that?

Thanks in advance!
Best

**Comment by shentao** [comment]
Thanks for the kind words!

You can use the custom option slot for that:
https://vue-multiselect.js.org/#sub-custom-option-template

I’m also working on the next release that will also include a slot for single selected value.
