### ISSUE TITLE
Customize Dropdown list width

### ISSUE THREAD

**Issue by kevinding0218** [shentao/vue-multiselect#669]
Hello, I am new to Vue.js and I really love this api! Well I have some options text in a long string while currently I have to make my multiselect to be 140px as the dropdown list width always keep same as the control, therefore it takes more space in my UI otherwise my user won't see entire description in the dropdown list item.
Is there an example or prop to customize the dropdown list width? Like my multiselect is '80px' but the dropdown list width would be able to set to '140px'? So when user expand the dropdown they would be able to see full text while the label box only stays at '80px' 

Best

**Comment by shentao** [comment]
You can add a `min-width: 140px;` rule for `.multiselect__content` class.

Example: https://jsfiddle.net/kcff8k7c/

**Comment by kevinding0218** [comment]
@shentao , thank you very much! It looks great on the example you provided, however, when I apply the same css on my page, it's not working as expected, the dropdown width did expand, but it looks same as the label box while it adds a horizontal scroll bar...
![image](https://user-images.githubusercontent.com/13737436/37357059-d0e2ad94-26bd-11e8-8f0c-88e92d4685e3.png)
As you can see the screenshot(I know it looks awful..please let me know so I can create an individual example to clarify more), the "STATE" dropdown does not have the horizontal scrollbar before I add the "min-width" option, but now it does after I add the css, 
is that because I am using bootstrap? My multiselect was placed in:
<div class="col-lg-2">
   <multiselect...></multiselect>
</div>

Best

**Comment by kevinding0218** [comment]
@shentao , I have figured out the issue, it's because the vue-multiselect.min.css is different from the one that I used from the CDN...
