### ISSUE TITLE
Option to auto-select first result

### ISSUE THREAD

**Issue by iamvitali** [shentao/vue-multiselect#674]
Don't think this is implemented yet?

Sometimes it's really nice to be able to set the default selected value, and even though I thought `:allow-empty="false"` would do it it's still a good thing that it doesn't (as it has a different purpose).

Would be nice to have something like `auto-select="first"` or `:auto-select-first="true"` or something like that. :grin:

**Comment by shentao** [comment]
This might be quite convenient. Although I don’t want to further expand the API, this change seems not to be to intrusive or hard to maintain.
