### ISSUE TITLE
[DOM] Found 2 elements with non-unique id #ajax

### ISSUE THREAD

**Issue by GMounir** [shentao/vue-multiselect#676]
Chrome throw this error in the console

[DOM] Found 2 elements with non-unique id #ajax: (More info: https://goo.gl/9p2vKq) <input name id=​"ajax" type=​"text" autocomplete=​"off"  tabindex=​"0" class=​"multiselect__input">​ <input name id=​"ajax" type=​"text" autocomplete=​"off"  tabindex=​"0" class=​"multiselect__input">​

**Comment by shentao** [comment]
Thanks! :) Gonna fix it in the docs.
