### ISSUE TITLE
Vue-Multiselect is support tree categories

### ISSUE THREAD

**Issue by kayota2203** [shentao/vue-multiselect#678]
Dear,

I find the component same select 2. 
But i have a problem with data tree categories. It's not show child data.

Can you help me?

Thanks

**Comment by shentao** [comment]
Hello :) Please provide some more data. A JSFiddle example would be best. Then I might be able to help.
Thanks

**Comment by kayota2203** [comment]
Hello shentao,

here is Example data

```
$array = [
	{
		'name' => 'Cat 1',
		'slug' => 'cat-1',
		'childs' => [
			{
			'name' => 'Child Cat 1',
			'slug' => 'child-cat-1',
			'childs' => [{
				'name => 'Sub Child Cat 1'
				'slug => 'sub-child-cat-1'
			}],
			},
			{
			'name' => 'Child Cat 2',
			'slug' => 'child-cat-2',
			}
		]
	},
	{
	'name' => 'Cat 2',
	'slug' => 'cat-2'
	}
]
```

Thanks for response

**Comment by mt89vein** [comment]
@kayota2203 #465
