### ISSUE TITLE
Width to fit selected item

### ISSUE THREAD

**Issue by Max64** [shentao/vue-multiselect#680]
Can't get component in single-select mode to fit selected option's width.
I tried this CSS but it doesn't work

https://jsfiddle.net/au1k8tq5/4/

**Comment by shentao** [comment]
Not sure what you mean. Maybe try setting the `show-labels` to `false`?
https://jsfiddle.net/shentao/o6xh6g23/

**Comment by Max64** [comment]
Sorry if I didn't explained clearly, I mean when selected option with any text length, I want container to fit selected option's width. By default container has 100% width, this is not suitable for my app. In my fiddle with given CSS, long option get cropped:

![modal-error](https://user-images.githubusercontent.com/3396808/37566721-1f452bf6-2ace-11e8-989d-86a9e2dc04c5.png)

**Comment by shentao** [comment]
This is fixed in the newest master (still to be released to NPM) when you add `width: fit-content;` to `.multiselect` class.

Please wait for the new release or download the sources and build it yourself.
