### ISSUE TITLE
Option Groups

### ISSUE THREAD

**Issue by Freddie-Banks** [shentao/vue-multiselect#683]
Hi! Just a quick question. We need to use option groups to allow a user to select different types of data. I have looked through the documentation and see that it is possible with multiselect. However, is it possible to allow a user to only pick one option within each option group, instead of all the options in one group.

**Comment by shentao** [comment]
Please see: https://vue-multiselect.js.org/#sub-option-groups

You should be able to only allow for 1 option from each group if you manually handle the `@input` event and decide whether to update the `value` or not.

I’m working on a new release (form current master) that should make that easier.
