### ISSUE TITLE
Remotely change search query value 

### ISSUE THREAD

**Issue by GMounir** [shentao/vue-multiselect#684]
Hello buddy,
 is there a way to change query value (e.g dd to dd-) and display it in the input

**Comment by shentao** [comment]
Not in this version. This might be possible in the incoming v3.0.

**Comment by GMounir** [comment]
Ok thank, so i have no solution right now :(!!

**Comment by TomFranssen** [comment]
You can do this using the created Vue state:

`            created: function () {
                var that = this;
                setTimeout(function () {
                    that.$emit().$children[0].activate();
                    that.$emit().$children[0].updateSearch('Search query');
                })
            }`

**Comment by AlanVerne** [comment]
Hi, GMounir, Tim. Can't understand how it works.
I need something like 
`this.$refs.mymultiselect.updateSearch('Search query');`

**Comment by AlanVerne** [comment]
lol, it works)
