### ISSUE TITLE
Options dropdown without horizontal scrollbar

### ISSUE THREAD

**Issue by Max64** [shentao/vue-multiselect#687]
I'm trying to apply styles to make options dropdown list be same width as most wide option. I achieved this, but can't get .multiselect__option be same width as parent .multiselect__element:

https://jsfiddle.net/xo9f7jby/30/

Can this be achieved anyway?

**Comment by Max64** [comment]
Issue solvved:
https://stackoverflow.com/questions/49499878

Working fiddle:
https://jsfiddle.net/xo9f7jby/33/

In my opinion it would be useful to create something like styling recipes in docs with examples like this.

**Comment by shentao** [comment]
Sure, I will accept more examples for the docs anytime :)
