### ISSUE TITLE
Post-selection focus does not work

### ISSUE THREAD

**Issue by mkampa** [shentao/vue-multiselect#690]
Updated: If i have two single selects (with search). I want to select a value in the first field. After that I want to switch to the next field using the tab key. 
While i was using vue-multiselect v.2.0.3 it did not work on Safari but on Chrome and Firefox it worked fine. On v.2.1.0 tabbing does not work on any Browser.

**Comment by shentao** [comment]
Thanks for creating the issue! I think this might be related to the "simplification" I did to the input element inside Multiselect. I’m currently working on the 3.0 release so if someone would want to fix this – I would gladly accept a PR.
