### ISSUE TITLE
Allow multiple selections, but with no tags. :limit doesnt really help [workaround]

### ISSUE THREAD

**Issue by sourenaraya** [shentao/vue-multiselect#691]
What i am trying to achieve, is select with fixed height. 
Something like 
![fixed height](https://user-images.githubusercontent.com/3405082/32716370-6c9e5a92-c8a1-11e7-8e50-04b06576dd29.png)

The problem with ` :limit ` is: select doubles the height, which is not what i want.
Top half is whatever in `limit` slot, botton half is placeholder.

Any suggestions how to make it inline?

#580 is kind of related.

**Comment by sourenaraya** [comment]
Ok, this is what i'm came up with:
I've created component, that extend VueMultiselect, and overrides a couple of things.
```html
<script>
    import Multiselect from 'vue-multiselect'

    export default {
        extends: Multiselect,
        name: "vue-multiselect",
        props: {
            limitText: {
                type: Function,
                default: function (count) {
                    return `${this.placeholder} (${count})`
                }
            },

        },
        computed: {

            isSingleLabelVisible () {
                return this.singleValue &&
                    (!this.isOpen || !this.searchable) &&
                    (!this.visibleValues.length && this.limit > 0)
            },
        },
    }
</script>
```

**Comment by HenSei** [comment]
Thank you for your feedback and the workaround! Have you done the extension in the same component where you also use the multiselect? Because I get some errors that some other props would be missing which are required in VueMultiselect. Maybe you could provide a more detailed example. Would be create. Thank you!!

**Comment by sourenaraya** [comment]
I've created MyMultiselect.vue, which contains code from comment above.
This component can be imported and used like any other component.

The only change needed In component where i used vue-multiselect, were import path. Instead of importing global vue-multiselect (from node_modules), import from local .vue component.

**Comment by HenSei** [comment]
Cool, is working. Thank you very much!

**Comment by TrendyTim** [comment]
Is there any possibility of getting the ability to turn off the singleLabel (even by making the computed a getter and setter for isSingleLabelVisible if you want) without having to resort to the extender.

I have searchable = false, limit = 0 to hide the tags, show the single selected item text if one and the count if multiple.

The way it is, it affects the height pushing content around  and even if it didnt do that having it appear at the end would look weird) just looks weird

https://jsfiddle.net/jqofkzxc/3059/

The solution provided by @sourenaraya is perfect from a UI POV, although id rather not need to have to have the wrapper (or fork it) just for this functionality, having it baked in makes sense (and it would only cost a few bytes).

**Comment by shentao** [comment]
That’s an interesting case. Should be possible to do much easier in 3.0.
