### ISSUE TITLE
Not showing placeholder label for single select

### ISSUE THREAD

**Issue by akki-jat** [shentao/vue-multiselect#692]
Hi,
In my current project, I am using vue-multiselect and facing problem while using single select .
> no :multiple attribute

Example : 

![html_code](https://user-images.githubusercontent.com/26685162/38081833-ff028a08-3312-11e8-86cc-472b903532fe.png)

Problem is it is not showing the placeholder. 
Here is screenshot:

![searchform](https://user-images.githubusercontent.com/26685162/38082002-6f73e84a-3313-11e8-94cc-75dede2120b1.png)

And for more debugging here is screenshot of console:

![console](https://user-images.githubusercontent.com/26685162/38082053-917616d4-3313-11e8-927e-934e292e233d.png)

Please help me with this..ASAP

**After updating to version 2.1.0**, placeholder is displayed but now it not showing selected value as you can see here :

![image](https://user-images.githubusercontent.com/26685162/38128659-792e158e-33c9-11e8-9ea8-96ef72ceb89a.png)

And i have selected the value as you can in `<span>` here :

![image](https://user-images.githubusercontent.com/26685162/38128699-ade7c126-33c9-11e8-9b3d-34f119b8872a.png)

**Comment by sourenaraya** [comment]
Empty :value should be [].

**Comment by akki-jat** [comment]
@sourenaraya thanks for reply.
In my case :value is {} because it is it is single select

**Comment by sourenaraya** [comment]
yes, i think its better to have {} as empty value in case of single select, but this component only support [] as empty value.

**Comment by akki-jat** [comment]
@sourenaraya thanks for your concern but dropdown values are showing just fine but problem is that placeholder is not displayed.

**Comment by sourenaraya** [comment]
just set value in data to empty array. DO IT!

**Comment by akki-jat** [comment]
@sourenaraya I tried that no luck. And I have one more concern, as you can see in screenshot of console there is `<span>` tag appearing which is not appearing for other all multi selects.

**Comment by akki-jat** [comment]
@sourenaraya you are right setting it as empty array is worked.
As before I tested it, it was in influence of another custom class.
Thanks @sourenaraya
