### ISSUE TITLE
Placeholder always shown if prop limit = 0

### ISSUE THREAD

**Issue by HenSei** [shentao/vue-multiselect#693]
Hey, 
if I use multiselect with the prop limit: 0, the placeholder is always shown, although I have already selected a couple of elements. Is there a way to fix that?

Thanks a lot for any help!

![image](https://user-images.githubusercontent.com/8431183/38140336-995aa3da-3433-11e8-9830-34e8228b07d4.png)

**Comment by sourenaraya** [comment]
See #691 for workaround.
