### ISSUE TITLE
custom-label usage

### ISSUE THREAD

**Issue by plweil** [shentao/vue-multiselect#694]
I'm having some trouble figuring out how to use the custom-label. I need for my select list to read 'city_name (county_name)'. For :options I am using an array of city objects('cities') with these properties:

id
city_name,
county {
county_name
county_id
}

How do I use custom-label to get the county_name?

**Comment by sourenaraya** [comment]
Did you read the [docs](https://vue-multiselect.js.org/#sub-custom-option-template)?

**Comment by shentao** [comment]
Please read the docs.

**Comment by plweil** [comment]
To be clear, I did the read the docs. It was my issue: I thought I was having difficulty with the template literals, but my problem was solved by checking for records where properties are null. Thanks.
