### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Uffman** [shentao/vue-multiselect#696]
How can I make package work in typescript?

I am getting an error:

> Could not find a declaration file for module 'vue-multiselect'. '/node_modules/vue-multiselect/dist/vue-multiselect.min.js' implicitly has an 'any' type.
  Try `npm install @types/vue-multiselect` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-multiselect';`

**Comment by shentao** [comment]
Create a PR with typings :)

**Comment by atilkan** [comment]
@shentao It is much harder for an outsider to write typings. It is best to be done by the author. 🥇 

https://medium.com/jexia/how-to-manage-type-definition-files-for-third-party-libraries-for-your-typescript-project-8640960f1342

**Comment by atilkan** [comment]
Thanks for the first step
