### ISSUE TITLE
Display Empty Options Message

### ISSUE THREAD

**Issue by MannikJ** [shentao/vue-multiselect#698]
Hi!
As the title says I would like to display a message within the multiselect (like the no results message) that is displayed when the options list is empty. I would like to be able to customize how this is displayed via props and slots. Actually it would be ok for now, if the no results message would be shown without typing any search parameter.
Just a small jsfiddle to show the situation in which this message should be displayed:
https://jsfiddle.net/zczy28g2/1/
Maybe I'm just missing something that is already there...

**Comment by shentao** [comment]
PR merged.
