### ISSUE TITLE
Can i prevent opening the multiselect by clicking and set a min length for searching?

### ISSUE THREAD

**Issue by kleusch** [shentao/vue-multiselect#703]
Hi, 

thanks for this great plugin.

I wonder if I could achieve the following things.

1. I want to disable the click -> open feature and use it as a plain autocomplete input (only open on input event). Is there a way to do this?

2. I want a minimum length of characters when searching. So if you type "a" there should nothing triggered. At a certain length (e.g. 3) the search should be triggered and display.

Is this possible?

**Comment by shentao** [comment]
Programmatic opening/closing is one of the improvements I want to introduce in 3.0. 

As for now, you can try to use the async-search and not return anything when the search input is empty thus it should appear closed.

**Comment by sarojmjn** [comment]
Is there any other options for opening and closing?

**Comment by cssagogo** [comment]
Is there a fancy way to do 2) above?  Or do we just wrap the asyncFind contents in a length check and return null if not large enough?

**Comment by shovan-techlogicians** [comment]
Yes  you can pass event variable like this `@search-change="getAllEmails($event)"`

and then prevent the api call by checking the value of "query" variable 
like `if(query>4){
"your api call"
}`
