### ISSUE TITLE
Is it possible to change Selected to Icon ?

### ISSUE THREAD

**Issue by TomePale** [shentao/vue-multiselect#705]
Hello there,

is it possible to change the Selected placeholder to be an icon instead of text upon selecting in Multi-select list? Currently, the default is :selectedLabel -> Selected

Regards,
Tome

**Comment by TomePale** [comment]
@shentao Any solution to my question, please...?

**Comment by shentao** [comment]
Sadly I’m not sure if this is possible. You might try using custom option slot and disable the default selected label. Then you might be able to introduce your own selected indicator.

**Comment by TomePale** [comment]
Hm ok, thx for your answer ;)

**Comment by andywd7** [comment]
I'm just trying to the exact same thing! I was trying to just do a v-if="selected" on the icon in option slot.

But I am struggling to workout how to find out if an item is selected?

Any help would greatly be appreciated?

Thanks

**Comment by blyleven** [comment]
@andywd7 I know it's a bit of an old issue, but I just tried to do the same thing. For future reference, I've done this by adding the template:

```
<template slot="option" slot-scope="props">
    {{ props.option.name }}
    <i v-if="isOptionSelected(props.option.id, options)" class="fa fa-check float-right"></i>
</template>
```
The value of 'options' is the array of options selected.

Then I've created a method which would check if the current option is selected:

```
isOptionSelected(currentOption, options) {
    if (options.filter(item => item.id === currentOption).length > 0) {
        return true;
    }
    return false
}
```

Hope this will help someone else too.
