### ISSUE TITLE
send extra data in input event

### ISSUE THREAD

**Issue by DavidSotoA** [shentao/vue-multiselect#706]
Hi, is possible call the input event with the value selected and extradata?

**Comment by shentao** [comment]
Please be more specific. For the value selected, you can use the `@select` event.

**Comment by nepkto** [comment]
Hello,
I am also facing the same problem. I want to send multiple parameters through the event.
For e.g: 
          **@select(parameter1,mySelectedOptions)**
How can I achive this?

**Comment by ddurose** [comment]
I am wondering about this as well

**Comment by mt89vein** [comment]
i think it can be solved with wrapper component. Just listen @input event and  emit to parent with extra data

**Comment by shentao** [comment]
@nepkto this is not possible right now. The events are usually emitted with only the value and the `id` of the component.

**Comment by xlanex6** [comment]
@mt89vein 
can you show an exemple ?

**Comment by mt89vein** [comment]
@xlanex6 https://codesandbox.io/s/v06l9z6743

**Comment by Venegrad** [comment]
and i need create event for every select?
