### ISSUE TITLE
Deselecting pre-selected group

### ISSUE THREAD

**Issue by jsvdvis** [shentao/vue-multiselect#713]
Hello,

Before I was not using the group-select part of Vue-Multiselect, but it is really useful. Up to now I have used v-model to preselect values, since it worked just fine for my application. I do not know what the preferred method for preselecting options is.

However, I am now trying to implement groups as well, including preselect. Deselecting preselected groups does not seem to work though, see [JSFiddle](https://jsfiddle.net/ocx234fz/17/).
Looking at the events, it can be seen that the elements that are removed are added again (if I understand correctly). 

Is this not working due to the way I am preselecting options? And, if so, what is the proper way to preselect options in Vue-Multiselect?

Thank you in advance,
Jaap

**Comment by jsvdvis** [comment]
Using a work-around (Using the @select and @remove events to add and remove elements to a secondary array) I have been able to also remove objects, though the solution is not exactly pretty.
I have got it working for now, but I'm still wondering is this is the intended solution?

**Comment by shentao** [comment]
This looks like a bug. It should work with the way you’re preselecting them. Please use the workaroud and I will try to fix this during the weekend. Thanks for reporting!

**Comment by Reollyn** [comment]
U can make it with `computed property`. Here is the code [JSFiddle](https://jsfiddle.net/ocx234fz/31/).

The array `selectedValues` at start needs to be same as the `value` array. And i added `underscore.js`.

**Comment by bgarrison25** [comment]
So, there is a workaround but it was determined by @shentao up above that it should be fixed....why the decision to just not fix it and force the workaround?

**Comment by chdzma** [comment]
Any update for this?

**Comment by chandrabhan-singh-27d** [comment]
Any workaround other than underscore js on this issue?
