### ISSUE TITLE
Wrong --selected class in multiselect-tag when custom value is already added

### ISSUE THREAD

**Issue by Landen13** [shentao/vue-multiselect#715]
Used config:

:clearOnSelect="false"
:multiple="true"
:tags="true"
:limit="2"

**Steps to reproduce:**
Add a new value (which is not present in select values)
Start entering a new value

**Current result:**
a new **li** item with alredy entered letters (not yet finished) appears in dropdown with **multiselect__option--selected** class and deselect label

**Expected result:**
this new **li** item shouldn't have such class and deselect label

**Comment by shentao** [comment]
Sorry but please provide a reproduction link and reopen the issue if it’s still valid.
