### ISSUE TITLE
ajax multiselect loading data automatically

### ISSUE THREAD

**Issue by danieltutu** [shentao/vue-multiselect#716]
What I am looking for is a way that when I click on the multiselect (multi = true) for the first time, I need to see some options in the list. I would like those options to be loaded when the component is rendered (loaded), This way I can give users some clues about the search values and what they may try to type in.

I saw that when you click the component and then click outside it, it sends an ajax request to the server with a value of "" for the `query` parameter.

I believe that this can be used to automatically load the options before the user types in something.

The other way around would be to manually send a request to the server and set the `:options` attribute. But as I said, it may be useful to reuse the previous request with empty query param.

Is there any way I can achieve this at this point? I looked over the documentation and I haven't seen something they may help me with this problem.

**Comment by shentao** [comment]
Hi. If you want to load the `options` before the user interacts with the component please do it in the parent component during the `mounted` or `created` hooks. VueMultiselect has nothing to do with it. You can, however, use the same method for fetching the data. :)
