### ISSUE TITLE
How to combine option groups with simple multiple options

### ISSUE THREAD

**Issue by Denis4yk** [shentao/vue-multiselect#719]
I want to have a few groups along with a list of other options. Something like that

```javascript
this.options = [
                    {
                        type: 'no-review'
                    },
                    {
                        groupName: 'Reviewed',
                        group: response.data.data
                    }
                ];
```

Is it possible?

**Comment by shentao** [comment]
Sadly I think that the current solution only allows for either grouped results or flat ones. What about you create a new group with a label like "Others"?

**Comment by Denis4yk** [comment]
@shentao Yes, I did so, but, honestly, it looks a little bit...awkward. So, to my mind, it may be a good improvement. May I create an issue for that feature request?
