### ISSUE TITLE
How do I define the selected value?

### ISSUE THREAD

**Issue by OctaneInteractive** [shentao/vue-multiselect#720]
I'm attempting to replace `<select>` elements with Vue Multiselect:

```
<select v-bind:name="name" v-bind:id="id">
	<option v-bind:value="value">Select a {{behaviours[4]}}&hellip;</option>
	<option v-for="(optionRoomLayout, optionIndex) in roomObj" v-bind:value="optionRoomLayout.roomLayout" :selected="optionRoomLayout.roomLayout == cellValue.spreadsheetCellValue">{{optionRoomLayout.roomLayout}}</option>
</select>
```
In the above example, I compare two values:

`optionRoomLayout.roomLayout == cellValue.spreadsheetCellValue`

... but I don't see how I would do the same with Vue Multiselect.

Any ideas?

**Comment by TrendyTim** [comment]
I had the same issue then i thought perhaps vue can solve this missing piece for us.

Its not ideal, but you can use a function or a filter which are really just functions but easier to read when chaining.

```html
<multiselect :value="findListItemByID(item.cat, listsource)" @input="function(value) {item.cat = value.id }" :options="listsource" :multiple="false" :close-on-select="true" :clear-on-select="false" :show-labels="false" :hide-selected="false" placeholder="" label="name" track-by="id" :preselect-first="false" :searchable="false"></multiselect>
```

Where 
**listsource** is the array objects (each item in that list has a name and and id property)
**item** is the item that holds the value
**findListItemByID** is a method i added to my vue instance defined as 

```js
 findListItemByID(id, list) {
                    return list.filter(function (e) { return e.id == id })[0]
                },
```

Personally i haven't settled on if ill inline findListItemByID or not, i guess it depends on if i need to reuse it elsewhere.

It would be a lot easier if there was a value-field property to eliminate that extra step though.

**Comment by OctaneInteractive** [comment]
Hi @TrendyTim, and thanks for the suggestion.

While I've been able to adapt your code and get it to match, it still won't select it.

Weird.

**Comment by OctaneInteractive** [comment]
I'm using `v-model` which is appears to be the cause of the problem, but if I remove it, no value is passed.

**Comment by TrendyTim** [comment]
yeah i use mine i a loop too, if you post your multi select that works but uses the object i can help you with the proper syntax, you just have to use functions  to process the values.

**Comment by shentao** [comment]
This has been solved multiple times on other issues. See #727 as a rather recent example.

**Comment by OctaneInteractive** [comment]
Hi @TrendyTim, and apologies for the late response.

I've tried the various workarounds in the issue recommended by @shentao, but none of them work.
