### ISSUE TITLE
List of option from object without keys

### ISSUE THREAD

**Issue by heyddi** [shentao/vue-multiselect#724]
Hi there!

I haven't find it so I guess I already have my answer. But before reformatting anything, is there any way to have the option list working from a source like the following:

           `"options": [
              {
                "": "--"
              },
              {
                "AB": "Alberta"
              },
              {
                "BC": "British Columbia"
              },
              {
                "MB": "Manitoba"
              },
              {
                "NB": "New Brunswick"
              },
              {
                "NL": "Newfoundland"
              },
              {
                "NT": "Northwest Territories"
              },
              ....
            ]`

Thanks for the help!

Heyddi

**Comment by TrendyTim** [comment]
id say you would need to bind it to a computed property where you reformat it into name and value pairs (or just preprocess it before hand)

var newObj = {}
for(var key in options) {
    if(options.hasOwnProperty(key)) {
        var name = options[key];
        newObj ['value'] = key
        newObj ['name'] = name 
    }
}

that would convert one of them to {value: 'AB', name='Alberta'} you'd just need to loop it and build the new array.

**Comment by heyddi** [comment]
Thanks so much for the help! That was already something like this that I worked on but I was wondering if I missed something simpler or not.

Thanks again,

Heyddi
