### ISSUE TITLE
Track by is not used everywhere

### ISSUE THREAD

**Issue by vpratfr** [shentao/vue-multiselect#727]
Hi,

We store IDs in database and thus we provide the select component the selected ID as the model.

Similarly, when form gets submitted, we expect the selected ID to be sent along with the form data.

Currently, the value property only accepts a full object. It does not take into account the track-by property which tells how we identify our objects.

I saw another issue related to the preselected item(s). But I want to also add that the resulting value sent with the form should also be the tracked property of the item (not the whole item).

**Comment by vpratfr** [comment]
For instance, given `options = [ { 'id': 1, 'label': 'John' },  { 'id': 2, 'label': 'Jane' } ]`

I would expect that: 

- `value="1"` selects the option 'John'
- the target `v-model` property contains '2' when I select 'Jane'
- the form gets sent with the value '2' for the corresponding named select input

**Comment by TrendyTim** [comment]
i thought the same thing, though that probably cant be done for backwards compatibility reasons a new prob would be required.

My not quite so nice but it works workaround  is at 
https://github.com/shentao/vue-multiselect/issues/720

**Comment by alex3683** [comment]
As a workaround I currently use a computed property split into getter and setter:

```js
{
   data: () => ({
      actualSelection: -1,
      options: [ { 'id': 1, 'label': 'John' }, { 'id': 2, 'label': 'Jane' } ]
   }),
   computed: {
      wrappedSelection: {
         get() {
            if( this.actualSelection === -1 ) {
               return null;
            }
            return this.options.find( _ => _.id === this.actualSelection );
         },
         set( value ) {
            this.actualSelection = value != null ? value.id : -1;
         }
      }
   }
}
```

Then bind the multiselect component to the `wrappedSelection` instead of the `actualSelection`.
(I just wrote this down here as example without testing, so be careful ;-))

**Comment by vpratfr** [comment]
Fine if you have a few selects in your whole app. But that is quite a lot of code to write again and again when select2 is just compatible with HTML forms from start.

**Comment by wtfuii** [comment]
If it helps somebody: @alex3683 's workaround for multi select:
```
<multiselect multiple
   :value="actualSelection.map(selection => options.find( _ => _.id === selection))"
   @input="actualSelection = $event && $event.map(_ => _.id)"
   :options="options"/>
```

**Comment by shentao** [comment]
Using a computed property with a getter/setter (that @alex3683 mentioned) is the recommended approach. 

This can’t be done otherwise for the reasons you mentioned (preselecting, async options etc). The decision to do it this is that it’s easier to extract the `id` from the whole object than to dynamically recreate objects based on just the `id` where for example other data needed for displaying might not be available. 
I imagine it would result in even more issues being created... :(
