### ISSUE TITLE
pass variables and access selectedOption via @select 

### ISSUE THREAD

**Issue by Branksy** [shentao/vue-multiselect#732]
I want to get the selected value into a method, and I can do this by having @select='myMethod', which I can access as:

myMethod(selectedOption){
  ..do stuff with selectedOption
}

However, if I also want pass other variables like an index into myMethod,
 i.e.
@select='myMethod(index) or 
@select='myMethod(index, selectedOption)'

....then selectedOption is always undefined inside the method.

Is this an error or, what am I missing?

**Comment by icaromelog** [comment]
I have the same question.

**Comment by shentao** [comment]
The `select` event is emitted like this:
```
this.$emit('select', option, this.id)
```

This means the 1st argument is the `selectedOption` and the 2nd argument is the `id` that you can pass to the component. `index` is not passed. You can get it by searching for the index of the element. For example:
```
myMethod(selectedOption) {
  const index = this.options.findIndex(option => option.id === selectedOption.id)
  // stuff
}
```
