### ISSUE TITLE
Placeholder text not visible if its length is more than multiselect input box width

### ISSUE THREAD

**Issue by kevinding0218** [shentao/vue-multiselect#733]
Hello, thank you very much for providing this awesome control! We found one small issue during our development is that, when applied a placeholder to multi-select dropdown, if the place holder length is more than multiselect input box width, the placeholder won't be available to see partially. However, this does not happen on single select dropdown, as the input will automatically wrap the place holder text. Please see below screen shot(**the 1st dropdown is single-select where the place holder has been adjusted wrapped into two lines where the 3rd dropdown is multi-select where the place holder has been blocked partially from UI**:
![capture](https://user-images.githubusercontent.com/13737436/40396833-1c02e052-5dfd-11e8-9550-6d653e52ed01.PNG)
Is there any way to apply the same text-wrap to multi-select dropdown? We've tried to use CSS text-wrap however the height of the multi-select dropdown won't adjust automatically so that after wrapping text, the second line of text won't be able to see...

Thank you very much for any help or advise!

Best

**Comment by shentao** [comment]
You can edit/override the whole CSS code if you want so it should be possible. Otherwise, there is no easy way to do it unless you increase the width of the components based on the placeholder length. Though that might be tricky if you have i18n in your app.

**Comment by Kshitizagar** [comment]
how can we apply can you explain
