### ISSUE TITLE
How to remove the add tag option in tagging?

### ISSUE THREAD

**Issue by harishankards** [shentao/vue-multiselect#734]
Hi, I'm using your [tagging](https://vue-multiselect.js.org/#sub-tagging) feature. Thanks for that.

In that, when I'm typing a tag which is not existing, it asks me to add a new tag. I want to hide it and only show the available tags to select. How do I achieve this?

Thanks in advance

**Comment by shentao** [comment]
Just remove the `:taggable="true"`. It’s the default behavior of a multiple select. 
https://vue-multiselect.js.org/#sub-multiple-select
