### ISSUE TITLE
When options are cleared, there is no message like "no data available"

### ISSUE THREAD

**Issue by akki-jat** [shentao/vue-multiselect#736]
**VueMultiselect Version:** 2.1.0
**Vue Version:** 2.5.11
**OS:** Windows 7

### Reproduction Link
[https://codepen.io/akki-jat/pen/YvzKZW](https://codepen.io/akki-jat/pen/YvzKZW)

### Steps to reproduce 
Click on update button to clear all options
### Expected Functionality
Should display message like "no data"
### Actual Functionality
It does not display anything

**Comment by shentao** [comment]
https://codepen.io/anon/pen/KegemE you can do it by using the `afterList` slot.

**Comment by akki-jat** [comment]
OK, thanks @shentao.
