### ISSUE TITLE
How use multiselect by createElement?

### ISSUE THREAD

**Issue by fourteenmeister** [shentao/vue-multiselect#738]
VueMultiselect Version: 2.1.0
Vue Version: 2.5.16
OS: Windows 7

**Reproduction Link**

https://codepen.io/anon/pen/WyvBJp

**Steps to reproduce**

Select option

**Expected Functionality**

Option should be selected

**Actual Functionality**

Options are not selectable

**Comment by shentao** [comment]
Hey! You have to pass `value` within `props`, rather than `domProps`.

Here’s the solution: https://codepen.io/anon/pen/zaKaBY
