### ISSUE TITLE
When using multiselect as tagsinput, dropdown should not open on the whole width of the control

### ISSUE THREAD

**Issue by wisamx** [shentao/vue-multiselect#741]
Hello,
When using multiselect as tagsinput, dropdown should not open on the whole  width of the control.
The dropdown should lay under the new tag being typed.

![Image](https://preview.ibb.co/ckep2o/new.png)
![Image](https://preview.ibb.co/fxnbho/old.png)

**Comment by shentao** [comment]
This is not possible right now unless you customize it yourself. Feel free to do it. :)
