### ISSUE TITLE
[Feature Request] Add some class for option group even if group-select prop is set to false

### ISSUE THREAD

**Issue by akki-jat** [shentao/vue-multiselect#742]
### Explanation
If I want to apply something on class "**multiselect__option--disabled**" then it includes option group also.

### Repo Link
[https://codepen.io/akki-jat/pen/Nzrwar](https://codepen.io/akki-jat/pen/Nzrwar)

### Step to Reproduce
Just delete **:group-select="true"** prop and open the multiselect

**Comment by shentao** [comment]
Thanks! This seems like an easy change. :)

**Comment by kellym** [comment]
Related to this, the option groups should have a specific class regardless of if `group-select` is true or false. Right now, only the disabled class is applied when `group-select` is false.
