### ISSUE TITLE
Option with value 0 not showing.

### ISSUE THREAD

**Issue by JamesBrightley** [shentao/vue-multiselect#745]
When setting the the mulitselect value it does not display the selected value if it is 0. The model is correctly bound but for display purposes it is not working when I believe it should especially when the default is 0, this triggers the user to try and select it again.

### Version
2.1.0 - CDN version as per Getting started guide

### Steps to reproduce
`<multiselect v-model="numberOfChildren"  :multiple="false" :close-on-select="true" placeholder="Number of Children" :options="numberOfChildrenOptions">
                            </multiselect>`

vue data property:

`
data: {
    numberOfChildrenOptions: [0,1,2,3,4,5,6,7,8,9,10],
    numberOfChildren: 0
}
`

### Expected behaviour
The drop down will display '0'

### Actual behaviour
The drop down display is empty.

**Comment by sholzmayer** [comment]
I'd like to reopen this issue, because I still have the same problem...

**Comment by JamesBrightley** [comment]
Same here, I believe it's a genuine bug
