### ISSUE TITLE
input text with no results search

### ISSUE THREAD

**Issue by Sndan** [shentao/vue-multiselect#749]
I want to capture the input in case the search did not have any results ...
is it possible 
as i went over the doc but could not figure it out

**Comment by jalerson** [comment]
Hey @Sndan, I also needed that and, in my case, I have the `v-model` attribute in my `multiselect` tag, like this:

```
<multiselect v-model="city" ... >
  ...
</multiselect>
```

So I just needed to use `this.city`. Simple as that!

I hope it helps =)

**Comment by Sndan** [comment]
it does not work for me as the field is automatically cleared !

**Comment by Sndan** [comment]
it is OK I used tags
