### ISSUE TITLE
 make the tags invisible and show the total tag instead

### ISSUE THREAD

**Issue by VCodepp** [shentao/vue-multiselect#750]
I do not want to see the tags. Instead, it is better to see the total selected tags.

**Comment by purplelady105** [comment]
I would like to have an option for this as well.

**Comment by TrendyTim** [comment]
I had to do an ugly hack with limit=0 and some custom JS for the limit-text so native support would be nice, its crazy how there are no multi select dropdowns that dont natively and cleanly support no tags,

**Comment by akki-jat** [comment]
Hi @VCodepp 

### Are you talking about feature like this?
![element_select](https://user-images.githubusercontent.com/26685162/42593577-7d152096-856a-11e8-93bd-aabf9f5554c6.png)

### Or like this?
![vue_multislect](https://user-images.githubusercontent.com/26685162/42593598-8c88599e-856a-11e8-898e-a6083160ad46.png)

**Comment by smilingkite** [comment]
I've 'solved' this by setting the amount of selected items to show at 0 and css hiding the message that appears when there is nothing showing.

**Comment by shentao** [comment]
This is now available in 2.1.2 thanks to @akki-jat PR! 🎉

**Comment by rashearth** [comment]
Hi, thank you for the wonderful feature!
I have checked many sites to implement this feature, but i couldn't find out how to set it.
If possible, could you kindly share us how we could list no tags and list "2 options selected"?
(Please kindly tell us in what options or code we should list to implement this feature)
sorry for taking you time.
& thank you for your support.

**Comment by akki-jat** [comment]
hi @rashearth,
creted small demo for it so you can play around with it.

### Demo Link:
https://jsfiddle.net/akki_jat/pdvLz5bs/6/

**Comment by rashearth** [comment]
Hi, akki-jat, Thank you so much for the support!
i understood, but it seems a bit different for what i have imagined.

in the Vue.js multiselect homepage(https://vue-multiselect.js.org/) example, it writes in plain text of "3options selected" as the picture below.
is it possible to work like this in plain text? this feature would fit the design of any kind of sites.
i have checked the source of the HP, but i could find the exact code for working this out.

sorry for taking you time, but it would be great if you could show us how to work this out.

<img width="1420" alt="スクリーンショット 2019-10-14 19 51 15" src="https://user-images.githubusercontent.com/26535295/66746415-b9cd1b80-eebc-11e9-94c9-ac1911835c79.png">
<img width="417" alt="スクリーンショット 2019-10-14 19 51 22" src="https://user-images.githubusercontent.com/26535295/66746419-bf2a6600-eebc-11e9-809b-436e18b322e6.png">

**Comment by akki-jat** [comment]
Hi, @rashearth ,

Styles were coming because I added the classes you can remove the classes or even add your custom classes to give look as you want.

### Take a look at updated link.
[https://jsfiddle.net/akki_jat/prLu7zqt/9/](https://jsfiddle.net/akki_jat/prLu7zqt/9/)

**Comment by rashearth** [comment]
thanks alot! I got it working! 
it took me so long, since i have been using the old version of vue multiselect, and couldnt make it work. but now i got it:)

**Comment by ashwiniDPSL** [comment]
> ### Are you talking about feature like this?
How implement 1st image option ?

**Comment by Devd2022** [comment]
> Hi @VCodepp
> 
> ### Are you talking about feature like this?
> ![element_select](https://user-images.githubusercontent.com/26685162/42593577-7d152096-856a-11e8-93bd-aabf9f5554c6.png)
> 
> ### Or like this?
> ![vue_multislect](https://user-images.githubusercontent.com/26685162/42593598-8c88599e-856a-11e8-898e-a6083160ad46.png)

How to implement 1st image option?
Thanks
