### ISSUE TITLE
[Feature Request] Tag validation

### ISSUE THREAD

**Issue by andrey-hohlov** [shentao/vue-multiselect#752]
For example, we need to make taggable multi-select, but only for email addresses.

It can be simple regexp prop for validation.
If an input is not valid (not passed regexp test) you can't add it as a new tag.

Live example: https://joshuajohnson.co.uk/Choices/ ('Email addresses only' section).

What do you think?

**Comment by shentao** [comment]
I would rather leave that to userland and not expand the API further in that direction. Try extending the component and simply override the tagging function to your needs.

**Comment by carmolim** [comment]
Could you please show in a simple example how I could override the tagging function?

Thanks!
