### ISSUE TITLE
Single select with :clear-on-select='false' and :preserve-search="true" throw warn "ClearOnSelect and Multiple props can’t be both set to false."

### ISSUE THREAD

**Issue by karakum** [shentao/vue-multiselect#755]
Why single select can't be with :clear-on-select='false' ?

### Reproduction Link
https://jsfiddle.net/karakum/jqofkzxc/3454/

### Steps to reproduce
1. Run as is
2. Open select
3. Type search string
4. Select any item

### Expected behaviour 1
First option must stay modified

### Actual behaviour 1
First option modified as expected, but:
Console warn: `ClearOnSelect and Multiple props can’t be both set to false.`

Modify `:clear-on-select` to `true` and repeat scenario.

### Expected behaviour 2
First option must stay modified

### Actual behaviour 2
First option has been reset with suffix `(reset)` because search query **reset on select**

**Comment by karakum** [comment]
Any suggest?

**Comment by akki-jat** [comment]
@karakum if you set **clear-on-select** with **single select** then there will be no options to **deselect** it.

**Comment by karakum** [comment]
@akki-jat but I need to **clear-on-select=FALSE** with **single select** to prevent clear of search string after select item

**Comment by akki-jat** [comment]
@karakum I also don't think there is any connection betwwen **clear-on-select** and **multiple** prop.
But author would know better, so I am adding @shentao in loop.

**Comment by shentao** [comment]
This is a legacy warning when the single-selection was using the input itself to display the value. After the recent changes (the single value has it’s own span), this no longer seems needed. Feel free to provide a PR that will remove the warning.

**Comment by karakum** [comment]
@shentao merge PR please
