### ISSUE TITLE
tag placeholder helper issue when using the option slot

### ISSUE THREAD

**Issue by danielrz** [shentao/vue-multiselect#760]
### Reproduction Link
https://jsfiddle.net/jqofkzxc/3808/
### Steps to reproduce
search for none existing options (i.e: xx)
### Expected behaviour
the tag placeholder helper should show the characters that are being typed.
### Actual behaviour
the tag placeholder helper does not work as expected. it does not show the characters that are being typed. The data is blanked. 
The reason is because option slot is used for my custom option template...

BTW, is there a way to configure the multiselect so that the tag placeholder helper can be shown or be hidden? 

![image](https://user-images.githubusercontent.com/3119826/41657373-e21c1088-749b-11e8-99c6-0f6311805049.png)

**Comment by crutch12** [comment]
Found solution:
Use it with slot="selection" and write there placeholder too:
```
<multiselect v-model="model" :options="options" :multiple="true" placeholder="Placeholder" label="name" track-by="id">
  <template v-slot:selection="{ values, search, isOpen }">
    <span v-if="values.length && !isOpen">Placeholder</span>
  </template>
  <template v-slot:tag="{ option, search }">
    <span></span>
  </template>
</multiselect >
```
