### ISSUE TITLE
group label is not rendered when using option slot

### ISSUE THREAD

**Issue by danielrz** [shentao/vue-multiselect#761]
Reproduction Link
https://jsfiddle.net/jqofkzxc/3838/

Steps to reproduce
click on the input field in order to display the menu

Expected behaviour
the group labels should be rendered according to the option slot

Actual behaviour
the group labels are not rendered.
The reason is because option slot is used for my custom option template...
![image](https://user-images.githubusercontent.com/3119826/41666111-61d5fce2-74b2-11e8-8abd-aaa3d7804dfe.png)

possible relation with #760

**Comment by jehadassaf** [comment]
Ran into the same issue... 
Here's a temporary workaround: https://jsfiddle.net/Jehad/jqofkzxc/3872/

**Comment by farzadso** [comment]
@jehadassaf Thanks for the solution. Worked perfectly.

**Comment by TheSycamore** [comment]
@jehadassaf Thank you so much! Works great.

**Comment by MLDMoritz** [comment]
Issue still persists, should be fixed please.

**Comment by daverogers** [comment]
I'm seeing this too. the solution @jehadassaf posted works for now.

**Comment by farzadso** [comment]
@shentao Will this issue be fixed in the upcoming versions?

**Comment by MarcStoecker** [comment]
Thanks @jehadassaf, clever workaround. 👍

**Comment by anthonywebster** [comment]
> Ran into the same issue...
> Here's a temporary workaround: https://jsfiddle.net/Jehad/jqofkzxc/3872/

Great!!!1
