### ISSUE TITLE
how to create button like in multiselect

### ISSUE THREAD

**Issue by rockyshukla** [shentao/vue-multiselect#764]
hello folks is it possible to create button look in dropdown option which always fixed at bottom or top for eg  option list like 
       1.add new    //this are fix (either in last or top)
       2.jhon         //this are scollable
       3.miky       //this are scollable
       4.rock       //this are scollable

here is link of image https://i.stack.imgur.com/Np1TE.png
 is it possible to achieve suing css or html if yes how please guide  me because i haven't found anything example

**Comment by pareeohnos** [comment]
@rockyshukla I've just had to do something very similar, and you can use the `beforeList` or `afterList` slots to define any custom markup you'd like to appear before or after the list.

**Comment by shentao** [comment]
This should be possible with the incoming v3 release. You can try it out here: https://github.com/shentao/vue-multiselect/tree/v3

**Comment by tjb328** [comment]
@shentao what has changed in v3 to make this easier? Sorry if it's a dumb question, but I took a look at some of the diffs and nothing popped out at me.

**Comment by 1quintana** [comment]
Pretty old post, but I was dealing with this problem and the V2 already have this option.

You have to make sure to add :taggable="true" and tag-placeholder="Add new flag" and finally the function which is gonna handle what to do with the value :tag="addTag"

`addTag (newTag) {
                const tag = {
                    name: newTag,
                    code: newTag.substring(0, 2) + Math.floor((Math.random() * 10000000))
                }
                this.taggingOptions.push(tag)
                this.taggingSelected.push(tag)
            },`
