### ISSUE TITLE
Use isDisabled as data -- suggestion

### ISSUE THREAD

**Issue by woodgates** [shentao/vue-multiselect#765]
Hi.

I want to suggest to implement to use isDisabled as data in the code in replacement of disabled as props. This way if you extend the component you can change the isDisabled value with Events without creating errors for changing a prop directly.
    
props:{
....  
    disabled: {
        type: Boolean,
        default: false
      },
----}

data(){
  return{
    ...
    isDisabled:this.disabled
    ...
  }

**Comment by shentao** [comment]
You can change the `disabled` prop from outside.
