### ISSUE TITLE
How to get multiselect refresh displayed options when changed externally

### ISSUE THREAD

**Issue by dancvrcek** [shentao/vue-multiselect#766]
I must be missing something trivial. I'm changing the array assigned to the options. The array itself gets changed.

When I try search, the labels are updated afterwards.However, I can't figure out how to make the multiselect show the new labels as soon as I make changes to the options list variable.

**Comment by shentao** [comment]
How are you changing the labels? Please remember there are several caveats regarding mutating arrays. https://vuejs.org/v2/guide/list.html#Caveats

**Comment by dancvrcek** [comment]
The setup is: a parent component with a vuetable and a child with a modal window consisting of a couple of multiselects.

The modal is unhidden by clicking a cell in a vuetable. The click should update the content of the modal and show the modal itself

It seems that the multiselects in the modal window render before the props from the parent are updated and show with default values.

However, it happens only the very first time I reload the whole page.... and I'm debugging with a remote database / in a docker / ... i.e., everything is pretty slow.

Maybe, the modal window needs some kind of pre-render?

**Comment by dancvrcek** [comment]
writing things down sometimes help :) calling hide() method on the modal window when the parent is created seems to have solved the issue!

Thanks for the link above, it was quite useful on its own as well.
