### ISSUE TITLE
Option to remove extra drop down space?

### ISSUE THREAD

**Issue by ahummel25** [shentao/vue-multiselect#768]
Is there an option to remove extra drop down space if you don't have enough option values to fill it? Couldn't find existing question in closed/open issues.

Example..

![image](https://user-images.githubusercontent.com/12643871/41873839-d0d9e37e-788b-11e8-80c0-faf4f1bcb37a.png)

**Comment by shentao** [comment]
That’s weird. The Multiselect should automatically adjust to the content inside. See https://jsfiddle.net/shentao/0hLexkyz/. I think thee issue must be on your end.
