### ISSUE TITLE
Limit Slot

### ISSUE THREAD

**Issue by DM2489** [shentao/vue-multiselect#771]
### Description
Documentation for the limit slot is confusing. Either the documentation is wrong, or the 'limit' slot is broken.

https://vue-multiselect.js.org/#sub-slots

### Reproduction Link
https://jsfiddle.net/jqofkzxc/4056/

### Steps to reproduce
1.add an options-limit to the multiselect
2. add a 'limit' slot to the multiselect.

### Expected behaviour
The 'limit' slot to display at the end of the list, when the options-limit has been hit.

### Actual behaviour
No 'limit' slot is displayed

**Comment by akki-jat** [comment]
Hi @DM2489, I think the documenttation is wrong.
And to limit the selection, you have to use limit prop.

### Here the example
[https://jsfiddle.net/akki_jat/o6eyfar7/3/](https://jsfiddle.net/akki_jat/o6eyfar7/3/)

Hope it helps!

**Comment by DM2489** [comment]
@akki-jat Thanks for getting back to me, but I think you misunderstand what I am after. I am looking to show a slot when the number of selected options in the list is too great, not when the user has selected too many options.

Lets say I have 2000 items in my select list. Items after 1000 are not displayed by default, and increasing the limit negatively affects performance too much.

I want a slot to be displayed if the number of options is greater than the `optionsLimit` property.

In essence, i want something similar to the  `afterList` slot, but only when the number of options is `optionsLimit` property is met or exceeded.

Thanks :)

**Comment by akki-jat** [comment]
@DM2489 I get it. But I think right know there is no slot for the use-case you are talking.

And @shentao should know more about this.

Hi @shentao, what do you think? Is there any workaround for this?
If no, then I am happy to implement this feature.

**Comment by DM2489** [comment]
I think it would be a good addition to the plugin.

**Comment by shentao** [comment]
@DM2489 you have to use the `afterList` slot (as you already mentioned), but limit the number of options yourself in a computed property that you pass.
After that, you add another computed property that you put into the `afterList` slot `v-if`. If the number of options is more than 1000 – it should be true, otherwise false. This way you can have a message at the end of the list only when there are too many options.

The `limit` slot is for selected options only. Sorry for the misunderstanding.

**Comment by elDub** [comment]
> After that, you add another computed property that you put into the `afterList` slot `v-if`. If the number of options is more than 1000 – it should be true, otherwise false. This way you can have a message at the end of the list only when there are too many options.

Is there a way to access the count of _filtered_ options within the `afterList` slot, perhaps with a slot scope? Ideally I would want the message to only be displayed when the filtered count of options is greater than the `optionsLimit` property.

**Comment by shentao** [comment]
I don’t think there is a way to do that now. :(

**Comment by alorman-omatech** [comment]
@elDub I used the multiselect's computed array property `filteredOptions` and saved its length with the `search-change` event in a variable to then check the condition to show the `beforeList` slot.

I added the props `ref="list_reference"` & `:options-limit="100"` to my multiselect with the event `@search-change="updateListLength"` 

And in this `updateListLength` function simply put something like this:
`this.filterLength = this.$refs.list_reference.filteredOptions.length;`

Then finally add `v-if="filterLength >= 100"` to the `slot="beforeList"`

Hope this helps!
