### ISSUE TITLE
Is there a way of having only the group shown in the multiselect box rather than all the options within that group?

### ISSUE THREAD

**Issue by DonnyMars** [shentao/vue-multiselect#777]
I'm using the multi-select for some groups. However some of these groups contain loads of options so when I add them, the text box is filled with options and fills the entire screen. Is there a way I get it to show only the group name and allow you to hit the x button to remove that entire group.

**Comment by shentao** [comment]
That’s probably not possible unless you extend the component and provide your own template that supports that.
