### ISSUE TITLE
How can I add predefined option to multiselect?

### ISSUE THREAD

**Issue by tilonorrinco** [shentao/vue-multiselect#778]
Hello there!
Is there any way to add predefined option to multiselect? 
I have an array of years like [2017, 2018, 2019], it comes from DB. 
I want to add predefined option 'all years' with value = 0.
Is there any way to get such thing without changing array structure?
For example, by add some slot in markup or something else?
Here is fiddle with detailed explanation.
https://jsfiddle.net/b82q1huo/
Thanks in advance!

**Comment by shentao** [comment]
You can use a computed property that adds the required option without modifying the value.
https://jsfiddle.net/shentao/w26xfa3e/
