### ISSUE TITLE
If you want to use different markups for selected options it doesn't work with single select

### ISSUE THREAD

**Issue by jpperlm** [shentao/vue-multiselect#782]
https://jsfiddle.net/jqofkzxc/4709/

### Steps to reproduce
if you remove the :multiple="true" from this fiddle the functionality discussed [here](https://vue-multiselect.js.org/#sub-select-with-search)

> New in v2.0.0 stable:
> You can now pass <template slot="tag" slot-scope="props"><Your code></template> to use a different markup for selected options (tags)

no longer works
### Expected behaviour

I should be able to change the markup of selected items on a single select

**Comment by shentao** [comment]
There is the `singleLabel` slot for that.
https://jsfiddle.net/shentao/1qrjavuk/

Also an example in the docs:
https://vue-multiselect.js.org/#sub-custom-option-template
