### ISSUE TITLE
Groups Label

### ISSUE THREAD

**Issue by yohan-atlan** [shentao/vue-multiselect#785]
Hello,
I have an issue when I want to search in Option groups with uppercase value.

```
<multiselect v-model="selectedHeader" @input="updateHeader" group-values="characteristics" group-label="name" label="name" :options="characteristics" :close-on-select="true" width="350"></multiselect>
```

**Comment by shentao** [comment]
Please provide an reproduction link using the Issue template (there’s a link to JSFiddle that can be used to present the issue).
