### ISSUE TITLE
How to focus the multiselect from js?

### ISSUE THREAD

**Issue by okmkey45** [shentao/vue-multiselect#787]
Reading docs and searching issues, I don´t see a way to focus the input of the multiselect from javascript. Maybe I am missing something. Please help me and thank you

**Comment by shentao** [comment]
Find the component in your DOM tree and call `.focus()` on it. It will forward the focus to the input element if it’s a searchable component.

**Comment by okmkey45** [comment]
Hello. Sorry to bother you again.
I tried these and none of ther worked for me
```
document.getElementsByClassName("multiselect__input")[0].focus()
document.getElementsByClassName("multiselect")[0].focus()
```

**Comment by shentao** [comment]
https://jsfiddle.net/shentao/6brntkj5/

**Comment by okmkey45** [comment]
aaaahhh got it. Thanks for the help
