### ISSUE TITLE
Tags not styling v2.0.1

### ISSUE THREAD

**Issue by YosefOberlander** [shentao/vue-multiselect#790]
Hi,

I looked at the documentation, and I couldn't find anything regarding the css.

1. I installed vue-multiselect via npm from the documentation - `npm install vue-multiselect --save`. 
2. I imported the package into my component `import Multiselect from 'vue-multiselect'`. 
3. I mounted the component `components: { Multiselect },`
4. I imported the css just like the documentation showed `<style src="vue-multiselect/dist/vue-multiselect.min.css"></style>`

5. I coped this sinppet from the documentation - I made three changes. changed v-model, options, preset-first.

`<multiselect v-model="tag" :options="multiTagOptions" :multiple="true" :close-on-select="false" :clear-on-select="false" :hide-selected="true" :preserve-search="true" placeholder="Pick some" label="name" track-by="name" :preselect-first="false">
    <template slot="tag" slot-scope="props"><span class="custom__tag"><span>{{ props.option.language }}</span><span class="custom__remove" @click="props.remove(props.option)">❌</span></span></template>
  </multiselect>`

6. I adde the options 
`multiTagOptions: [
                    { name: 'Vue.js', language: 'JavaScript' },
                    { name: 'Adonis', language: 'JavaScript' },
                    { name: 'Rails', language: 'Ruby' },
                    { name: 'Sinatra', language: 'Ruby' },
                    { name: 'Laravel', language: 'PHP' },
                    { name: 'Phoenix', language: 'Elixir' }
                ],`

7. I added the v-model `tags[]`

What i understand from the documentation that's all i needed todo, and some css class won't get the styles from the imported css. As you can see from the screenshot below some f the styles are missing.

<img width="347" alt="screen shot 2018-07-30 at 10 27 47 pm" src="https://user-images.githubusercontent.com/20997717/43434005-e3b3ce4c-9447-11e8-84bd-83bd72c2087a.png">

**Comment by akki-jat** [comment]
@YosefOberlander can you create repo to reproduce error?

**Comment by YosefOberlander** [comment]
@akki-jat sure I'll do it once I get home

**Comment by jurb** [comment]
@YosefOberlander For the example to work, you still have to add your own styling. 

See that `<span class=".custom__tag">`? That class is missing from your code now. Just add:

```
.custom__tag {
  display: inline-block;
  padding: 3px 12px;
  background: #96b4df;
  margin-right: 8px;
  margin-bottom: 8px;
  border-radius: 10px;
  cursor: pointer;
}
```

in your style block, and you're good to go. Would be nice if the documentation would also mention this.

**Comment by YosefOberlander** [comment]
@jurb 

Yea, I forgot to update this last week I figured it out like that. Thanks :)
