### ISSUE TITLE
How to style?

### ISSUE THREAD

**Issue by focussing** [shentao/vue-multiselect#794]
Thank you for this great component!
Is there a working example of for example how to change the font-size?

**Comment by shentao** [comment]
The styles are not scoped so it should be quite straightforward to override the styles. Look into the css classes in the inspector.

**Comment by focussing** [comment]
That's exactly what I already did... but doesn't work...

**Comment by shentao** [comment]
Where do you add the Multiselect css file? Remember that CSS is cascading – meaning whatever comes later is overriding the previous statements. Also, remember about CSS specificity.
