### ISSUE TITLE
Multiple Selected Items in Optgroup with Custom Label for Selected Options

### ISSUE THREAD

**Issue by alucidwolf** [shentao/vue-multiselect#797]
### Reproduction Link
https://jsfiddle.net/efaj4pbt/

### Steps to reproduce
Select a couple items and observe the label for selected items is the same as the option under the optgroup

### Expected behaviour
I would like it if I can set a custom template with a slot for multiple labels where I can append the optgroup category title to the label after it is selected, but not when it is listed in the dropdown under the optgroup

### Actual behaviour
I can only get this to work for `slot="singleLabel"` using the `<template>`, not for multiple select though.

![image](https://user-images.githubusercontent.com/563139/43972853-c71c04ac-9ca3-11e8-9a38-141947ffbe84.png)

**Comment by shentao** [comment]
You can use the `tag` slot. https://vue-multiselect.js.org/#sub-slots
