### ISSUE TITLE
Zero value not recognized

### ISSUE THREAD

**Issue by arwinvdv** [shentao/vue-multiselect#801]
Is there a way to use the zero (0) value as a return value? Or is the behaviour below how it should work?

### Reproduction Link
I will use it with an more advanced function but I have made the problem as small as possible: https://jsfiddle.net/53gnwzv0/

### Steps to reproduce
1. Click on the first option (0)
2. Placeholder didn't change

### Expected behaviour
I was expecting that the zero is shown.

### Actual behaviour
The placeholder is shown when the value is zero.

**Comment by TheStoof** [comment]
It looks to be fixed, but no new version was released yet. v2.1.3 was a week before this was merged.
