### ISSUE TITLE
Search by multiple fields

### ISSUE THREAD

**Issue by mt89vein** [shentao/vue-multiselect#819]
Hi!

Is it possible to search by multiple fields out of the box?

if i have an array of objects as options with two or more fields  e.g. { name: 'awesome name', age: 18 }
i want to type in search field and find by age or by name.
now i solve it by listening @search-change and filter options by myself

Is it possible to add a prop searchField, with type string or array (like works now prop "label" with search)

Thanks

**Comment by shentao** [comment]
You have to turn the internal search off. See example: https://vue-multiselect.js.org/#sub-asynchronous-select
