### ISSUE TITLE
Vuex Getters not working in :options

### ISSUE THREAD

**Issue by priteshkadiwala** [shentao/vue-multiselect#820]
Hello, firstly thank you for this awesome component. However, I am having a problem when I load options of the multiselect with a vuex getter which is an array. I have provided the code below with more explanation:

The code for multiselect: 
```html
<multiselect   v-model="city"
               v-if="location_loaded"
              :options="location"
              :showLabels="false"
              :placeholder="city.text"
               label="text"
               track-by="value">
</multiselect>
```

for `:options:"location"` the `location` is actually coming from: 
`...mapGetters({ locations: 'locations' })`

And the getter in the vuex looks like this: 
```js
const getters = {
  locations: state => {
    return state.cities.map(i => {
      return {
        value: i.city_id,
        text: i.city_name + ', ' + i.state_name + ', ' + i.country_name,
        city_name: i.city_name,
        state_name: i.state_name,
        country_name: i.country_name,
      }
    })
  }
}
```
I also do make sure that before my component, which contains the multiselect, is mounted the `locations` getter is loaded with the data but then I still get this error from multiselect:

<img width="483" alt="screen shot 2018-09-07 at 11 23 30 pm" src="https://user-images.githubusercontent.com/12538126/45249818-17c02480-b2f5-11e8-9c35-f9babaf42380.png">

Please let me know what I can do to solve this issue.

Thanks

**Comment by p-adams** [comment]
Could it just be a typo? You are binding "location" to :options but you've declared it as "locations" (plural) in Vuex. Let me know if that helps.
