### ISSUE TITLE
axios response to pre-select on multi-select

### ISSUE THREAD

**Issue by ksromero** [shentao/vue-multiselect#822]
Im using this popular plugin

    <multiselect v-model="test.selectedTags" 
        :options="options" 
        :multiple="true" 
        :clear-on-select="false" 
        :hide-selected="true" 
        :preserve-search="true" placeholder="Pick some" label="name" track-by="name" :preselect-first="true">
    </multiselect>  

 

On my code im using axios request to fetch user id and name to be pre-selected by the multi-select

    editUrl: function(id){
        let vm = this;
        axios.get('api/urls/' + id)
        .then( response => {
        vm.test.selectedTags = response.data.data.users.map(user => ({  name:user.name, id: user.id }))
             })
        .catch( error => {
             console.log(error);
         });
         },
     }

and the response looks like this 

    selectedTags:Array[2]
        0:Object
            id:3
            name:"asdaa"
        1:Object
            id:4
            name:"atetest"

Now, I successfully got the result and pre-select the data in multi-select
[![enter image description here][2]][2]

However when i click the "x" to remove, it doesnt remove the selected data and no errors has been shown. How to fix this? TIA

i dont get it my response looks like this but i cant still remove a specific option when i clicked the "X" 
https://jsfiddle.net/0hLexkyz/660/

  [1]: https://github.com/shentao/vue-multiselect
  [2]: https://i.stack.imgur.com/UCHJp.jpg

**Comment by shentao** [comment]
This should work out of the box. Sadly I have no idea what could go wrong here.

Please try changing `v-model` into `:value="test.selectedTags"` and `@input="updateSelectedTags"` and check what arguments the `updateSelectedTags` method receives.
