### ISSUE TITLE
How can I change the "max" text?

### ISSUE THREAD

**Issue by heliomsolivas** [shentao/vue-multiselect#839]
How can I change it? That text: "Maximum of 2 options selected. First remove a selected option to select another." ?

**Comment by robinscholz** [comment]
Same question. Would be great if this was an option.

**Comment by shentao** [comment]
You can use the `maxElements` slot. :)

**Comment by shijinmk2006** [comment]
Appreciate for the feature implemented in this. But could you please help me on below

How can i hide the Default label "Maximum of 2 options selected. First remove a selected option to select another"?

**Comment by Roel-Hugens** [comment]
@shijinmk2006 Al little bit late, but you can override the text as @shentao mentioned in this way: 
`<template v-slot:maxElements>Your custom text here</template>`
