### ISSUE TITLE
pass second variable to async dropdown

### ISSUE THREAD

**Issue by nicolasvahidzein** [shentao/vue-multiselect#857]
Hello,

is it possible to pass a second variable to the functions in the async dropdown?

There seems to be an initial variable passed that is not apparent so i am not sure how to add a second one which is the UID since i am using a v-for loop to generate my async dropdown.

@search-change="employeesDropdownAsyncFind(emp.UID)"

**Comment by paolog22** [comment]
```
data() {
return {
 myCustomVar: 'viola'
}
}
```

```@search-change="employeesDropdownAsyncFind(emp.UID, myCustomVar)"```

**Comment by nicolasvahidzein** [comment]
@paolog22 hello,

i meant a second variable on top of "query", and "id" that are already passed implicitly.

Sorry if i was not clear.

**Comment by paolog22** [comment]
@nicolasvahidzein hi,
can you provide the code thanks

**Comment by shentao** [comment]
Why don't you use the `id` that is already passed as the second param? You could also try something like `@search-change="employeesDropdownAsyncFind($event, emp.UID)"`
