### ISSUE TITLE
Select-Search: Dropdown stuck after the first click

### ISSUE THREAD

**Issue by jippy89** [shentao/vue-multiselect#858]
Problem,
I was just trying to add v-model to v-select but after I've added `v-model='lokasi_select'` to the code it can't be clicked! Tried to reproduce in JSFiddle, however everything goes fine there..

### Reproduction Link
https://jsfiddle.net/irfandyjip89/tuL9w1g8/16/

### Steps to reproduce
I just copy pasted the needed code for it. The only difference is that my lokasi_list is actually connected to database using PHP. And it's already encoded to json.

**### Expected behaviour**
_Select with search_ like in the documentation
1. User type
2. User click the selected label
3. Input shown in the input table

**### Actual behaviour**
1. User type
2. User click the selected input
3. Dropdown stuck, won't close.
However it can be seen that the value change when I clicked on the label. It only change once. Tried clicking other label, didn't change.

What it looks like in my project:
![error vue_select1](https://user-images.githubusercontent.com/33748953/47066880-b2bfee80-d211-11e8-8cd4-4b6dca1dba5d.png)

I know the variables are different, but I assure you that's the only thing that's different. So after the first click of 'Mall Ciputra Jakarta' it stucks. But when I tried using Google Dev tools to check wheter the values are in, they have been filled.

Photo after first click, and dropdown element deleted using Google Dev Tools:
![error_vue_select2](https://user-images.githubusercontent.com/33748953/47067068-4d203200-d212-11e8-8d1c-68b6fca47da9.png)

However the second time I clicked none have changed. I can still interact with my other elements.

Error shown in Google Dev Tools:
![error_vue_select](https://user-images.githubusercontent.com/33748953/47066590-d0408880-d210-11e8-8326-c98a135b3ca2.png)

Also, side note, I discovered if you use Bootstrap 4 you got a little 'dropdown logo' after the vue-select's dropdown button. Can be checked on my FiddleJS, however that's another thing. For now, I'm just wondering what should I do in order to get that _search-select dropdown_ in documentation.

Thanks.

**Comment by shentao** [comment]
🙃 No problem :)
