### ISSUE TITLE
Multiselect fold-out visually below other content

### ISSUE THREAD

**Issue by axtg** [shentao/vue-multiselect#859]
### Reproduction Link
Not applicable

### Steps to reproduce
Have besides the multiselect component, another component that loads its contents dynamically (axios).

### Desired behaviour
Show the select fold-out on top of the other component's results.

### Actual behaviour
As the other component renders last, it will always render on top of the multiselect.

A picture says more than a thousand words...
![multiselect behind results](https://user-images.githubusercontent.com/61356/47158478-0bfc5080-d2ec-11e8-8513-4a86f5f60763.png)

### Already tried
**Z-index (e.g. -10) on result cards.** 
Result: elements become unclickable as they render behind the parent div

**Z-index (e.g. 10) on multiselect__select classes (e.g. active)**
Result: works when done in Firefox DOM inspector, but not when applied to code. Which I assume has to do with the later rendering of the results component.

Any ideas?

**Comment by shentao** [comment]
Wrap the component inside a `div` with `position: relative` and some higher `z-index`.
