### ISSUE TITLE
Unable to make vue-multiselect work as it should

### ISSUE THREAD

**Issue by Drillan767** [shentao/vue-multiselect#861]
Hello,
I'm experiencing a strange behavior with Vue-Multiselect, where everything works on your fiddle, but I get tons of problem once I try it on my own project. I'm rather new to VueJS (I work with it since a few months), so I might have done something obvious.

Here are my problems:

- When I copy / paste / adapt the code from your JSFiddle demo, I get the error "cannot read default of undefined" on the component declaration

```
components: {
  Multiselect: window.VueMultiselect.default <-- this
}
```

- When I start typing "VueMul~", WebStorm suggests me "VueMultiSelect". Upon selection, it adds the following:

```
import VueMultiselect from 'vue-multiselect/src/Multiselect'
// ...
components: {VueMultiselect},
```

The problem is that when I reload my page I get this kind of console errors:

```
vue.esm.js?efeb:591 [Vue warn]: Invalid prop: type check failed for prop "multiple". 
Expected Boolean, got String.

found in

---> <VueMultiselect> at node_modules/vue-multiselect/src/Multiselect.vue
       <ArticleNew> at src/components/admin/articles/ArticleNew.vue
         <AdminLayout> at src/components/admin/AdminLayout.vue
           <App> at src/App.vue
             <Root>
```

My `<template>` part looks like this:

```
<VueMultiselect
          :options="tags"
          :hide-selected="true"
          multiple="true"
          label="name"
          track-by="name"
>
</VueMultiselect>
```

- Despite the errors, it works, I retrieve my data but I can't delete anything. When I clicking the small 'x', a new error as shown previously shows up.

- I can't reproduce any of this on a JSFiddle, and it's getting me insane, because your component is godsend for what I need

As you saw in the error trace, I declared the component in a vue file. I tried declaring it in my "main.js", but it didn't change anything.

```
"vue": "^2.5.2",
"vue-multiselect": "^2.1.3",
```
 Thank you in advance

**Comment by LouWii** [comment]
Well, if you read the error message carefully `Invalid prop: type check failed for prop "multiple". 
Expected Boolean, got String.`, you will realize that this means `multiple="true"` is wrong as it's passing `true` as a string and not a boolean.

Try `:multiple="true"`, the column is making Vue to handle the prop, and should pass `true` as a boolean instead of a string. Note that this works for numbers as well, if you ever encounter the same problem in your code somewhere.

**Comment by shentao** [comment]
Thank you @LouWii for the answer 👍
