### ISSUE TITLE
How can i remove default selected green label when using property :multiple="true"

### ISSUE THREAD

**Issue by phongtrandang** [shentao/vue-multiselect#862]
I am using vue-multiselect which `:multiple="true"`, i can not find any document about how can i hide the selected label in input box like this

![vue multiselect jsfiddle](https://user-images.githubusercontent.com/15318099/47288939-9c0b0480-d622-11e8-9296-1e0fce846723.png)

**Comment by shentao** [comment]
Use the `selection` or `tag` slots. https://vue-multiselect.js.org/#sub-multiple-select

**Comment by akazorg** [comment]
The example in documentation is incorrect @shentao

Anyone looking for the answer: 
```
...
    <template 
        slot="selection" 
        slot-scope="{ values, search, isOpen }"
        >
        <span 
            class="multiselect__single" 
            v-if="values.length"
            >{{ values.length }} options selected
            </span>
    </template>
...
```
Happy coding :rocket:

**Comment by EthanHannn** [comment]
`<template slot="tag"><span class="custom__tag"></span></template>`
