### ISSUE TITLE
Missing styles for .multiselect__clear

### ISSUE THREAD

**Issue by Fokis** [shentao/vue-multiselect#867]
If you check css in dist folder you will see that its missing part for .multiselect__clear:
```
.multiselect__clear {
    position: absolute;
    right: 41px;
    height: 40px;
    width: 40px;
    display: block;
    cursor: pointer;
    z-index: 2;
}
.multiselect__clear::before {
    transform: rotate(45deg);
}
.multiselect__clear::after {
    transform: rotate(-45deg);
}
.multiselect__clear::after, .multiselect__clear::before {
    content: "";
    display: block;
    position: absolute;
    width: 3px;
    height: 16px;
    background: #aaa;
    top: 12px;
    right: 4px;
}

```
I've took this missing css from example on docs site.

### Reproduction Link
not required
### Steps to reproduce
not required
### Expected behaviour
not required
### Actual behaviour
not required

**Comment by vDupindev** [comment]
Thanks !

**Comment by shentao** [comment]
That’s because this is an element passed and styled in the example and not a feature of VueMultiselect itself.

**Comment by mschlitz-trux** [comment]
This was very helpful, thank you. I find it very weird that there is a slot for "clear" and nothing there by default...
