### ISSUE TITLE
method by pressing the down key or the up key

### ISSUE THREAD

**Issue by lordenas** [shentao/vue-multiselect#869]
Hi! Is it possible to add a method by pressing the down key or the up key? 
It is desirable that at a focus on a drop-down element, its value got to an input

![ice_video_20181102-163154](https://user-images.githubusercontent.com/15974195/47919420-61c22280-dec0-11e8-91c1-468131ce9be7.gif)

**Comment by shentao** [comment]
Not in v2. It will be possible in v3 though.
