### ISSUE TITLE
Multiselect is crashing when using groups and $isDisabled

### ISSUE THREAD

**Issue by sagg** [shentao/vue-multiselect#870]
Hi there,
i'm using grouped options and in case i provide `$isDisabled: true` in an option there is an error thrown in the console.

If i'm correct this should work? I only found this comment to disabled options:
https://github.com/shentao/vue-multiselect/issues/176#issuecomment-307638151

Thanks a lot!

### Reproduction Link
https://jsfiddle.net/sagg85/bdu2e73o/
(The shown example is a copy from the docs, i only added `$isDisabled`: https://vue-multiselect.js.org/#sub-option-groups)

### Steps to reproduce
Setting `$isDisabled` when using groups.
Remove `$isDisabled` from the example and everything is working fine. 

### Expected behaviour
VueMultiselect should appear.

### Actual behaviour
Error is thrown in the console.

**Comment by on4life** [comment]
+1, I have the same problem

**Comment by sagg** [comment]
I can confirm that this solves the issue.

**Comment by nazihnemri** [comment]
Hi there,
i'm using grouped options and in case i provide $isDisabled: true in an option there is an error thrown in the console. but it seems not working even after the fix , please help I have  the v2.1.3
**Reproduction Link:**
https://jsfiddle.net/m2kep3xj/

**Comment by LadyMashiro** [comment]
@nazihnemri Any solution? I got the same error.
**Reproduction link:**
[https://codesandbox.io/s/k09ml6wwko](url)

**Comment by akki-jat** [comment]
Hi @nazihnemri and @LadyMashiro, this issue will be fixed in next release.

**Note:** Fix for this bug has been merged but not released yet.

**Comment by shentao** [comment]
Released!
