### ISSUE TITLE
input value

### ISSUE THREAD

**Issue by riux** [shentao/vue-multiselect#874]
Hello, how to capture the value of the input and store it in a model element

**Comment by shentao** [comment]
You can use the `@search` event to receive the current input value, however that value is not persisting through the open/close actions. Given that this is a select/multiple-select component that supports complex data structures, the value can’t be easily stored inside an input element.

**Comment by riux** [comment]
I tried with:
 ```this.dataQuery = JSON.parse (JSON.stringify (query));```
 and does not store it, any recommendation

**Comment by shentao** [comment]
Please provide a JSFiddle where you show what exactly do you want to accomplish.

**Comment by riux** [comment]
thanks apparently I got this way
https://codepen.io/riux/pen/VVWjPd?editors=1010
