### ISSUE TITLE
read multi-select user typed text inside slot 'NoResult'

### ISSUE THREAD

**Issue by adilhraza** [shentao/vue-multiselect#876]
I have a multi-select on the page, working nicely, no issues, here's the code that renders the multiselect:

```
  <h3>Other / Inactive Ingredients:</h3>
  <multiselect id="inactiveIngredients"
                v-model="someObj.subObj.inactiveIngredients"
                label="name"
                track-by="id"
                placeholder="Type ahead or select..."
                :options="allInactiveIngredients"
                :multiple="true"
                :close-on-select="false"
                :clear-on-select="true"
                :hide-selected="true"
                :searchable="true"
                :preselect-first="false"
                @search-change="getInactiveIngredients"
                :disabled="!isDraft">
    <template slot="tag"
              slot-scope="props">
      <span class="prettify-selected">
        <span>{{ props.option.name }}</span>
        <span class="custom__remove fa fa-times"
              @click="props.remove(props.option)">
        </span>
      </span>
    </template>
    <template slot="noResult"
              slot-scope="props">
      No ingredients found. Check spellings or
      <a @click="addInactiveIngredient(props)"
          :disabled="!isDraft()">add new</a>
    </template>
  </multiselect>
```

i need to add new ingredient if not already there in the list. one (ugly way) is to have a button and input, a nicer and better way is to read the value that user already has typed in the multi-select and use that. see pic below:

![image](https://user-images.githubusercontent.com/12248896/48705865-55450600-ebf2-11e8-9644-077c7ebbf4d5.png)

how can i read the value `asdf` and pass it on to `addInactiveIngredient()` which is called on the `a` click in the `noShow` slot, i have tried different variations and been reading through the docs and existing 'noResult' questions for hints but can not figure this simple one out. i have tried the `<span slot="noResult".......` and the above one is my failed attempt to read props by putting the slot in `<template>` tag

**Comment by cheekudi** [comment]
Adil, I am looking to do exactly what you mentioned above and havent had any luck. Did you get it working and if so can you share your solution please ?

**Comment by adilhraza** [comment]
@cheekudi we ended up changing the design of the app to more mobile friendly way. So we didn't continue with the above approach.

**Comment by huanes** [comment]
@cheekudi Use data object as a placeholder of current search. @search-change event sends searchQuery 'asdf' or whatever you are currently typing as first parameter which you can then use in a handler. 
So do something like following.
```html
<template>
    <div>
        <multiselect @search-change="updateSearchText">
            <span slot="noResult" @click="doSomethingWithSearchText">
                Click me to do something with {{ searchText }}
            </span>
        </multiselect>
    </div>
</template>
```
```javascript
data() {
    return {
        searchText: ''
    }
},
methods: {
    updateSearchText (query) {
        this.searchText = query
    },
    doSomethingWithSearchText () {
        // do something with this.searchText
    }
}
```
