### ISSUE TITLE
Pre-selected values not selected in the vue-multiselect dropdown

### ISSUE THREAD

**Issue by PrimozRome** [shentao/vue-multiselect#878]
Why are my preselected options not selected when I open the select dropdown?

<img width="1103" alt="screenshot 2018-11-20 at 15 44 26" src="https://user-images.githubusercontent.com/1180467/48780990-5e5dd200-ecdb-11e8-97de-69333b20ca14.png">

This is the `value` prop of the `vue-multiselect` - preselected values

<img width="824" alt="screenshot 2018-11-20 at 15 46 56" src="https://user-images.githubusercontent.com/1180467/48781085-91a06100-ecdb-11e8-9e35-189383031208.png">

and this is the `options` prop

<img width="828" alt="screenshot 2018-11-20 at 15 47 10" src="https://user-images.githubusercontent.com/1180467/48781103-9fee7d00-ecdb-11e8-892b-6b444c9a2a24.png">

What am I missing here? The values should be selected when I open the dropdown correct?

**Comment by shentao** [comment]
Matching for objects is based on the property you pass to `track-by`. Make sure you pass `id` to track-by.

**Comment by PrimozRome** [comment]
> Matching for objects is based on the property you pass to `track-by`. Make sure you pass `id` to track-by.

Uff life saver. Thanks a lot.

**Comment by shentao** [comment]
No problem. :) Btw. even if an issue is closed, you can still comment.

**Comment by PrimozRome** [comment]
> No problem. :) Btw. even if an issue is closed, you can still comment.

Cool. We use your component a lot. Do you have a donate button somewhere to drop in for few beers?

**Comment by shentao** [comment]
Whoa! Been thinking about it a while ago and now that you mention I guess I should really consider doing something like https://www.buymeacoffee.com/. Thank you!

**Comment by PrimozRome** [comment]
Sure you should do it!

**Comment by shentao** [comment]
Thank you a lot! This is really encouraging to hear. 😃 Will work on it around December and let you both know.
