### ISSUE TITLE
Tagging without new tag

### ISSUE THREAD

**Issue by narkoze** [shentao/vue-multiselect#880]
Hello,
Is there a way to disable option to add new tag for "Tagging" and use only defined options?

**Comment by JGKL** [comment]
You can use this example: https://vue-multiselect.js.org/#sub-tagging and just remove the :taggable property.

**Comment by shentao** [comment]
@narkoze this is the default behaviour when you use `:multiple="true"`. You don’t need `:taggable="true"` to make the multiselect have pills/tag-like elements when selected. You just won’t be able to create new tags without using it.
