### ISSUE TITLE
The dropdown is not appearing after selecting any option from the list

### ISSUE THREAD

**Issue by Ravi-kavya01** [shentao/vue-multiselect#883]
Hi There,

I have an issue on the "Asynchronous select". After selecting an option from the list. The dropdown will never appear again.

**Comment by shentao** [comment]
This sounds like a issue in your code. Please provide a reproduction link (can be jsfiddle, codesandbox, whatever fits you).

**Comment by rewuxiin** [comment]
Hey.
I have the same problem. 
In laravel, I use search with the% like% method.
The search works - it returns the first results, however when I select the first tag and start looking for the next one - the drop-down list with new search results no longer appears.

I copied the code completely from the documentation and changed only the laravel request part.
Code
https://jsfiddle.net/bjt9hx2z/
And video problem
https://drive.google.com/open?id=1XVqCc0gnfUvtq67To0US0Fq2DVkcTVT4

Thanks
