### ISSUE TITLE
Long placeholder getting cut off

### ISSUE THREAD

**Issue by TomFranssen** [shentao/vue-multiselect#886]
### Reproduction Link
https://jsfiddle.net/jqofkzxc/6527/

### Steps to reproduce
Deselect the pre-chosen option. Click in the input and select another option. Click in the input to see the placeholder again. The placeholder text is now cut off. 

I tried setting the width of the placeholder using CSS but then the placeholder flows out of the container, see image:
![image](https://user-images.githubusercontent.com/1880964/49428206-b7326d80-f7a5-11e8-9da7-4baec982dfa1.png)

### Expected behaviour
To see the entire placeholder text.

### Actual behaviour
The placeholder text is cut off.

**Comment by shentao** [comment]
I think this could be solved by making the input use `display: flex` with `flex-grow: 1` so that it auto-expands to the width that is still available. Could you try that?

**Comment by NewkirkS** [comment]
I'm running into this same issue. Think I've got a fix, so I'll be making a PR.
