### ISSUE TITLE
Disable value for delete

### ISSUE THREAD

**Issue by 99percent6** [shentao/vue-multiselect#887]
Hi, how can I prevent deletion for a specific value (tag)?

**Comment by shentao** [comment]
In that specific case, you need to handle the selecting/deselecting manually. To do that you have to stop using `v-model` or `@input` and instead have two event handlers attached to `@select` and `@deselect`. The 1st one will have to add the option to your value list, the latter remove it and in your case – also prevent being removed when needed.

**Comment by mcmule** [comment]
Small detail: the proper slot for listening to deselect is `@remove` (and not `@deselect` as stated above). The solution is working fine, nonetheless.
