### ISSUE TITLE
"noOptions" slot is not documented

### ISSUE THREAD

**Issue by yaakovp** [shentao/vue-multiselect#888]
### Steps to reproduce
               <slot name="noOptions">List is empty.</slot> Isn't documented

### Expected behaviour
the slot is useful and need to be in the API list.
### Actual behaviour
the slot isn't in the list and I was forced to find it in the source code.

**Comment by spotman** [comment]
:+1: for that and for `showNoOptions` config option to completely disable this slot (useful when using debounce + async)

**Comment by sozzzzz** [comment]
noOptions attr was already documented here https://github.com/shentao/vue-multiselect/pull/854
But it seems the page was not updated

**Comment by enesesski** [comment]
<multiselect v-model="" :options="" placeholder="" label="">
<span slot="noOptions">Warning...</span>
</multiselect>

**Comment by mattelen** [comment]
Looks like this was fixed elsewhere as noOptions slot is documented, as you can see at https://vue-multiselect.js.org/#sub-slots
