### ISSUE TITLE
Cannot type in input box in the beforeList slot

### ISSUE THREAD

**Issue by babak-f** [shentao/vue-multiselect#894]
I need to use a custom input box at the beginning of the drop-down list, so I have defined the following content for the `beforeList` slot: 

```html
<template slot="beforeList" slot-scope="values">
  <input type="text">
</template>
```

But when I open the drop-down, I can't enter anything into the text box. I.e. when pressing keys on the keyboard, nothing gets written into the input box. 

When I move the input element outside the div with the class `multiselect__content-wrapper` (wrapper of the ul element with the list of values), it works. But that wouldn't help me in this particular case, since I need the input box to be part of the drop-down. 

`searchable` is set to false. 

Package version: latest (2.1.3)

**Comment by shentao** [comment]
Not possible in v2. This is because the component relies on focus to maintain its active state. This is however solved in v3 that should ship early next year.

**Comment by HasanKadi** [comment]
@shentao is this fixed or is there a workaround ???
because there is no v3 until now

**Comment by ganya-qwe** [comment]
@shentao no v3 yet for 5 years ?

**Comment by shentao** [comment]
@ganya-qwe https://github.com/shentao/vue-multiselect/tree/next

**Comment by florinionce** [comment]
@shentao I've checked the v3, however, this still does not seem to work. Is there a workaround for this? Thanks.

**Comment by shentao** [comment]
Hey @florinionce! I don't think there is a workaround apart from forking the project and making the changes yourself. I'm not actively maintaining it anymore.
