### ISSUE TITLE
Send extra data/parameter in @tag

### ISSUE THREAD

**Issue by marioene** [shentao/vue-multiselect#896]
First, great package!

My issue:
I have 40  multiselect components on my webpage and I want to detect which multiselect is focused/clicked.

I don't want to make addTag method for every component. I want to make a generic function.

` <multiselect :options="options_id_of_the_component"  :taggable="true" tag-placeholder="Add new item" @tag="addTag('id_of_the_component')"  v-model="id_of_the_component_value"  ... ></multiselect>` 

So, how can I send extra data in @tag event to implement in method addTag(newTag) ?

Is it possible to build a method like this?

```
...
methods: {
        addTag (newTag, id_of_the_component) {
          const tag = {
            name: newTag,
            code: newTag.substring(0, 2) + Math.floor((Math.random() * 10000000))
           }
           this['options_'+id_of_the_component].push(tag)
           this[id_of_the_component+ '_value'] = [];   // clear selected value
           this[id_of_the_component+ '_value'].push(tag)
         }
}
...
```

If I can send a new parameter  (beside newTag), like the id in @tag event, my problem is solved!

**Comment by lear-cash** [comment]
<multiselect id='test' @tag="addTag" ></multiselect>
methods: {
        addTag (newTag, id) {
           console.log(id)  //  test
         }
}

Does that help you？
