### ISSUE TITLE
Multiple select, slot="selection" does not work

### ISSUE THREAD

**Issue by karkius** [shentao/vue-multiselect#899]
Multiple select [Documentation](https://vue-multiselect.js.org/#sub-multiple-select)  says that a slot "selection" can be used, but it is nowhere to be found in available slot list and it does not work if I just use the sample code. How can I control the display of multiple options selected?

 Edit: it works, but it's not documented properly.

**Comment by rriixx** [comment]
can you please let us know how you solved it?

**Comment by shentao** [comment]
@rriixx You can either use the selection slot to modify the whole selection area (for example to replace tags with a text like in the linked docs example) or use the "tag" slot to modify each selected element.

**Comment by Vemir98** [comment]
> Multiple select [Documentation](https://vue-multiselect.js.org/#sub-multiple-select) says that a slot "selection" can be used, but it is nowhere to be found in available slot list and it does not work if I just use the sample code. How can I control the display of multiple options selected?
> 
> Edit: it works, but it's not documented properly.

can you please let us know how you solved it?

**Comment by karkius** [comment]
After all this time not sure if this is the relevant code, but "multiselect" with "slot="selection" " in my code looks like:

```        
<multiselect @close="closed" @select="selected" @open="opened" ref="multiselect" v-model="selectedlist" 
                    :options="options"
                    :multiple="true"                     
                     :placeholder="placeholder" 
                     :searchable="false" 
                     :show-labels="false"
                     label="text" track-by="value">
            <template slot="selection" slot-scope="{ values, search, isOpen }">
                <span style="height:19px;white-space: nowrap;overflow:hidden;display: block;">{{ values.map(v=>v.text).join(', ') }}</span>
            </template>
        </multiselect>
```
Key detail being the `<template slot="selection"...</template>` inside `<multiselect></multiselect>`

Hope this helps

**Comment by DanyDes** [comment]
Well in my case, I must recommend to check the version, I was working with the CDN 2.1.0 which is in the docs, I tried the example and failed. I updated to 2.1.6 and works as expected.
