### ISSUE TITLE
Multiple select with mandatory options

### ISSUE THREAD

**Issue by jcasale** [shentao/vue-multiselect#900]
Is there any way to force an option to be mandatory in a multiple select? I have criteria by which certain options must be preselected? It doesn't appear there is a slot for the individual options in a multiple select like there is for `singleLabel`? It appears that `@onRemove` is called before the actual option is removed so while adding it back during the event works, its a gross hack.

**Comment by shentao** [comment]
You have to handle the `@input` event yourself rather than using v-model. There in the handler, you just need to make sure the new value contains the mandatory values.
