### ISSUE TITLE
Custom option template with Html

### ISSUE THREAD

**Issue by drakakisgeo** [shentao/vue-multiselect#902]
I have this code that doesn't work.
```
<template slot="option" slot-scope="option" v-html="option.text"></template>
```
option.text has html tags that I don't want them to be stripped down. (v-html is ignored) Any idea how to do this?

**Comment by shentao** [comment]
Could you try 
```
<template slot="option" slot-scope="option">
{{{ option.text }}}
</template>
```
Notice the triple `{{{`.

**Comment by drakakisgeo** [comment]
> 
> 
> Could you try
> 
> ```
> <template slot="option" slot-scope="option">
> {{{ option.text }}}
> </template>
> ```
> 
> Notice the triple `{{{`.

No, I get "Syntax Error: Unexpected token"

**Comment by shentao** [comment]
In that case try putting a `<span v-html="option.text"/>` inside the `<template>` tag.
