### ISSUE TITLE
multiselect dropdown won't open inside vue-awesome-swiper

### ISSUE THREAD

**Issue by ig1na** [shentao/vue-multiselect#906]
Hello, 

I have an issue when using multiselect inside a swiper-slide from vue-awesome-swiper, it seems that the event that opens the dropdown menu isn't firing so the menu won't open. When checking with Vue dev tools, the isOpen property is not changing inside the multiselect component

https://jsfiddle.net/nx51L3zs/

**Comment by ig1na** [comment]
well I noticed that it works on mobile, and that it works if I right click too.. very strange, I keep investigating

**Comment by lewiswilby** [comment]
Hi @ig1na,

Did you find a solution to this in the end? How did you configure vue-awesome swiper to get around the focus event?

**Comment by JoeKaldas** [comment]
@ig1na @lewiswilby  Did you ever find a solution for this?
