### ISSUE TITLE
After a search, if I use the scrollbar, the search scope is lost

### ISSUE THREAD

**Issue by MatthiasRMS** [shentao/vue-multiselect#910]
Hi,

I have an issue after typing a search query.
If I have many search results, and scroll a little, the vertical scrollbar will appear. If I use it by clicking and holding it with a mouse, the options visible instantly come back to all options, completely losing the search results. 

### Reproduction Link
Here is a fiddle. 
https://jsfiddle.net/jkdzea4g/

### Steps to reproduce
If you type "a", then scroll, the bar appears. Try to scoll using the vertical scrollbar instead of a trackpad. You'll then see all the options instead of the search results.

### Expected behaviour
Being able to scroll using the scrollbar without losing all the results

Let me know if this isn't clear or if you have a hard time reproducing.

**Comment by shentao** [comment]
Hey! Thanks for reporting. I noticed that the fiddle is using an older version of the library. I tried to reproduce the issue using the newest version and it seems to be working correctly. See: https://jsfiddle.net/xovebmjh/
