### ISSUE TITLE
SelectedLabel as a function instead of string and make certain items disabled

### ISSUE THREAD

**Issue by HereIsJimmy** [shentao/vue-multiselect#912]
Came around two issues while using this:
1. The need of making some items non-selectable when using categories inside the multiselect. I actually worked out a workaround via adding an on-click event inside the option slot and adding stopPropagation when the item should be disabled.
2. Using a function instead of a string as selectedLabel prop. This way we could recieve the current selected item and show one text or another.

edit: Just to extend this a little and explain myself a bit better, I came around all this while showing items from some kind of a hierarchy tree, where just the leaves may be selectable. All the different levels from inside the tree are from a different kind, therefore I would like to show their kind in the **selectedLabel**

For now I just convert the tree to an ordered array and make each node type to have a different _padding-left_

**Comment by shentao** [comment]
Hey! I think that if you add `.$isDisabled` to the option it will automatically become disabled on the options list. Try `$disabled` if the other property doesn't work.

**Comment by shentao** [comment]
As for tree like structures of options - in v3 you should be able to pass a custom component to handle the list. The selected value will have to stay a flat array though.
