### ISSUE TITLE
Vue-multiselect dropdown menu positioned wrong at resolution 1366x768

### ISSUE THREAD

**Issue by akagamina** [shentao/vue-multiselect#919]
Hello

I use multiselect on my project. usually i dont hit a problem. But when i at resolution 1366x768 dropdown menu at wrong positioned.

[this is 1920x1080](https://imgur.com/g9dVxR9) and no problem.

[and this is 1366x768](https://imgur.com/HnaLvub) and wrong positioned.

how can i fix this. my english not very well sorry for this.

**Comment by shentao** [comment]
Hey. This is actually the desired behavior. You can control the direction where the dropdown opens with `openDirection`. It defaults to auto, which results in the dropdown being open where there is more space.
