### ISSUE TITLE
Wrong selection behavior with slot, after Vue released to 2.6.2

### ISSUE THREAD

**Issue by blok1993** [shentao/vue-multiselect#923]
### Reproduction Link
https://jsfiddle.net/ue6cL75n/1/

### Steps to reproduce
Click on span class="library" element, and that option won't be selected / deselected. 

### Expected behaviour
Option should be selected, wherever i click inside li class="multiselect__element"

### Actual behaviour
Option wasn't selected when i clicked on span class="library". That worked with previous vue releases.

**Comment by shentao** [comment]
There was an regression with slots in Vue 2.6.4 and should now be fixed in 2.6.5. Please give it a try with the new version and let me know if it works properly.
