### ISSUE TITLE
Templates necessary for taggable single select with async search

### ISSUE THREAD

**Issue by jcasale** [shentao/vue-multiselect#928]
### Reproduction Link
[fiddle](https://jsfiddle.net/ritmo2k/xdp7a6gf/)

### Steps to reproduce
I am trying to implement a taggable single select with an async search on strings. When the fiddle has `:multiple="true"` and the behavior is expected.

### Expected behaviour
When setting `:multiple="false"`, I cannot determine the correct combination of slots and properties to be able to delete a currently selected value. I can style the selected option, however I cannot determine the appropriate template for enabled remove functionality.

### Actual behaviour
The remove functionality must be manually implemented in single select and hence the option cannot be unselected. You can overwrite the tag with either a new tag or a new async search value, but the form behavior is unexpected and unintuitive.

**Comment by shentao** [comment]
Great catch! I think we really need the clear button mentioned in #915. Closing this one, since it will be solved once the clear button is implemented.
