### ISSUE TITLE
[Question] Simple value

### ISSUE THREAD

**Issue by alexpts** [shentao/vue-multiselect#930]
I try to use component with my traditional form and have some problem.
Backend to store only the select value of the field and. I expect to pass to value only tag-option attribute value, but not complex object. After select new value, I expect push scalar value to data property, but not complex object.

Demo - https://jsfiddle.net/f74oxn9e/4/

Can I get this behavior? It is classical behavior for html form.

**Comment by shentao** [comment]
This is not built-in. You would need to create a computed property and a `@input` handler that handle it. Sadly, there are multiple edge-cases when using just the value (that is used by track-by).

There are other issues on the topic, so you can look for examples on how to do it there.

**Comment by alexpts** [comment]
@shentao can you share link to similar examples?

**Comment by shentao** [comment]
https://github.com/shentao/vue-multiselect/issues/385
