### ISSUE TITLE
noOptions message

### ISSUE THREAD

**Issue by wapewape** [shentao/vue-multiselect#931]
Hi
I need translate noOptions and noResult message 

I try <slot name="noResult"> new message </slot> en my template
but no work

i need translate this messages:
<slot name="noResult">No elements found. Consider changing the search query.</slot>
<slot name="noOptions">List is empty.</slot>

![hagamelatarea](https://user-images.githubusercontent.com/1838797/53197532-3000d300-35f9-11e9-91c4-4a58a34de142.png)

**Comment by quentinus95** [comment]
I need exactly the same thing.

**Comment by shentao** [comment]
Hey!
https://jsfiddle.net/jbzkhowx/ it seems to work properly.
The `noOptions` slot is used when no options have been passed.
The `noResult` slot is used when no option is matching the query.

**Comment by jerearaujo03** [comment]
`noOptions` slot didn't work for me
