### ISSUE TITLE
How to pass parameter in @select="method( extra )" ?

### ISSUE THREAD

**Issue by therakib7** [shentao/vue-multiselect#933]
First, I would like to thank for your great vue component. But I have a problem to watch an array object property.

My component code looks like this.

```
data: function () {
    return {   
        products: {  
            product: [ 
                { product_id: '', price: ''}, 
                { product_id: '', price: ''},  
            ],
            another_field: '',
        },  
    }
},
```

Here 'product_id' is a vue multiselect field. Now I want to get object index when 'product_id' changed. I didn't get any solution in vue to get the object index. Now I'm thinking to pass object index in @select="method( key )" when v-for loop in templating. 

Is there any way to pass an extra parameter in @select="" or any other solution to solve my problem. 

Thanks

**Comment by shentao** [comment]
Hey! Thanks for the kind words.

I would probably suggest a different data architecture. The `products` property looks as if it should be an array. It also misses a `selectedProduct` property that could store the selected element. I don’t really see why you need to use `@select`? Please take a look at the docs https://vue-multiselect.js.org/

**Comment by therakib7** [comment]
Please see it https://stackoverflow.com/questions/54877945/vue-js-how-to-watch-property-of-nested-object-and-get-index  I think you will understand

**Comment by shentao** [comment]
I see. The events are emitted with an additional param, called `id` that you can pass as `:id="key"`. Then your method will receive it as the 2nd param. See docs: https://vue-multiselect.js.org/#sub-events
