### ISSUE TITLE
Unhandled promise rejection TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by WillGoldstein** [shentao/vue-multiselect#936]
Seeing this error:

![image](https://user-images.githubusercontent.com/20759342/53580144-fbd16900-3b48-11e9-80ed-63cf75fd76e0.png)

Anyone else seeing this or is it me?

V 2.1.0

**Comment by shentao** [comment]
Probably not related to this library. Please provide more context, repro link or fiddle.
