### ISSUE TITLE
How to keep dropdown open for styling?

### ISSUE THREAD

**Issue by robSIG** [shentao/vue-multiselect#940]
I realise there's a whole bunch of issues created about custom styling. I've got no issue writing my own CSS but the problem is you can't inspect element because it always loses focus and closes the searchable dropdown. So it's a nightmare to try and find what styles you want to change.

Is there a way around this? Just some way of forcing it to be open and never close?

### Steps to reproduce
I attempted to edit the `multiselectMixin.js` and changed `deactivate()` to just return nothing

```
deactivate () {
    return
}
```

Hoping this would stop it closing, but apparently not.

Is there anyway to keep it open all the time? Or is there a better way to play with the styles that i'm just unaware of?

**Comment by sabob** [comment]
Hi,

In Chrome, with the devtools open, open the multiselect then hit F8 to pause the debugger. Should work.

**Comment by shentao** [comment]
Yeah, that’s a tricky thing. It should be easier to debug/style when v3 ships since it changes the way the `active` state is working.
