### ISSUE TITLE
Vue-Multiselect loses focus when Vuex forces re-render by using Vue.set() or object.assign()

### ISSUE THREAD

**Issue by antopravin** [shentao/vue-multiselect#942]
### Reproduction Link
The above jsfiddle doesn't seem to have vuex support, it would be great if one with Vuex support is provided
### Steps to reproduce
1. Create a store with selected state for example.
state: {
selected: {}
}
2. commit a mutation to add a dynamic property 'value'
selected: {
  value: []
}
Since 'selected.value' was not created as part of the initial store, it won't be reactive. (THIS IS IMPORTANT)
https://vuejs.org/v2/guide/reactivity.html
Use Vue.set(state.selected, key, value) to trigger Vue update on this key.
3. Wire up @select and @remove to commit mutations to update Store's selected.value
4. Set up property :close-on-select to false

### Expected behaviour
1. On a select/remove event, close event is not triggered
2. Component does not lose focus from the text field

### Actual behaviour
1. On a select/remove event, close event is triggered
2. Component does lose focus from the text field

**Comment by shentao** [comment]
You can create a codesandbox to showcase Vuex related behaviour.
