### ISSUE TITLE
Detecting keypresses

### ISSUE THREAD

**Issue by FunnyB0y** [shentao/vue-multiselect#943]
Is there anyway to detect keypresses at the moment? I'm trying to make it so if there's an `enter` keypress on an empty search value, it will run my search function.

Tried:
```
                <MultiSelect 
                    @keypress.enter
                    @keydown.enter
                />            
```

**Comment by shentao** [comment]
I don't think that's possible right now. However you can react the the search query changing using `@search`. I hope that helps.

**Comment by vvmspace** [comment]
It is actual!
