### ISSUE TITLE
Selecting a group may cause selection of duplicate items

### ISSUE THREAD

**Issue by joaomlink** [shentao/vue-multiselect#945]
### Reproduction Link
https://vue-multiselect.js.org/#sub-option-groups
### Steps to reproduce
1.  Open groups multi-select and select the item **Vue.js**
2. Open again groups multi-select and select group **Javascript**
### Expected behaviour
Only Vue and Adonis should be selected ex: [Vue, Adonis]
### Actual behaviour
Vue gets selected two times ex: [Vue, Vue, Adonis]

**Comment by shentao** [comment]
This does look like a regression. Thanks for catching this!

**Comment by alxMartynova** [comment]
Inside multiselectMixin.js line 564: function "selectGroup" - instead of || put && like: 
`const optionsToAdd = group[this.groupValues].filter(not(this.isSelected) && not(this.isOptionDisabled))`

Fixed the issue for me

**Comment by teuneboon** [comment]
Do you have any pointers or ideas on where to look to get this fixed? I can take a look at it then. It's quite an annoying bug for us right now.

**Comment by teuneboon** [comment]
Managed to fix it: #968
