### ISSUE TITLE
Documentation out of date for Multiple select

### ISSUE THREAD

**Issue by jcasale** [shentao/vue-multiselect#949]
### Reproduction Link
[Fiddle](https://jsfiddle.net/ritmo2k/4gr2wy7t/)

### Steps to reproduce
Copy the code from [Multiple Select](https://vue-multiselect.js.org/#sub-multiple-select) and compare the results to the embedded app.

### Expected behaviour
The resulting app resembles the app within the documentation.

### Actual behaviour
In the documentation, as you select options, they don't appear while the dropdown is open. They also don't appear when it is closed as a template is evidently configured.

However in the fiddle, they appear as you select them, and are then hidden once the dropdown closes. A note in the documentation suggests a template exists for this:
```html
<template slot="tag" slot-scope="props"><Your code></template>
```
However without a value, it is ignored.

What is the optimal way to prevent options from being displayed when the dropdown is open?

**Comment by shentao** [comment]
The Fiddle uses an outdated version of the component (v2.1.0). The current version is 2.1.4.
See: https://jsfiddle.net/7ox2tnfq/

**Comment by jcasale** [comment]
Hi, thanks for the quick response.
However, the behavior is unchanged (even after bumping the css to the same current version).

The issue is the document presents a component configuration which is desirable when selecting several options, however the code does not produce that result even with a current dist.

**Comment by mschlitz-trux** [comment]
Yep, I ran into this same issue, as there was no discernible flag to disable the "tags" as a whole (instead, only flag to disable "new" user-entry tags).

Took me way too long to figure it out, but you just need to supply an empty slot for "tag", but at least give it one element:
`<template slot="tag"><span></span></template>`
