### ISSUE TITLE
Vue MultiSelect Major Version 3.0 Roadmap

### ISSUE THREAD

**Issue by leipert** [shentao/vue-multiselect#958]
@shentao. First of all: Thanks for this library and giving great talks at Vue.JS conferences. I particularly enjoyed https://www.youtube.com/watch?v=Rql3BsT9WKA which you gave in a similar fashion in Berlin at the Vue.JS road trip.

I am bringing this up because that talk definitely peaked my interest in the infrastructure you are planning for vue-multiselect in the next major version.

Looking at the open issues / branches, I wondered whether you are able to give a roadmap for 3.0, and whether there is something the community could support you with! I haven't found any meta issue to discuss this, so I just opened this one up and see where it goes.

Again, thank you for your time and dedication on this project.

**Comment by shentao** [comment]
Hey! Just published the roadmap: https://github.com/shentao/vue-multiselect/issues/963
Would appreciate your feedback!
