### ISSUE TITLE
[Question] Setting prop defaults globally

### ISSUE THREAD

**Issue by Nfinished** [shentao/vue-multiselect#960]
Sorry if this is in the docs, but when registering vue-multiselect globally is there a way to provide default values for properties? eg defaulting the `showLabels` prop to false instead of true.

**Comment by shentao** [comment]
I'd say, create a functional component that would work as a wrapper with some preexisting props that match your default config + pass all the other attributes, props and listeners to the real component. This is called a transparent component / wrapper. 
Pretty useful!

**Comment by Nfinished** [comment]
That's an excellent suggestion, thanks!
