### ISSUE TITLE
Allow initial value to be only an identifier and not the full structure

### ISSUE THREAD

**Issue by Tofandel** [shentao/vue-multiselect#961]
When setting the value using v-model you need to pass the full structure of the option, this is not ideal because you may not always know the full structure and in the vanilla select it does work like this ([you can see it in the vue doc](https://fr.vuejs.org/v2/guide/forms.html#example-7))
```
data: {
    value: 'rail', //This doesn't work
    value:  { value: 'rail', name: 'Rails', language: 'Ruby' }, //This does
  	options: [
        { value: 'vue', name: 'Vue.js', language: 'JavaScript' },
        { value: 'rail', name: 'Rails', language: 'Ruby' },
        { value: 'sinatra', name: 'Sinatra', language: 'Ruby' },
        { value: 'laravel', text: 'Laravel', name: 'Laravel', language: 'PHP', $isDisabled: true }
      ]
	},
  computed: {
      value: {
          get: function () {
            	return this.options.find(function(el) {
            		return el.value == 'rail' 
            	}); //This does work
          }
     },
  },
```

### Reproduction Link
In the following fiddle you can see the vanilla select, the computed value and the non computed values behavior
https://jsfiddle.net/xvecnhdm/1

It would be nice to be able to use `value: 'rail'` by default instead of having to use a computed value to find the right selected option

**Comment by shentao** [comment]
This question has already been asked. You will have to provide the whole value or at least a minimal structure that is enough to compare and display a label. This is due to the support for async multiselect, where the currently selected elements might not be available in the options list.
I’m currently thinking how to solve it in the 3.0 release.

**Comment by Tofandel** [comment]
[This plugin](https://github.com/sagalbot/vue-select/ ) offers this option in the [reduce prop](https://vue-select.org/guide/upgrading.html#index-prop-replaced-with-reduce)
You might want to take a look

**Comment by shentao** [comment]
@Tofandel yup, I’ve seen this recently and thought about something similar for this library. Just need to consider all use cases. :)

**Comment by mojtabaahn** [comment]
any updates about this feature :-( ?

**Comment by jetlej** [comment]
A reduce function would be VERY helpful
