### ISSUE TITLE
hi, change lang!

### ISSUE THREAD

**Issue by karelbyte** [shentao/vue-multiselect#962]
Hi, I would like to be able to change the language, how can I do it?

**Comment by shentao** [comment]
Hey! I’m not sure what you mean? Would you like to modify the placeholder or the prompts inside the dropdown? There are props for that. See docs: https://vue-multiselect.js.org/#sub-props

**Comment by khayyak** [comment]
anyone wants to change language of some elemnts like placeHolder or empty list message to any language he wants , you can use something like this (I use arabic language) :
<multiselect v-model="value2" :options="modules" :close-on-select="true" :preserve-search="true" placeholder="Module" selectLabel="اضغط لاختيار هذا العنصر" label="intitule" track-by="id" id="example2" @select="onSelect2" > <span slot="noOptions">اللائحة فارغة</span> <span slot="noResult">لا توجد نتيجة</span> </multiselect>
and of course you can use props and slots to change what you want using this link : https://vue-multiselect.js.org/#sub-props

hope this can help someone .
