### ISSUE TITLE
sort according to options

### ISSUE THREAD

**Issue by essamtariq123** [shentao/vue-multiselect#965]
Hi hope you are doing great. 
so my issue is let say my options array is
[
        "monday",
        "tuesday",
        "wednesday",
        "thursday",
        "friday",
        "saturday",
        "sunday"
      ]

when I select multiple like ['monday','wednesday','tuesday']

can i then sort it out like the option? meaning it will sort out to ['monday','tuesday','wednesday']

**Comment by shentao** [comment]
Hey! Thank you :)
I’m not exactly sure what you mean, but you can manipulate the `options` list freely inside the parent component. There is however, no way to sort it inside the Multiselect component though.

**Comment by mariusa** [comment]
The component should keep the sort order as given initially. When search is enabled and one types something, the sort is random.

**Comment by michaelvalenti** [comment]
I have the same problem. Basically the options are sorted alphabetically and when I search the sorting is random.

**Comment by zhuwei** [comment]
I have the same problem，It's unbelievable that the order of options in the dropdown menu is completely different from the order of options

**Comment by shentao** [comment]
You can set the `internalSearch` prop to `false`. This will disable the internal filtering and sorting. After that, you can listen to the `@search-change` event to get the current search query and perform the search and sorting on your own as needed. @zhuwei
