### ISSUE TITLE
Error in nextTick: "TypeError: Cannot read property 'focus' of undefined"

### ISSUE THREAD

**Issue by lukeKonopka** [shentao/vue-multiselect#966]
I am getting following error when running automated tests on our app:
![image](https://user-images.githubusercontent.com/1548278/56134836-ae417c00-5f8f-11e9-8e6a-01db43156d0f.png)
It's thrown because for some reason all `$refs` are undefined in this callback inside `$nextTick`:
https://github.com/shentao/vue-multiselect/blob/8c162dd01a4b0d85eb405d5c116b3f9080b612d1/src/multiselectMixin.js#L656

![image](https://user-images.githubusercontent.com/1548278/56137546-6291d100-5f95-11e9-8e4c-1c60c9369869.png)

It might be related to the fact that there is a `v-if` on the multiselect component, as well as on the parent component (the issue seems to happen when those values change to false - the components are removed from DOM).

Possible fix would be to check if `$refs.search` is not undefined before calling `focus()` on it.

I tried to reproduce this on jsfiddle, but was unsuccessful.

### Reproduction Link
None

### Steps to reproduce
Hard to reproduce, as it happens only when running automated tests, and even then, only sometimes.

### Expected behaviour
No error

### Actual behaviour
Error present

**Comment by xrei** [comment]
Have simillar issue but with `blur()`
![image](https://user-images.githubusercontent.com/9521710/57153505-29ec5700-6ddf-11e9-9e93-0c2da6324c57.png)

**Comment by emerg** [comment]
I'm also having a similar issue. 
When I am typing into the input box, and then delete, if I hit the delete key one additional time, I get the same "TypeError: Cannot read property '$isDisabled' of undefined", as well as "Cannot read property 'blur' of undefined" any ETA on a fix?

**Comment by Astray-git** [comment]
### Reproduction Link
https://jsfiddle.net/1e97k8pf/

### Steps to reproduce
1. click gotobar
2. open the select dropdown
3. click browser back button
4. errors in console

**Comment by jagroop** [comment]
This is still issue. Using latest version of vue-multiselect

**Comment by sontd-0882** [comment]
The latest version is 2.1.6, it's still haven't included this fix yet.

https://github.com/shentao/vue-multiselect/blob/904d10fb1b/src/multiselectMixin.js#L658

**Comment by bennettfrazier** [comment]
Found this to be due to `nuxt-link`, was getting $el of undefined whenever I tried to focus. Changed from nuxt-link to
``` vue
<button :ref="`gallery-btn-${id}`" @click="customEvent(id)"> 
```
``` js
customEvent(id) {
  if (process.browser) {
    const activeButtonRef = `gallery-btn-${id}`
    // focus on active button after slide changes
    this.$refs[activeButtonRef][0].focus();

    // manual route change instead of nuxt-link
    this.$router.push({ hash: id });
  }
}
```

**Comment by Etheryte** [comment]
As mentioned above, this is still a problem with the latest release @p-adams and it would be appropriate to reopen the ticket until it gets resolved. Are there any blockers for getting a new release out with the relevant changes?

**Comment by Jeremy720** [comment]
having the same issue when opening the multiselect, then navigating via browser back button.

**Comment by rnunezherrer** [comment]
Still not in production
