### ISSUE TITLE
Undefined-errors

### ISSUE THREAD

**Issue by TiborMalmo** [shentao/vue-multiselect#967]
Hello! 

I am working on a system where i use the multiselect component for adding users. 
When a user is pressing backspace two times in the multiselect component, the system seems to error out and the console log states 
`app.js:488 TypeError: Cannot read property '$isDisabled' of undefined`
and
`TypeError: Cannot read property 'blur' of undefined`

Has anyone experienced anything similar to this issue, and how did you solve it?

**Comment by cmorbitzer** [comment]
The first one, at least, is fixed by #939

**Comment by TiborMalmo** [comment]
Thank you! 

Then i guess it's just to wait for the next release 😄
