### ISSUE TITLE
How to use it as menu

### ISSUE THREAD

**Issue by mrodal** [shentao/vue-multiselect#971]
Hi, is there a way to use it as a simple menu?
What I would need is like a simple select with a fixed placeholder that never goes away, even when an option is selected.
I couldnt find in the docs something like this
Thanks!

**Comment by mrodal** [comment]
I ended up making the multiselect invisible by giving it height 0 and using another button to open it programatically

**Comment by shentao** [comment]
That’s a valid way, though I would probably go for something much simpler though.
