### ISSUE TITLE
Remove event does not emit 'id'

### ISSUE THREAD

**Issue by PrimozRome** [shentao/vue-multiselect#983]
v. 2.1.3

In the docs it says that remove event submits `removedOption` and `id` as payload:

Remove | (removedOption, id) | @remove | Emitted after removing an option

**Actual payload:**

<img width="1228" alt="Screenshot 2019-05-15 at 16 40 55" src="https://user-images.githubusercontent.com/1180467/57784562-62215d00-7730-11e9-83aa-2afd300bc8d8.png">

**Comment by shentao** [comment]
The `id` is the `id` prop that you can pass. Not the track-by property value.

**Comment by PrimozRome** [comment]
@shentao 

it was supposed to return the same as `selected` event right?

For me it does not. On the same field I have bot `selected` and `remove` events:

```
    handleVueMultiSelect(value, field) {
      console.log(value, field)
      this.$emit('form:field-selected', value, field)
    },

    handleVueMultiDeselect(value, field) {
      console.log(value, field)
      this.$emit('form:field-deselected', value, field)
    },

```

But the output of above console.logs is different:

<img width="1222" alt="Screenshot 2019-05-15 at 17 03 20" src="https://user-images.githubusercontent.com/1180467/57786208-600ccd80-7733-11e9-948f-fc213ac34c01.png">

**Comment by shentao** [comment]
Take a look:
https://github.com/shentao/vue-multiselect/blob/master/src/multiselectMixin.js#L615

Also, why do you need to handle `@select` and `@remove` instead of just using `@input`?
