### ISSUE TITLE
block the removal of options

### ISSUE THREAD

**Issue by lscavelli** [shentao/vue-multiselect#989]
Congratulations for the component. well done
I would like to know if there is a way to prevent the removal of the option (not last)
ex.. @remove="onRemove"

onRemove (selectedOption) {
if (selectedOption.id == 36) {
	// not remove option
}
thank you so much

**Comment by shentao** [comment]
Thank you! 
Don't use v-model or `@input` to update all the selected options in batch, instead rely on `@select` and `@remove` to manage all elements individually. This way you can control if you want to remove something or not. 👍

**Comment by zeeshan09** [comment]
@shentao if we dont use v-model or @input how would the values be populated in the multiselect input

**Comment by shentao** [comment]
@zeeshan09 you can still pass `:value="selectedOptions"` to set up the value of the multiselect input. Later you will have to manually update `selectedOptions` by reacting to the `@select` and `@remove` events.

**Comment by zeeshan09** [comment]
@shentao Alright. Thanks!! :)
