### ISSUE TITLE
Option groups not searchable

### ISSUE THREAD

**Issue by ntoljic** [shentao/vue-multiselect#997]
Hello and first of all, thanks for your amazing work!

Not sure if this is a bug or intended behavior, but here it goes.

### Reproduction Link
https://vue-multiselect.js.org/#sub-option-groups

### Steps to reproduce
Type 'Ruby' into the search box

### Expected behaviour

The selection group 'Ruby' should be found, and selecting it should select the entire group

### Actual behaviour

The selection group 'Ruby' is not found, as the search-engine apparently only considers leaf options.

Would be great if this could be added into the component. If not, how would one go about implementing this with a custom search logic?

**Comment by ntoljic** [comment]
Any feedback would be appreciated :)

**Comment by ntoljic** [comment]
Really, any feedback ;)

My use case is that there is a large list of municipalities, that are grouped by region. It would be great to have the ability to search for the region as well, not just the municipalities.

**Comment by koljada** [comment]
I also have the same requirement

**Comment by ntoljic** [comment]
Since this issue is getting stale I did some digging and found https://vue-treeselect.js.org.
Closing this issue as vue-treeselect is a viable alternative for me.
